### ISSUE TITLE
No Medication resources conforming to the profile (FI-1539)

### ISSUE THREAD

**Issue by dwebe003** [onc-healthit/onc-certification-g10-test-kit#101]
I am encountering this skipped test during the MedicationRequest section tests.
![Screen Shot 2022-04-19 at 2 13 49 PM](https://user-images.githubusercontent.com/6394944/164103263-bfdd0bd3-4a3f-48a1-8b99-4d81e3e39049.png)

Yet our `medication` field in the previous responses seems to be correct, as seen below:
![Screen Shot 2022-04-19 at 2 20 28 PM](https://user-images.githubusercontent.com/6394944/164103911-6d7a454e-ead3-4cc5-8058-7b9d5e06833e.png)

Is there something I'm missing? The structure seems to match the profile for a medication field of type CodeableConcept, and looks similar to the examples I've seen on the structure definition page.

**Comment by arscan** [comment]
Could you confirm that none of the MedicationRequests you are providing have references to Medication resources?

**Comment by dwebe003** [comment]
Correct. None are references, only CodeableConcepts.

**Comment by dwebe003** [comment]
@arscan Awesome! Thanks for the update. Glad you were able to reproduce that.

**Comment by dwebe003** [comment]
I tried pulling from master a couple days ago and I still experienced this issue. Is this something I'll just have to wait until the official release for?

**Comment by yunwwang** [comment]
@dwebe003 The fix is on us-core-test-kit repo (https://github.com/inferno-framework/us-core-test-kit). 

onc-certification-g10-test-kit imports tests from us-core-test-kit

**Comment by dwebe003** [comment]
Ah ok. Sorry if this is a dumb question, but how do I make my onc-certification-g10-test-kit import from the **latest** us-core-test-kit?

**Comment by arscan** [comment]
If you have Ruby installed, you can add this to the `Gemfile` in onc-certification-g10-test-kit, on a line right after the `gemspec` line ([here](https://github.com/onc-healthit/onc-certification-g10-test-kit/blob/55e1b62257ac02a346fad06c8ea58d6ee6e17391/Gemfile#L6))

```
gem 'us_core_test_kit', git: 'git@github.com:inferno-framework/us-core-test-kit.git', branch: 'main'
```

Then, run `bundle install`, which tells Ruby's package manager to override the default version of the 'us_core_test_kit' gem (library) to pull with the latest from the main branch.  That will also update the Gemfile.lock to indicate the change to the source of the us_core_test_kit gem.

Alternatively, you could just [clone the us_core_test_kit](https://github.com/inferno-framework/us-core-test-kit) directly, and run it in the same way that you run the g10 tests (`./setup.sh` `run.sh`).  The v3.1.1 tests are basically imported into the g10 test kit directly as the 'Single Patient API' tests. Note that you may get false failures and warnings from differences in the configured validator when running in that mode though.  Those can be ignored.

We will have the new version out next week though, in case you have trouble trying out the above.

**Comment by dwebe003** [comment]
@arscan Perfect instructions! That worked great, and my MedicationRequest is in the green now. Thank you for your help!

**Comment by arscan** [comment]
Thank you for reporting the issue and taking the time to verify the fix!  It is *greatly* appreciated.
