### ISSUE TITLE
Unable to run in local machine. No errors but not connecting to localhost:4567

### ISSUE THREAD

**Issue by ashu-bdvt** [onc-healthit/onc-certification-g10-test-kit#102]
Trying to run this new version of test kit locally however unable to hit the localhost:4567 . Followed the steps per https://github.com/onc-healthit/onc-certification-g10-test-kit#local-installation-instruction

No issues when I run setup.sh and run.sh.

I am on Macboook Pro (macOs Monterey 12.3.1 (21E258))
Terminal Logs: No errors
<img width="1418" alt="Screenshot 2022-04-20 at 10 00 50 AM" src="https://user-images.githubusercontent.com/6142355/164150796-f7745f13-5d5a-476c-9239-45313fbde28a.png">

Browser screenshot:
<img width="1148" alt="Screenshot 2022-04-20 at 10 01 31 AM" src="https://user-images.githubusercontent.com/6142355/164150875-502fba0d-1a82-4203-8a7f-c34d8b5b9f9e.png">

**Comment by ashu-bdvt** [comment]
Strange. If we run without port 4567 it works in localhost!!!
<img width="1029" alt="Screenshot 2022-04-20 at 1 53 07 PM" src="https://user-images.githubusercontent.com/6142355/164184381-d14a4888-4182-49eb-9828-ef0d62992eb0.png">

**Comment by ashu-bdvt** [comment]
Resolved

**Comment by Jammjammjamm** [comment]
Yes, it's running behind nginx which forwarding traffic from port 80.
