### ISSUE TITLE
Inferno Test Suite - EHR Practitioner App

### ISSUE THREAD

**Issue by naveen101112** [onc-healthit/onc-certification-g10-test-kit#109]
Hi Team,

As I don't know the process of running the EHR Practitioner App, I am stuck at the test of that group . Can any one please help me by providing information on how  to run the tests in EHR Practitioner App?
![image](https://user-images.githubusercontent.com/78737412/165542023-14fbad83-c042-4eba-8461-22528a8e3271.png)

**Comment by radamson** [comment]
Hi @naveen101112. It looks like you are using the Inferno Reference Server Preset. The EHR Launch test requires you to initiate the launch from the EHR (in this case https://inferno.healthit.gov/reference-server/)

If you go to https://inferno.healthit.gov/reference-server/ you'll see a link to the app launch page where you can paste in the launch URL (`https://inferno.healthit.gov/suites/custom/smart/launch`).

See the short gif below:
![EHR](https://user-images.githubusercontent.com/41651655/165543734-03c1d017-64fb-42bf-be7a-1c34a8c37426.gif)

**Comment by naveen101112** [comment]
Thank you for your instant response @radamson. Will try with the reference you provided.

**Comment by naveen101112** [comment]
Hi @radamson,

After trying with your reference the test is running fine now, but only one test case is getting failed i.e. 

![image](https://user-images.githubusercontent.com/78737412/165594279-993f4782-745f-4b58-8eab-5bed72f62b09.png)

Tried modifying the App Launch URL like, https://inferno.healthit.gov/inferno/oauth2/static/launch?launch=123&iss=**custome_issuer_url** even though getting same error specified in screenshot. Can you please suggest me what to be done to overcome this

**Comment by radamson** [comment]
You're original screen shot is from Inferno ONC Certification (g)(10) Standardized API. The screenshot you just posted is from (Legacy) Inferno Program Edition.

Are you using a version of Inferno hosted on https://inferno.healthit.gov/? If so which one?

![Screen Shot 2022-04-27 at 2 33 03 PM](https://user-images.githubusercontent.com/41651655/165595630-3d73f094-410b-499e-a8c8-19a07dfe7ded.png)

**Comment by naveen101112** [comment]
I am getting following error while trying with (g)(10) version. With redirecting to inferno screen.

![image](https://user-images.githubusercontent.com/78737412/165599696-8e39bf8f-ce07-430f-8429-3e1d55771e93.png)

So I tried with (Legacy) version. Here it is redirecting to inferno screen but failing with a test case which I mentioned above.

**Comment by naveen101112** [comment]
1. We are running tests on the https://inferno.healthit.gov. I am providing our server URL and credentials. 
**URL**: **https://bill.medgenehr.com:7043/fhir**
**ID**: **smart_launch** **PWD**: **launch**
2. 
![image](https://user-images.githubusercontent.com/78737412/165775034-4ec8a1bf-434b-4947-9279-b1f4feabd599.png)

**Comment by radamson** [comment]
Do you have an EHR launch page? Note that in this test you are required to "launch" the Inferno application from within your EHR Instance. These test are unique relative to other tests where just giving inputs and pressing the run button on the test isn't enough - once you've started the tests Inferno will be waiting for a redirect request which includes the `iss` and `launch` URL parameters

If you watch the gif I posted above you'll notice that I took these steps:
1. Started the Inferno EHR launch test
2. Copied the Inferno redirect URL from the inferno modal window (`https://inferno.healthit.gov/suites/custom/smart/launch`)
3. In another browser window/tab, go to the EHR server and launch the application with that URL
4. The browser should then return you back to Inferno where test execution will proceed

You can read more about this part of the spec and the request Inferno is expecting here:
[SMART App Launch EHR launch sequence](http://hl7.org/fhir/smart-app-launch/2021May/#ehr-launch-sequence)

**Comment by naveen101112** [comment]
Hi @radamson, Thank you for your support, for now that test is being pass after trying to launch inferno standalone app with our end-point as issuer.

**Comment by Justin-Ramm** [comment]
We also encountered this issue. A bit of troubleshooting revealed that Inferno is strict with regard to how it handles trailing slashes in the FHIR Endpoint. If you have a trailing slash in the FHIR Endpoint you specify in the configuration you use before beginning the EHR segment of the testing, but your FHIR server returns an `iss` without a trailing slash, you will hit the error described above. It can be resolved by remove the trailing slash from your FHIR Endpoint when you configure this test before running it (or perhaps adding a slash - whatever is needed to match your server's `iss` behavior)

All of the examples in the HL7 spec do not have a trailing slash.

Unclear whether this should be considered an issue or not, but I thought this comment might help others.
