### ISSUE TITLE
Clinical Note attachment reference mismatch bug

### ISSUE THREAD

**Issue by nathanloyer** [onc-healthit/onc-certification-g10-test-kit#110]
We just found another error that we think is a bug in inferno source code. This is in the Clinical Notes Guidance test section, "DiatnosticReport and DocumentReference reference the same attachment".

<img width="1403" alt="image" src="https://user-images.githubusercontent.com/10855885/165636058-a7a49394-aa68-42cb-b0b2-72cc36335031.png">

As you can see there is a null pointer error coming from the Ruby code. Looks like this is where the issue is

https://github.com/inferno-framework/us-core-test-kit/blob/main/lib/us_core_test_kit/custom_groups/clinical_note_attachment_test.rb#L37

I'm not a Ruby expert, but to me this looks like 

```Ruby
            "#{url} in DiagnosticReport/#{report_attachments[patient_id][url]} for Patient #{patient_id}"
```

needs to be changed to this

```Ruby
            "#{url} in DiagnosticReport/#{report_attachments[url]} for Patient #{patient_id}"
```

As report_attachments looks like it should be hashmap with url's for keys and not patient_id's

It looks like this error is presented because our test data has a mismatch that inferno was trying to give us a proper error message for, but this is still an inferno bug.

**Comment by arscan** [comment]
Thank you @nathanloyer!  This is absolutely a bug in Inferno.  End users should never see the "Purple Errors" (as we call them), regardless of server behavior.  They usually happen when the server is misbehaving and would fail the test anyhow, but at the very least it is an opportunity for us to improve failure messages.

Q for you as a user: is the above statement obvious, or should we put some explanatory text in the error message, and perhaps hide the technical details somewhere (e.g. as a Message)?

**Comment by yunwwang** [comment]
@nathanloyer Thanks for the PR. I pulled your changes into my branch and added unit test.

**Comment by arscan** [comment]
Thanks for the feedback on error messages, this is helpful.

> Usually I have to dig through code to figure out where the data is coming from and that's not something that should have to happen.

Absolutely!

**Comment by nathanloyer** [comment]
Thanks for the quick turnaround. I just opened a related issue in #113 that I was hoping yall could review as well when you get a chance. I'd like to get a resolution for that issue as well as this one into the next release that I assume should be happening in a week or so.
