### ISSUE TITLE
Inferno 2.1 does not have the same verbiage as in Inferno 1.9 in Group Compartment Export Validation Tests (FI-1553)

### ISSUE THREAD

**Issue by IgLysk00** [onc-healthit/onc-certification-g10-test-kit#111]
In Inferno version 1.9, Group Compartment Export Validation Tests, there is a statement that explicitly states that resources are optional:
 
![image](https://user-images.githubusercontent.com/73243391/165806266-036efad7-e230-4afb-abe0-ba6de87dccbe.png)

In Inferno version 2.0 this statement is omitted:
 
![image](https://user-images.githubusercontent.com/73243391/165806327-51a2d499-477e-4b84-a265-84f1a33b7310.png)

**Comment by arscan** [comment]
Thanks for letting us know about the discrepancy.  That wasn't intentional.  The behavior is the same (an "omit" is equivalent to a pass -- and in both v1.9 and 2.1 the result is an 'omit'), but it is nice to have that extra statement in the result message to make that clear.  We'll update that.
