### ISSUE TITLE
Provenance end-point and revInclude:Provenance:targets

### ISSUE THREAD

**Issue by naveen101112** [onc-healthit/onc-certification-g10-test-kit#117]
Hi Team,

Can you please help me in knowing what Provenance is, and what should be included in response when found **revInclude:Provenance:targets** in request?

We observed inferno example, that there is an endpoint for Provenance where we send a Provenance id it is responding with some data. Should we maintain that data in a database linked with that Provenance id?

**Comment by yunwwang** [comment]
Here is the Provenance in US Core v3.1.1
http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-provenance.html

Here is the Provenance in FHIR core spec
http://hl7.org/fhir/provenance.html
