### ISSUE TITLE
SSL test cases failing in Inferno V 2.1 

### ISSUE THREAD

**Issue by praneethyaji** [onc-healthit/onc-certification-g10-test-kit#119]
Hi Team,

We are testing standalone launch sequence of SMART application through custom developed IDP, authorize and token endpoints are secured by TLS 1.2 version and the test cases related to TLS check were passing   in old inferno i.e. 1.9 but post upgrading inferno to 2+ versions the TLS testcases are failing saying server did not support an allowed TLS versions. PFB screenshot of testcase result in 2.1 version and 1.9 V respectively.
In version 2.1
![image](https://user-images.githubusercontent.com/41485451/167390808-8a15e986-31b3-42b1-b720-61c3d515c124.png)
![image](https://user-images.githubusercontent.com/41485451/167390930-d4ec771e-293c-476a-b373-90073f906fd9.png)

where as in version 1.9 testcases pass
![image](https://user-images.githubusercontent.com/41485451/167391077-3a5979ce-6217-4257-95f5-aacad1b9d366.png)

Please help . Thanks in advance. Any suggestions would be very helpful.

**Comment by praneethyaji** [comment]
Hi Rob,

Thanks for the quick reply.

I am using public inferno site from https://inferno.healthit.gov/  so they are not installed anywhere in local or on server.
My concern is TLS testcases are passing in inferno  V 2.0+ in below option
![image](https://user-images.githubusercontent.com/41485451/167571341-6582ad56-05d7-4ee4-b14a-05233a606c2c.png)
![Inferno 2+ version TLS tests](https://user-images.githubusercontent.com/41485451/167571479-941ecd7b-a9f5-403a-8355-af7f4780a45f.png)

But when I run ONC Certfication g10 test cases
![image](https://user-images.githubusercontent.com/41485451/167571683-2ce2144b-c12a-44f5-881c-53c3ee41581a.png)


TLS tests are failing.  I am not much concentrating on inferno V1.9 as it would be removed from healthit.gov by May 2022.

**Comment by praneethyaji** [comment]
Just to add on to same context, we are using same authorization endpoints for TLS suites as well as ONC certification Standard test suite. The TLS specific test suite passes with message  "Server allowed TLS 1.2 connection where as ONC certification Standard test suite fails with message "Server did not support any allowed TLS versions".

Please suggest your thoughts on this, it would be very helpful.

**Comment by arscan** [comment]
Thanks @praneethyaji, this is very helpful to figure out what is going on here.  Could you paste in a screenshot of the 'Messages' tab from the 'TLS Test Kit' test, because it will provide messages of which versions work and which do not.  While the tests within g10 use the same tests as the ones you can access through the 'TLS Test Kit', they are perhaps configured slightly differently about what is allowed.

**Comment by praneethyaji** [comment]
I'm sorry for posting wrong screenshot. PFB screenshot of messages tab of 'TLS Tests'  suite which allowed TLS v1.2

![image](https://user-images.githubusercontent.com/41485451/167898729-6c01f642-d642-4356-9802-be15964df1f8.png)

**Comment by praneethyaji** [comment]
Thanks @arscan  for your suggestions. The issue is resolved now after both token receiver and token provider entity are TLS secured.
