### ISSUE TITLE
Single Patient Test - Encounter seeing unrecognized property

### ISSUE THREAD

**Issue by healthland** [onc-healthit/onc-certification-g10-test-kit#126]
![2022-05-12 10_52_21-Inferno](https://user-images.githubusercontent.com/66788141/168117652-b6685f91-ce2d-4925-9976-64f315f0f2fc.png)
When using the single patient test for encounter we are seeing errors on unrecognized property and not expecting to see these. 
Encounter.participant[0]: Unrecognised property '@individual'
@period
@reasonCode

This is the JSON showing these properties: 
   "participant": [
          {
            "type": [
              {
                "coding": [
                  {
                    "system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
                    "code": "ATND",
                    "display": "attender"
                  }
                ],
                "text": "attender"
              }
            ],
            "individual": {
              "reference": "Practitioner/571",
              "display": "Doctor, Kathy"
            },
            "period": {
              "start": "2021-06-04T10:00:00.000-05:00"
            }
          },
          {
            "individual": {
              "reference": "PractitionerRole/4"
            }
          }
        ],

   "period": {
          "start": "2021-06-04T10:00:00.000-05:00"
        },

 "reasonCode": [
          {
            "coding": [
              {
                "system": "http://hl7.org/fhir/sid/icd-10-cm",
                "code": "E23.2",
                "display": "Diabetes insipidus"
              }
            ],
            "text": "Diabetes insipidus"
          }
        ],
[EncounterJSON.docx](https://github.com/onc-healthit/onc-certification-g10-test-kit/files/8680853/EncounterJSON.docx)

**Comment by yunwwang** [comment]
I got the same error on reference server. It seems like the validator service is messed up. I will my team know. At the same time, you can download and run us-core-test-kit docker image locally which isolated you from random changes in the validator service.

**Comment by healthland** [comment]
Thank you!

**Comment by healthland** [comment]
It looks like they have it working now.  Thank you!
