### ISSUE TITLE
Single Patient API Test - CareTeam Search

### ISSUE THREAD

**Issue by yashpalk** [onc-healthit/onc-certification-g10-test-kit#127]
We're testing with the ONC Certification (g)(10) Standardized API Test Suite. For test the CareTeam Test (4.5.01) in Single Patient API, the test is failing because our server does not support comma-separated strings for the `status` query parameter. 

Is this the expected behavior? As per the [US Core CareTeam search spec](https://hl7.org/fhir/us/core/StructureDefinition-us-core-careteam.html#mandatory-search-parameters), support for this is optional.
> **SHALL** support searching using the combination of the [patient](https://hl7.org/fhir/us/core/SearchParameter-us-core-careteam-patient.html) and [status](https://hl7.org/fhir/us/core/SearchParameter-us-core-careteam-status.html) search parameters:
> - including optional support for composite OR search on status (e.g.status={system|}[code],{system|}[code],...) 

<img width="1748" alt="Screen Shot 2022-05-12 at 12 20 21 PM" src="https://user-images.githubusercontent.com/24425291/168129351-8dab1b04-8c03-4822-8fce-cf777f8f953b.png">

**Comment by yunwwang** [comment]
The composite OR support is required in US Core v3.1.1
http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-careteam.html

![image](https://user-images.githubusercontent.com/8761175/168147946-d0aea0f0-be42-4843-92f6-788b35cdaf38.png)

**Comment by yashpalk** [comment]
Ah okay, thank for you for clarifying!
