### ISSUE TITLE
sub must be a non-blank string not exceeding 255 characters in length

### ISSUE THREAD

**Issue by dileeprt** [onc-healthit/onc-certification-g10-test-kit#133]
Hello Inferno team,
Just wanted to check if it is a mandatory requirement that the EHR token sub claim should not exceed 255 characters.
This is with reference to the tests 3.3.06 under "EHR Practitioner App"

![image](https://user-images.githubusercontent.com/70513754/169224886-87bed8bf-3876-4a63-9897-52e3c5445f12.png)

**Comment by yunwwang** [comment]
https://openid.net/specs/openid-connect-core-1_0.html#IDToken

sub
REQUIRED. Subject Identifier. A locally unique and never reassigned identifier within the Issuer for the End-User, which is intended to be consumed by the Client, e.g., 24400320 or AItOawmwtWwcT0k51BayewNvutrJUqsvl6qs7A4. It MUST NOT exceed 255 ASCII characters in length. The sub value is a case sensitive string.

**Comment by yunwwang** [comment]
Hello @dileeprt 

I will close this issue as no activities over the last few months. If you experience similar issue in the future, you can reopen this issue or create a new one. 

Thank you
