### ISSUE TITLE
(g10) 6.1  Public Client Standalone Launch can not set client secret 

### ISSUE THREAD

**Issue by liquid36** [onc-healthit/onc-certification-g10-test-kit#135]
Hi! are there any reason why client secret is locked? I'm in (g10) 6.1  Public Client Standalone Launch with OpenID Connect test. 

![image](https://user-images.githubusercontent.com/3813270/169561986-40f92ce4-739f-4458-b6e8-66b386837494.png)

The Auth Server return an error if there is not cliente secret

```
{
  "error": "unauthorized_client",
  "error_description": "Client secret not provided in request"
}
```

am i missing something?

**Comment by yunwwang** [comment]
@liquid36 The test 6.1 is designed to test server's support for "public" client. According to SMART App Launch IG (https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Inferno.20Deployment.20w.2F.20Postgres/near/282979839), public client does NOT have a client_secret.
