### ISSUE TITLE
Encounter Resource

### ISSUE THREAD

**Issue by Pareshcool** [onc-healthit/onc-certification-g10-test-kit#137]
we are Ambulatory, so we dont have Encounter.hospitalization
Encounter.hospitalization.dischargeDisposition
data elements in our EHR. But as per Uscore and Inferno these are SHALL support elements. As we dont have in our EHR, shall we avoid this data elements or we need to mandatory have these elements to pass the test.

**Comment by yunwwang** [comment]
Hello @Pareshcool  

I will close this issue as no activities over the last few months. If you experience similar issue in the future, you can reopen this issue or create a new one. 

Thank you
