### ISSUE TITLE
Bulk Data Export - content type

### ISSUE THREAD

**Issue by naveen101112** [onc-healthit/onc-certification-g10-test-kit#139]
Team, 

We have written logic in C# to respond the ndjson content in response for Bulk Data export apis. But we are facing issue that is 406 Not Acceptable. Can any please help us on how to respond with content-type: application/fhir+ndjson

**Comment by yunwwang** [comment]
Hello @naveen101112 

Here is the section of File Export in Bulk Data IG v1.0.1 http://hl7.org/fhir/uv/bulkdata/STU1.0.1/export/index.html#file-request.

**Comment by naveen101112** [comment]
When coding as Response.Header.Add("Content-Type","application/fhir+ndjson")
Getting error as method not allowed

**Comment by arscan** [comment]
This sounds like an issue specific to the environment you are using to build your application, which we likely do not have sufficient expertise in to help you with.  Generally, for web/api frameworks, you should be able to specify a Content-Type for a response (assuming you are are the 'server' in this case).  Exactly how you can accomplish that depends... not just on the language (C#), but also libraries/frameworks you are using, and perhaps the server/cloud environment it is running in.  Is there documentation on how to modify this header specific to the library/framework you are using?

**Comment by arscan** [comment]
Also note, our client is sending the following header: 'Accept: application/fhir+ndjson'.  So a potential problem could be that your system needs to be updated to allow clients that expect that type of response?  Without knowing specifics about your setup I'm not sure though.  I hope this gives you some ideas to figure out the issue.

**Comment by yunwwang** [comment]
Hello @naveen101112  

I will close this issue as no activities over the last few months. If you experience similar issue in the future, you can reopen this issue or create a new one. 

Thank you
