### ISSUE TITLE
localhost

### ISSUE THREAD

**Issue by gjrom** [onc-healthit/onc-certification-g10-test-kit#140]
Hi,

We are attempting to test and use our newly deployed v2.2.1 local install of Inferno and believe we are running into a configuration issue.  For example, when selecting the Inferno Reference Server and attempting to run 1 Standalone Patient App we see a config that references the localhost in the URI, see attached...

![local](https://user-images.githubusercontent.com/65570556/171464111-cda6db95-610e-44b0-94df-491fcee166bb.JPG)

Is this expected behavior or is there a configuration step we need to follow?

Thanks

**Comment by Jammjammjamm** [comment]
In `.env`, update the value of `INFERNO_HOST` to your scheme + hostname.

**Comment by gjrom** [comment]
Thank you, this fixed the issue.
