### ISSUE TITLE
Support for IE 11 in EHR Launch Test (FI-1594)

### ISSUE THREAD

**Issue by yunwwang** [onc-healthit/onc-certification-g10-test-kit#143]
This issue is reported by @dougpratt at https://github.com/onc-healthit/inferno-program/issues/455. The original ticket includes several screenshot which could not be copied directly.

===========================

Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

Subject of the issue
We are unable to launch the EHR Practitioner App using INFERNO 2.x due to an IE 11 incompatibility that had been fixed in INFERNO 1.9 (see https://github.com/onc-healthit/inferno-program/issues/235 and (https://github.com/onc-healthit/inferno-program/pull/335). Please add this fix to INFERNO 2.x.

Your environment

Edition of inferno (Community or Program): Program
Version of inferno: 2.2.1
Which browser and version(s) is the bug present on?: IE 11, IE Mode on Edge Browser
Steps to reproduce
Tell us how to reproduce this issue.
Open Inferno 2.2.1 by navigating to [https://inferno.healthit.gov/onc-certification-g10-test-kit/] in IE 11. All we get is a blank screen. The behavior is same when Inferno 2.2.1 is opened in “IE Mode” on Edge browser.

Include:

The selected test suite EHR Practitioner App
The URL of the FHIR server being tested : https://fhir-ehr-sc.sandboxcerner.com/r4/3f2aca24-87f3-4eac-a6d7-1f75247e6b43
The Test ID, if it's a problem with a specific test. N/A
Any required configuration options (client ID, client secret, etc.) None Required
Anything else needed to make the issue occur. Nothing really. See steps to reproduce.
Expected behavior
Inferno 2.2.1 should open in IE 11 and “IE Mode” on Edge browsers. The full functionality of Inferno should be functional, including EHR launch..

Actual behavior
Tell us what happens instead. Include screenshots if possible. All we get is a blank page. Happens in all versions of IE 11 and IE mode on Edge browser. Screenshots are attached.

**Comment by dougpratt** [comment]
Thank you for copying this over, @yunwwang . I've copied the screen shots here:
![InfernoV1 9_IE-11_Win10_WorkingFine](https://user-images.githubusercontent.com/27502666/172694520-2e830428-d992-45f9-96b1-c02444e48b76.png)
![InfernoV2_IE-11_Win10_BlankPage](https://user-images.githubusercontent.com/27502666/172694533-13356ca7-a92c-4470-b5bd-d14c99694398.png)
![InfernoV2_IE-11_WinServer2012-BlankPage](https://user-images.githubusercontent.com/27502666/172694541-1a97f714-d656-4962-867f-ea18c8536265.png)
![InfernoV2_IE-11_WinServer2019-BlankPage](https://user-images.githubusercontent.com/27502666/172694557-470ef263-fb57-481e-a403-e49e2b8189e2.png)
![InfernoV2_IE-Mode-Edge_Win10-BlankPage](https://user-images.githubusercontent.com/27502666/172694567-78e6b861-160c-47dc-8ce6-6fdcdd86298f.png)

**Comment by dougpratt** [comment]
Hi @yunwwang, any update on this? 
Thanks, Doug

**Comment by dougpratt** [comment]
Thank you!

**Comment by IgLysk00** [comment]
At the latest Inferno Tech Talk meeting it was mentioned that a document might be published explaining that it is acceptable to see a blank screen during EHR Launch. Please let us know when such document will be published.

**Comment by dougpratt** [comment]
Hi, looking for a response to @IgLysk00 's comment from 17 days ago. As the fix for this may come in later than our certification date, we'd appreciate a quick response. Thank you.

**Comment by arscan** [comment]
Hi @dougpratt -- See https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki/Completing-EHR-Practitioner-App-test-in-Internet-Explorer/.  Our upcoming release next week prominently links to this within the test itself (see below).  Is this sufficient from your perspective?

![Screen Shot 2022-08-05 at 1 38 47 PM](https://user-images.githubusercontent.com/412901/183131439-e09cc18c-ab6a-4f40-a237-5afaf54895d5.png)

**Comment by dougpratt** [comment]
Yes, that is great! Thank you.
