### ISSUE TITLE
Inferno test 1.1.04 OAuth 2.0 Endpoints in the conformance statement match those from the well-known configuration failed.

### ISSUE THREAD

**Issue by IgLysk00** [onc-healthit/onc-certification-g10-test-kit#145]
Here is the error message received during the test execution:
![image](https://user-images.githubusercontent.com/73243391/175126102-e7dcc09a-dabf-466d-af90-899c80c05ae0.png)

SMART spec conformance recommends advertising the introspect URL

[http://hl7.org/fhir/smart-app-launch/conformance.html#metadata](https://nam10.safelinks.protection.outlook.com/?url=http%3A%2F%2Fhl7.org%2Ffhir%2Fsmart-app-launch%2Fconformance.html%23metadata&data=05%7C01%7CIgor.Lysko%40Cerner.com%7C685b5e4ea3d94dd3ff7308da5441bb50%7Cfbc493a80d244454a815f4ca58e8c09d%7C0%7C0%7C637914938539826360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=h21LVesAZM9HUgmozPjdQiO7bAp6GfucldFtucrFniM%3D&reserved=0)

[http://hl7.org/fhir/smart-app-launch/conformance.html#sample-response](https://nam10.safelinks.protection.outlook.com/?url=http%3A%2F%2Fhl7.org%2Ffhir%2Fsmart-app-launch%2Fconformance.html%23sample-response&data=05%7C01%7CIgor.Lysko%40Cerner.com%7C685b5e4ea3d94dd3ff7308da5441bb50%7Cfbc493a80d244454a815f4ca58e8c09d%7C0%7C0%7C637914938539826360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TejuxDaMhou3iQCPWLTJEPwW656MRso2nzXHgb4PZuk%3D&reserved=0)

Inferno expects that it should not be in the Capability Statement and also it must match the .well-known/smart-configuration response, which are contradictory expectations

[https://www.hl7.org/fhir/R4/extension-oauth-uris.html](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.hl7.org%2Ffhir%2FR4%2Fextension-oauth-uris.html&data=05%7C01%7CIgor.Lysko%40Cerner.com%7C685b5e4ea3d94dd3ff7308da5441bb50%7Cfbc493a80d244454a815f4ca58e8c09d%7C0%7C0%7C637914938539826360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9RGXN58JcXI3afK688tFTK1HwSM6ILsSkorChYh9qHg%3D&reserved=0)

**Comment by Jammjammjamm** [comment]
Why do you say that Inferno expects it not to be in the Capability Statement? Inferno expects the value in the Capability Statement to match the value from the well-known endpoint, which is a requirement in the SMART spec.
