### ISSUE TITLE
4.0.0 Patient 2.10 Failure for Birthsex, Ethnicity, Race

### ISSUE THREAD

**Issue by jj027509** [onc-healthit/onc-certification-g10-test-kit#146]
Test 2.10 Patient Resources Returned During Previous Tests Conform to the US Core Patient Profile
The errors returned are as follows (from the Inferno Validator): 

- Bundle.entry[0].resource.ofType(Patient).extension[0].value.ofType(code): The value provided ('M') is not in the value set 'Birth Sex' (http://hl7.org/fhir/us/core/ValueSet/birthsex), and a code is required from this value set) (error message = Error from server: Unable to find value set http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1021.103) on line 28. [Jump to error.](https://inferno.healthit.gov/validator/results#error-28)
- Bundle.entry[0].resource.ofType(Patient).extension[1].extension[0].value.ofType(Coding): The Coding provided (urn:oid:2.16.840.1.113883.6.238#2106-3) is not in the value set http://hl7.org/fhir/us/core/ValueSet/omb-race-category, and a code is required from this value set. (error message = Not in value set http://hl7.org/fhir/us/core/ValueSet/omb-race-category) on line 35. [Jump to error.](https://inferno.healthit.gov/validator/results#error-35)
- Bundle.entry[0].resource.ofType(Patient).extension[2].extension[0].value.ofType(Coding): The Coding provided (urn:oid:2.16.840.1.113883.6.238#2186-5) is not in the value set http://hl7.org/fhir/us/core/ValueSet/omb-ethnicity-category, and a code is required from this value set. (error message = Not in value set http://hl7.org/fhir/us/core/ValueSet/omb-ethnicity-category) on line 53. [Jump to error.](https://inferno.healthit.gov/validator/results#error-53)

The Items which it says are not in the value set can all be found in the value set, so I am unclear with what is wrong here. 
I have attached the resource that we put in the inferno validator to generate the above failures.

[Patient Birthsex_Race_Ethnicity Failures.txt](https://github.com/onc-healthit/onc-certification-g10-test-kit/files/8993585/Patient.Birthsex_Race_Ethnicity.Failures.txt)

**Comment by yunwwang** [comment]
@jj027509 

This is the same issue as this one recently raised at Validator repo https://github.com/inferno-framework/fhir-validator-app/issues/91. 

In a summary, US Core 3.1.1/4.0.0 Test Kits (and Inferno validator) replies on tx.fhir.org for terminology validation. There is a known issue on that server to correctly validate codes in valuesets from VSAC. Please see this zulip thread: https://chat.fhir.org/#narrow/stream/179166-implementers/topic/US.20Core.20Patient.20Example.20failing.20Inferno.20Validator.3F

We will let you posted when tx.fhir.org fixes that bug.

**Comment by jj027509** [comment]
@yunwwang Can you confirm if the following error that we are getting as part of careteam is coming from this same terminology validator issue?

CareTeam.participant[0].role[0]: Error from server: The filter "concept = 768734005" from the value set http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1099.27 was not understood in the context of [http://snomed.info/sct]

**Comment by yunwwang** [comment]
This message is a valueset expansion failure message. If you are using US Core Test Kit, then this message came from either tx.fhir.org or vsac.nlm.nih.gov depending on where the expansion happens.

I tested this query on tx.fhir.org: 

http://tx.fhir.org/r4/ValueSet/2.16.840.1.113762.1.4.1099.30/$validate-code?code=768734005&system=http://snomed.info/sct

which gives me the same error message as you mentioned.

**Comment by yunwwang** [comment]
Here is zulip discussion for the root cause:

https://chat.fhir.org/#narrow/stream/179202-terminology/topic/SNOMED.20.22.3D.22.20operation

**Comment by yunwwang** [comment]
@jj027509

The new (g)(10) test kit v3.0.0 was released this morning. It support US core v4.0.0 for Single patient test. Please let me know if you continue facing the same terminology issue with the new (g)(10) test kit.

**Comment by jj027509** [comment]
This is working now - feel free to close. Thanks!
