### ISSUE TITLE
4.0.0 Document Reference 10.10 Failure 

### ISSUE THREAD

**Issue by jj027509** [onc-healthit/onc-certification-g10-test-kit#147]
Getting error message which indicates that the returned code is not part of the value set, even though the listed non-conforming code is listed within the value set.

DocumentReference.type: None of the codings provided are in the value set 'US Core DocumentReference Type' (http://hl7.org/fhir/us/core/ValueSet/us-core-documentreference-type), and a coding from this value set is required) (codes = https://fhir.cerner.com/17316440-14fe-4957-b62f-9d85de2c88ca/codeSet/72#2820718, [http://loinc.org#11503-0](http://loinc.org/#11503-0)

[T1810 Document Reference 10.10 Failure.txt](https://github.com/onc-healthit/onc-certification-g10-test-kit/files/8994852/T1810.Document.Reference.10.10.Failure.txt)
)

**Comment by jj027509** [comment]
is this something that someone is able to look into?

**Comment by yunwwang** [comment]
We are still investigating the failure. The error comes from fhir-validator-wrapper and we could locate the root cause yet.

**Comment by yunwwang** [comment]
Hello @jj027509 

We believe this is an issue on the inferno validator service which is shared between inferno validator app and US Core test kit. We decide to spin off another validator service which is dedicated to US core test kits.

We hope this could resolve this mysterious loinc coding issue.

**Comment by jj027509** [comment]
@yunwwang Is this update already available or do you have an estimate of when we will be able to see this new validator service in the inferno.healthit.gov site?

**Comment by yunwwang** [comment]
The staging is deployed to https://inferno-dev.healthit.gov/
The final release to https://inferno.healthit.gov/ will be around today after business hours.

**Comment by yunwwang** [comment]
I noticed the second url has r2 version number. Since US Core is based on FHIR R4, the code should be checked with R4 terminology server.

http://tx.fhir.org/r4/CodeSystem/$validate-code?code=LP75011-4&system=http://loinc.org

returns false.

I also checked the code on LONIC. https://loinc.org/search/?t=1&s=LP75011-4 returns "no matching record found"

**Comment by jj027509** [comment]
If you change the dropdown to "part" on the loinc search you will get the result.
https://loinc.org/LP75011-4/

**Comment by jj027509** [comment]
We ran again on r4 validator and it failed - we will work on getting that mapping updated. Thanks!

**Comment by yunwwang** [comment]
Maybe a tx server issue. You see the error message from the tx server is exactly the same as inferno returns. 

One observation is the [LP75011-4/](https://loinc.org/LP75011-4/) is "Laboratory' which is the same concept as "LAB". Per FHIR spec, they represent the same concept and should be put under the same `codeableConcept` item instead of two separate items.

**Comment by jj027509** [comment]
@yunwwang when I tested this morning, 10.10 was failing again. Is it possible that the previous fix was lost in the most recent release?
https://inferno.healthit.gov/suites/test_sessions/39784a12-d02e-42f2-9eea-881014c139bd#us_core_v400-us_core_v400_document_reference

**Comment by yunwwang** [comment]
Do you mean the first error? That is strange.
We have a dev version of g10 certification test which having its own terminology service. Can you check if that passes your server? https://inferno-dev.healthit.gov/

**Comment by jj027509** [comment]
This is still failing. 
We believe this may be what is causing the problem on our side. It appears the document that is failing wasn't being returned before, but when we investigated what could be causing it to fail, but we couldn't find any causes. 
We are wondering if the validator is looking at STU5 instead of STU4, because STU5 no longer appears to be extensible and that is the only thing we have found that could be causing this.

**Comment by yunwwang** [comment]
Sorry, I didn't say it clearly. Can you try the g10 test suite with US Core 4.0 selection?

https://inferno-dev.healthit.gov/suites/g10_certification

![image](https://user-images.githubusercontent.com/8761175/185963036-c7fd3af3-955f-4820-9d0e-a171bf62c5fc.png)

**Comment by yunwwang** [comment]
Another thing I just learned is that tx.fhir.org apparently only have valuesets for the latest version. I asked Grahame on zulip (https://chat.fhir.org/#narrow/stream/179190-united-states/topic/validate-code.20for.20us-core.20v4.2E0.20valueset). If that is true, all the validations in US Core 3.1.1/4.0.0 test kits uses valuesets defined in US Core v5.0.1.

**Comment by jj027509** [comment]
I am unable to run that way as the dev environment is not set up with our smart app validator and I am unable to manually add a token in the single patient api (it appears manually adding a token there is locked). 

I am concerned about the valuesets being from v5.0.1. We are certifying on US Core v4.0, will the valuesets being for v5.0.1 cause incorrect failures?

**Comment by yunwwang** [comment]
The ONC (g)(10) Standard API test kit has its own terminology services which holds valuesets for specific versions.

**Comment by jj027509** [comment]
We are beta partners for the US Core v4.0.0 Test Suite for Single Patient APIs. Which valueset version would that use?

**Comment by yunwwang** [comment]
@jj027509 

The new (g)(10) test kit v3.0.0 was released this morning. It support US core v4.0.0 for Single patient test. Please let me know if you continue facing the same terminology issue with the new (g)(10) test kit.

**Comment by jj027509** [comment]
This is working - thank you! Feel free to close
