### ISSUE TITLE
Implantable Device search not registering response, returns error (FI-1607)

### ISSUE THREAD

**Issue by jlgrater** [onc-healthit/onc-certification-g10-test-kit#149]
Using the web application, I have test 4.7.01 failing. The errors says "GET search returned 0 resources, and POST search returned 2 resources". However, when I click on the DETAILS button for the GET, it shows 2 resources in the response (the same two show in the details for the POST). I'm not sure why it is saying there are 0. 

I try the same GET request (from the url in the test) using POSTMAN and I get 2 results. I'm sure that the error given is the wrong error. But I don't know what to fix if it's not going to tell me the actual problem. 

![image](https://user-images.githubusercontent.com/79801587/176494782-41225b09-f41c-4d85-ab4c-6267e00214c5.png)

![image](https://user-images.githubusercontent.com/79801587/176494948-c759e84b-d1ea-4c54-bc89-b445c3cd6668.png)

**Comment by jlgrater** [comment]
> @jlgrater Thank you for report this issue. Could you send me the session id or url of your testing session? Thank you.

https://inferno.healthit.gov/suites/test_sessions/d9742273-b635-45de-a01e-44587203448f#g10_certification-g10_single_patient_api

**Comment by jlgrater** [comment]
@arscan Yes, we ran with Device Type Code = 156009

**Comment by jlgrater** [comment]
@arscan I see. Thanks for the explanation! I was confused why it was accepting the results from the POST. We should be filling out the type code. We will fix and try again.

**Comment by arscan** [comment]
Sounds good.  We have a ticket in our side to fix the POST logic here so that it properly filters by Device.type to match the GET logic, if the tester puts in that value.  I think in practice most systems just test with patients that only happen to have devices associated with them that are 'implantable' (and can therefore leave that field blank).  Thanks for surfacing this for us!
