### ISSUE TITLE
Inferno doesn't detect  TLS termination in containerized environments

### ISSUE THREAD

**Issue by awatson1978** [onc-healthit/onc-certification-g10-test-kit#154]
Hello,
The Galaxy hosting provider, which we are running the FAST National Directory on, runs on AWS with a docker container infrastructure.  Prior versions of Inferno and the SMART on FHIR testing gave it a green light.  But the new version of Inferno checks for TLS connections.  And it appears that Galaxy terminates TLS 1.0 and 1.1 at an inner container, not the public proxy, and is therefore causing an error.

Please see the following forum thread on the issue:
https://forums.meteor.com/t/security-disabling-tls-1-0-and-1-1/58278

Any chance we can get Inferno to either emit a warning instead of an error, or check TLS with proxy tunnels?

**Comment by awatson1978** [comment]
Ran an SSL Server Test, and it doesn't check containerized environment either.  Container terminates TLS 1.0 and 1.1, but the receiving docker environment accepts both.  Thus getting a B rating.  

![Screen Shot 2022-07-06 at 8 57 05 AM](https://user-images.githubusercontent.com/675910/177570674-5258181d-6075-4e04-9de0-4687e543b2c1.png)

It would be ideal if Inferno could give a qualitative response, such as B rating or a Warning, instead of a binary pass/fail.  

[SSL Server Test_ national-directory.meteorapp.com (Powered by Qualys SSL Labs).pdf](https://github.com/onc-healthit/onc-certification-g10-test-kit/files/9055536/SSL.Server.Test_.national-directory.meteorapp.com.Powered.by.Qualys.SSL.Labs.pdf)

**Comment by awatson1978** [comment]
Can we have an update on getting the error message changed to a warning message for TLS 1.0 and 1.1?  And/or adding detection for docker containerization environments?  We're running the national-directory through the Inferno tests, and it's still incorrectly detecting the docker environment and claiming TLS has not been terminated, when it has by the time it reaches the container.

**Comment by arscan** [comment]
We got the OK to allow this approach for denying content being sent over TLS < 1.2 connections for certification, despite it not being consistent with current best practices, and will be working on it this month.

**Comment by yunwwang** [comment]
The TLS issue is fixed as part of #161
