### ISSUE TITLE
Warning message is issued during execution of the "2.1.06 Token exchange response body contains required information encoded in JSON" test (FI-1650)

### ISSUE THREAD

**Issue by IgLysk00** [onc-healthit/onc-certification-g10-test-kit#155]
The requirement to the Standalone Patient App - Limited Access test is to limit access only to the following resources: Patient, Condition, Observation. At the same time a warning message is issued by Inferno that not all scopes are included (see the attached screenshot). Since the requirement is to provide a limited access, should this warning be suppressed? 
![image](https://user-images.githubusercontent.com/73243391/177577091-6db1779d-7867-4fc6-b9a2-6b51ebce47c3.png)

**Comment by arscan** [comment]
Hi @IgLysk00 -- thanks for reporting this.  I agree that this is confusing.  We included the language 'these may have been denied by user' for this case as a way to signal that if it was denied by the user and is expected then its ok, but aren't clear that this warning can be ignored int his case.  And really it just shouldn't show up.  We'll look at removing it.
