### ISSUE TITLE
4.0.0 - Seeing Unknown FHIRVersion code '4.3.0' Error on every resource (FI-1620)

### ISSUE THREAD

**Issue by jj027509** [onc-healthit/onc-certification-g10-test-kit#157]
We are getting the following error on every resource in current test runs in 4.0.0: 
Error loading /root/.fhir/packages/hl7.fhir.r4b.core#4.3.0/package/StructureDefinition-Appointment.json: Unknown FHIRVersion code '4.3.0'

Test URL: https://inferno.healthit.gov/suites/test_sessions/29bcb43a-05ac-4bc2-96c9-aa586885443e#us_core_v400-us_core_v400_capability_statement

**Comment by jj027509** [comment]
Issue appears to have been resolved. 
https://inferno.healthit.gov/suites/test_sessions/009c0745-83b8-4ae3-9cb8-6011ec61163f#us_core_v400-us_core_v400_patient

**Comment by arscan** [comment]
The US Core v4.0.0 relies on our 'Community Validator', which allows users to upload IGs for validation.  That can create side-effect some times we've seen, and we think that may have been the case here.  As we package US Core v4 + v5 tests into our SVAP release for (g)(10) certification, the validator will be locked own to prevent this. Sorry about the confusion!

**Comment by jj027509** [comment]
We are once again getting this issue
https://inferno.healthit.gov/suites/test_sessions/a475b7dd-b08d-478e-bcb4-834b5d2e7205#us_core_v400

**Comment by yunwwang** [comment]
We will update the validator to the latest fhir-core v5.6.52 which may address this issue.

**Comment by yunwwang** [comment]
This issue has been address in US Core Test Kit and ONC g10 Test Kit by using dedicated validator instances having locked FHIR core version v4.0.1. 

A separated ticket is created in fhir-validator-wrapper repo (shown above) to address the dependency on community validator.

Ticket closed
