### ISSUE TITLE
Blood Pressure Observation test failing when cuff size is included

### ISSUE THREAD

**Issue by jlgrater** [onc-healthit/onc-certification-g10-test-kit#167]
Our observation tests are failing because we have included the Blood Pressure Cuff Size as a component. This was passing before, but is now failing with the following error:

![image](https://user-images.githubusercontent.com/79801587/178987644-7a01e339-737a-4157-823c-ef905f22545a.png)

Here is an example of our json response that includes the cuff size:

![image](https://user-images.githubusercontent.com/79801587/178987836-6a5af5f1-69ce-4642-936b-d7041416416c.png)

The US Core spec lists the component value binding as "extensible" for all slices that are not systolic or diastolic:

![image](https://user-images.githubusercontent.com/79801587/178988611-05bb0d3c-5c26-4745-823d-f139a8639fb6.png)

**Comment by arscan** [comment]
Hi @jlgrater -- we've gotten a couple of reports about new incorrect terminology failures in this last release.  We noticed one of the dependencies on https://inferno.healthit.gov wasn't updated properly, which may have caused some of them, and we fixed that last night.

Are you running this on https://inferno.healthit.gov, and if so, did you run this test this morning or is it from yesterday?  If the run is from yesterday, could you re-run it now?  I'm not sure if this is the same thing but worth checking. Thanks for your patience as we work this out.

**Comment by jlgrater** [comment]
@arscan It's actually a run from yesterday. I will try again today. Thanks!

**Comment by jlgrater** [comment]
@arscan Confirmed the test is now passing.

**Comment by arscan** [comment]
Thanks!  A quick explanation for posterity:  we altered the format of these validator error messages slightly across a couple of libraries.  One of the libraries in our inferno.healthit.gov deployment didn't get updated, causing some error messages to slip through a filter used in another library.  This dependency issue only should have affected our deployment -- those downloading and running the g10 test kit locally shouldn't have had that problem.
