### ISSUE TITLE
Need additional information about Organization test

### ISSUE THREAD

**Issue by jlgrater** [onc-healthit/onc-certification-g10-test-kit#168]
Our Organization test is failing because the particular organization that is queried by the test does not have an NPI. 

We DO return Organizations that have an NPI, and references to those are being returned in previous tests (MedicationRequest pharmacy, for example). 

It is not apparent from the test why it is always using this particular Organization id in the query. Does it first retrieve all Organizations, then use the first one? 

![image](https://user-images.githubusercontent.com/79801587/178993810-4b69a0f3-36ff-4738-b2b6-8038f47e6fc6.png)

**Comment by yunwwang** [comment]
Hello @jlgrater 

Thank you for raising this issue. To further investigate, could you send the url of your test session to my email yunweiw@mitre.org?

**Comment by yunwwang** [comment]
@jlgrater 

Thank you for the session link. Similar to the Encounter resource (https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki/FAQ#q-how-does-inferno-test-us-core-encounter-resource), Inferno Organization test is only concerned with references to Organization resources that it knows MUST support the US Core Organization profile.

MedicationRequest.performer has a reference to `Reference(Organization)`. So Inferno does not count it into the Organization test.

Some examples of MustSupport element with reference to `Reference(US Core Organization)` are: `CareTeam.participant.member`, `DiagnosticReport.performer`, and `DocumentReference.author`
