### ISSUE TITLE
6.5.12 “Health IT developer demonstrates support for the Patient Demographics Previous Name USCDI v1 element  - Need clarification.

### ISSUE THREAD

**Issue by MothyTim** [onc-healthit/onc-certification-g10-test-kit#169]
Hi, we are trying to understand if Patient.name.period is a required element in the patient resource when the Patient has a previous name.  We read the text in the Inferno test case and there is an ambiguity we need to clarify as follows.

ONC certification criteria states that all USCDI v1 data classes and elements need to be supported, including Patient Demographics - Previous Name. However, US Core v3.1.1 does not tag the relevant element (Patient.name.period) as MUST SUPPORT. The Health IT developer must demonstrate support for **_this_** USCDI v1 element as described in the US Core Patient Profile implementation guidance.

Here are the 2 potential interpretations:
1) 
ONC certification criteria states that all USCDI v1 data classes and elements need to be supported, including Patient Demographics - Previous Name. However, US Core v3.1.1 does not tag the relevant element (Patient.name.period) as MUST SUPPORT. The Health IT developer must demonstrate support for the **_Patient.name.period_** USCDI v1 element as described in the US Core Patient Profile implementation guidance.
2)
ONC certification criteria states that all USCDI v1 data classes and elements need to be supported, including Patient Demographics - Previous Name. However, US Core v3.1.1 does not tag the relevant element (Patient.name.period) as MUST SUPPORT. The Health IT developer must demonstrate support for **_Patient.name_** USCDI v1 element as described in the US Core Patient Profile implementation guidance.
 
To confirm for current certification efforts it should be the   US Core Patient Profile implementation 3.1.1  that should be used for latest inferno?

**Comment by yunwwang** [comment]
ONC has a clarification on that:

Either the US Core IG Profile “StructureDefinition-us-core-patient” element “name.period” or “name.use” is required for testing and certification in the ONC Certification Program to meet the USCDI requirement to support the “Patient Demographics” data class: “Previous Name” data element.


https://www.healthit.gov/test-method/standardized-api-patient-and-population-services

**Comment by MothyTim** [comment]
Reviewing the above information and the specification concludes this issue for this point in time.
