### ISSUE TITLE
Getting error when run setup.sh

### ISSUE THREAD

**Issue by NeetaRamani** [onc-healthit/onc-certification-g10-test-kit#176]
I am running setup.sh via cygwin and getting following error -- no configuration file provided: not found. Could you please help?

**Comment by yunwwang** [comment]
Hello @NeetaRamani 

Did you run onc-certification-g10-test-kit in cygwin on Windows OS? Which version of Windows are you using?

**Comment by NeetaRamani** [comment]
Windows 10, I have installed docker desktop also as that was required for running .sh file.

**Comment by NeetaRamani** [comment]
Kindly ignore, I made a comment too fast. I was supposed to run this using ubuntu :)
Resolved and worked for me. Thanks for your time.
