### ISSUE TITLE
Redirects on well-known endpoint (FI-1659)

### ISSUE THREAD

**Issue by arscan** [onc-healthit/onc-certification-g10-test-kit#180]
A (g)(10) impacting issue was raised here: https://github.com/inferno-framework/inferno-core/issues/229

> We utilize redirects to manage multiple connections through a single gateway. For example:
https://www.medentfhirtest.com/fhir/R4/savcw237/.well-known/smart-configuration
redirects to
https://www.medentfhirtest.com/fhir/R4/.well-known/smart-configuration/index.php?medent_practice_id=savcw237
>
> This worked for the previous Inferno test suites, but is now returning a 302 on the very first test.
>
> Will redirects like this be supported or do we need to reconfigure our connections?
> 
> Thanks!
> Savannah Dearing

**Comment by SavannahDearing** [comment]
I know its only been a week, but just checking in on this so we can continue testing :)

**Comment by arscan** [comment]
Hi @SavannahDearing -- the http client used in the discovery tests will follow the redirects automatically in the next release, out next week.

I have a feeling this might trip up some clients out there, as it tripped us up when we switched to a new http client in v2.0 of our tests.  But following redirects automatically should be a configuration option for most http libraries out there, and language in the referenced specs are vague about this, so it makes sense for us to just allow servers to do this if they'd like.

**Comment by SavannahDearing** [comment]
Thanks for following up, we also found the specs were a bit vague on it.  In general, with other interfacing we've been able to use redirects as long as its not a new domain name.

**Comment by yunwwang** [comment]
Pull Request: https://github.com/inferno-framework/inferno-core/pull/231
