### ISSUE TITLE
launch context in token response

### ISSUE THREAD

**Issue by RER** [onc-healthit/onc-certification-g10-test-kit#181]
Hi,
I get the feeling this question has been answered but could not locate it.
Trying to get passed the g.10 tests and they say they want the launch context in the token response. 
We first tried an external auth service but they refused to change their token response to include "patient" or "fhirUser" in the token response json (as opposed to inside of the JWT)
seems like we cant get passed the smart launch tests without it.
what do most  EHRs do?
which oauth oidc service supports this? or are we expected to make our own?

**Comment by yunwwang** [comment]
There is a SMART stream on chat.fhir.org (https://chat.fhir.org/#narrow/stream/179170-smart). You may get better answer from broader implementer community.
