### ISSUE TITLE
Encounters with data absent reasons failing validation

### ISSUE THREAD

**Issue by nathanloyer** [onc-healthit/onc-certification-g10-test-kit#182]
After updating to the latest releases I have found that our Encounter resources are now failing test 4.27.03 "All must support elements are provided in the Encounter resources returned". I think this bug was introduced in this change in the us-core-test-kit

https://github.com/inferno-framework/us-core-test-kit/commit/54133f0148782bb5a9b46ba2ef011a587c5558f6

I'm not confident that is the root cause, but this is the only change after us-core-test-kit version 0.2.2 that appears to be relevant to me. Our server passes all tests on version 2.2.1 of the onc-certification-g10-test-kit. The version we failed with is at the latest version of the main branch in the g10-kit, as I wanted to pick up the feature I added here:

https://github.com/onc-healthit/onc-certification-g10-test-kit/commit/31cd34274da67ce48cc9f31f85268a571b39ec62

**Comment by yunwwang** [comment]
What error messages did you see?

**Comment by nathanloyer** [comment]
> Could not find hospitalization.dischargeDisposition in the 48 provided Encounter resource(s)

**Comment by nathanloyer** [comment]
I'm trying out the attached fix to see if that resolves it. Not sure if this is the right solution or not, just wanted to share that I was trying to resolve this on my own already.

**Comment by nathanloyer** [comment]
Sorry should have added this earlier, all of our resources being returned have the following fields set on the objects

```json
  "hospitalization": {
    "dischargeDisposition": {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
          "valueCode": "not-applicable"
        }
      ],
      "text": "Not Applicable"
    }
  },
```

**Comment by nathanloyer** [comment]
![image](https://user-images.githubusercontent.com/10855885/181151775-e17df39f-21e6-4b6a-a236-076354687435.png)

the linked changes do resolve this issue for us

**Comment by yunwwang** [comment]
Yes. Inferno may have a different issue here. Could you post the whole Encounter resource? The code segment you post does not look correct. `hospitalization. dischargeDisposition` is a CodeableConcept. so that should be
```
  "hospitalization": {
    "dischargeDisposition": {
      "coding": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
          "valueCode": "not-applicable"
        }
      ],
      "text": "Not Applicable"
    }
  },
```

**Comment by nathanloyer** [comment]
@Jammjammjamm 

I'll follow up with our team that knows this data better to discuss in more detail why none of these resources have that field populated. We have two different types of practices in our product, hospital practices and ambulatory practices. The one that is failing is ambulatory, and this passes for the hospital practice that we test with. Just looking at the documentation in the spec I'm guessing we don't have this for ambulatory because the patient is never hospitalized with them, so they're never discharged. Doesn't seem like the data element would ever apply.

@yunwwang 

I redacted a few things, but this is pretty much what it looked like. The structure is fhir compliant though, a CodeableConcept is derived from Element, so we can have an `extension` field on it if we want to, and `coding` is 0..* so we don't have to include it. Encounter.hospitalization.dischargeDisposition is must-support and we supply a CodeableConcept object for it, but we have no relevant data for it in these cases so we attached a DAR. 

```json
{
  "location": [
    {
      "location": {
        "reference": "Location/1234"
      }
    }
  ],
  "period": {
    "start": "2000-01-01T00:00:00Z"
  },
  "resourceType": "Encounter",
  "hospitalization": {
    "dischargeDisposition": {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
          "valueCode": "not-applicable"
        }
      ],
      "text": "Not Applicable"
    }
  },
  "status": "entered-in-error",
  "subject": {
    "reference": "Patient/5"
  },
  "identifier": [
    {
      "system": "https://fhir.athena.io/sid/ah-encounter",
      "value": "3"
    }
  ],
  "participant": [
    {
      "type": [
        {
          "text": "The practitioner that has responsibility for overseeing a patient's care during a patient encounter.",
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
              "code": "ATND",
              "display": "attender"
            }
          ]
        },
        {
          "text": "The principal or primary performer of the act.",
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
              "code": "PPRF",
              "display": "primary performer"
            }
          ]
        }
      ],
      "individual": {
        "reference": "Practitioner/8"
      }
    }
  ],
  "id": "9809",
  "class": {
    "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
    "code": "VR",
    "display": "virtual"
  },
  "type": [
    {
      "text": "Indirect encounter",
      "coding": [
        {
          "system": "http://snomed.info/sct",
          "code": "185316007",
          "display": "Indirect encounter"
        }
      ]
    }
  ]
}
```

Here's another that failed that isn't entered-in-error.

```json
{
  "location": [
    {
      "location": {
        "reference": "Location/8913"
      }
    }
  ],
  "period": {
    "end": "2000-01-01T12:00:00Z",
    "start": "2000-01-01T14:00:00Z"
  },
  "resourceType": "Encounter",
  "hospitalization": {
    "dischargeDisposition": {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
          "valueCode": "not-applicable"
        }
      ],
      "text": "Not Applicable"
    }
  },
  "status": "finished",
  "subject": {
    "reference": "Patient/7364"
  },
  "identifier": [
    {
      "system": "https://fhir.athena.io/sid/ah-encounter",
      "value": "8544"
    }
  ],
  "participant": [
    {
      "period": {
        "start": "2000-01-01T13:00:00Z",
        "end": "2000-01-01T14:00:00Z"
      },
      "type": [
        {
          "text": "The practitioner that has responsibility for overseeing a patient's care during a patient encounter.",
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
              "code": "ATND",
              "display": "attender"
            }
          ]
        },
        {
          "text": "The principal or primary performer of the act.",
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
              "code": "PPRF",
              "display": "primary performer"
            }
          ]
        }
      ],
      "individual": {
        "reference": "Practitioner/13456"
      }
    }
  ],
  "id": "875",
  "class": {
    "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
    "code": "AMB",
    "display": "ambulatory"
  },
  "type": [
    {
      "text": "BRIEF EMOTIONAL/BEHAV ASSMT",
      "coding": [
        {
          "system": "http://www.ama-assn.org/go/cpt",
          "code": "96127",
          "display": "BRIEF EMOTIONAL/BEHAV ASSMT"
        }
      ]
    },
    {
      "text": "OFFICE/ OUTPATIENT E&M ESTABLISHED PATIENT",
      "coding": [
        {
          "system": "http://www.ama-assn.org/go/cpt",
          "code": "99213",
          "display": "OFFICE/ OUTPATIENT E&M ESTABLISHED PATIENT"
        }
      ]
    },
    {
      "text": "BRIEF EMOTIONAL/BEHAV ASSMT",
      "coding": [
        {
          "system": "http://www.ama-assn.org/go/cpt",
          "code": "96127",
          "display": "BRIEF EMOTIONAL/BEHAV ASSMT"
        }
      ]
    },
    {
      "text": "NO CHAD OR CHAD SCR 0 OR 1",
      "coding": [
        {
          "system": "urn:oid:2.16.840.1.113883.6.285",
          "code": "G9931",
          "display": "NO CHAD OR CHAD SCR 0 OR 1"
        }
      ]
    },
    {
      "text": "OFFICE/ OUTPATIENT E&M ESTABLISHED PATIENT",
      "coding": [
        {
          "system": "http://www.ama-assn.org/go/cpt",
          "code": "99213",
          "display": "OFFICE/ OUTPATIENT E&M ESTABLISHED PATIENT"
        }
      ]
    }
  ]
}
```

**Comment by yunwwang** [comment]
@nathanloyer I see the confusion here. You actually find a loophole in our logic. 

In this code segment:

```
  "hospitalization": {
    "dischargeDisposition": {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
          "valueCode": "not-applicable"
        }
      ],
      "text": "Not Applicable"
    }
  },
```

The meaning of this code segment is that the server could not populate `dischargeDisposition` with a reasonable value. When all the `dischargeDisposition` have the same segment, the server in practical fails the MustSupport requirement. In another way, the server does not demonstrate that it SUPPORT this element.

But structure wise, the server populates the `dischargeDisposition.text` element. In that sense, the server does provide something other than DAR extension.

One logic is that "IF there is DAR extension, ignores the element". The other is "IF there is anything other than DAR extension, takes the element"

For all the previous resources we have tests, these two logics yields the same result because all tests have either DAR or subelements.

This is the first time that we have seen that DAR extension and a subelement present at the same time. 

In @nathanloyer example, the DAR extension and subelement convey the same meaning. But what if they don't. For example, I could have a Patient like
```
  "name": [
    {
         "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
          "valueCode": "unknown"
        },
       "family": "Dole"
       "given": [ "John" ]
    }
  ]
```

Structure wise, this is valid. But what is the meaning of this element?

@nathanloyer Though you can attach DAR extension to any element. US Core has a guidance that your code segment fails to follow:

![image](https://user-images.githubusercontent.com/8761175/181279750-74351ab7-5e4d-4b07-b506-a6ad5451937e.png)

first, you have a text segment which should be enough to pass the MustSupport test.
second, if you do want to more specific, you should "if the value set does not have the appropriate “unknown” concept code, use unknown from the [DataAbsentReason Code System](http://hl7.org/fhir/R4/codesystem-data-absent-reason.html)"

**Comment by nathanloyer** [comment]
> first, you have a text, you should use text element without that extension. This should be enough to pass the MustSupport test.

Well that text is just a human friendly representation of the DAR code, so probably don't need it there.

> second, if you do want to more specific, you should follow this: "if the value set does not have the appropriate “unknown” concept code, use unknown from the [DataAbsentReason Code System](http://hl7.org/fhir/R4/codesystem-data-absent-reason.html)". That would be same as the example I posted above. That should also pass the MustSupport test.

So it sounds like your recommendation is to change it to this:

```json
  "hospitalization": {
    "dischargeDisposition": {
      "coding": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
          "valueCode": "unknown"
        }
      ],
      "text": "Not Applicable"
    }
  },
```

Or that, but with `text` removed?

I think we wanted to be more specific here, as for our system, labelling this as "Not Applicable" is more accurate than "Unknown". In this case, we know that we wont have data for that element because patients are never admitted/hospitalized at these practices.

If we just remove `text` do you think that would satisfy the ruling? i.e.

```json
```json
  "hospitalization": {
    "dischargeDisposition": {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
          "valueCode": "not-applicable"
        }
      ],
    }
  },
```

**Comment by yunwwang** [comment]
```quote
I think we wanted to be more specific here, as for our system, labelling this as "Not Applicable" is more accurate than "Unknown". In this case, we know that we wont have data for that element because patients are never admitted/hospitalized at these practices.
```
You CAN use "not-applicable" here. The binding strength is "example" which gives you freedom to use any code you prefer.

And I think the intention for the author here "if the value set does not have the appropriate “unknown” concept code, use unknown from the [DataAbsentReason Code System](http://hl7.org/fhir/R4/codesystem-data-absent-reason.html)" is "use **an appropriate unknown code** from the [DataAbsentReason Code System](http://hl7.org/fhir/R4/codesystem-data-absent-reason.html)"

I will ask US Core author to clarify

**Comment by nathanloyer** [comment]
Thanks for the help @yunwwang. After reviewing with some colleagues we've come to agree with your recommendation and will patch a fix in our code and reject this issue and my PR.

I will say that the spec for this in the US Core IG could be updated to be more clear. I feel like it takes too long to re-review the spec to understand the intention every time I come across a situation where we find we are lacking data for various reasons. 

As for why we don't have data for this element, I found my previous guess was correct that in these practices we will never have hospitalization data because they're not a hospital and patients aren't admitted to or discharged from them.
