### ISSUE TITLE
Getting error with the terminology resources after building terminology. Please help!!

### ISSUE THREAD

**Issue by NeetaRamani** [onc-healthit/onc-certification-g10-test-kit#185]
Have taken all the latest files and also the terminology download is happening auto from UML, still getting following errors... 

http://hl7.org/fhir/ValueSet/clinical-findings: Expected codes: 158602 Actual codes: 156845
http://hl7.org/fhir/us/core/ValueSet/us-core-careteam-provider-roles: Expected codes: 1731 Actual codes: 1723
http://hl7.org/fhir/us/core/ValueSet/us-core-condition-code: Expected codes: 297182 Actual codes: 295223
http://hl7.org/fhir/ValueSet/device-kind: Expected codes: 16557 Actual codes: 16507
http://hl7.org/fhir/us/core/ValueSet/us-core-diagnosticreport-report-and-note-codes: Expected codes: 270991 Actual codes: 266703
http://hl7.org/fhir/us/core/ValueSet/us-core-diagnosticreport-lab-codes: Expected codes: 57824 Actual codes: 57115
http://hl7.org/fhir/us/core/ValueSet/us-core-documentreference-type: Expected codes: 10602 Actual codes: 10446
http://hl7.org/fhir/us/core/ValueSet/us-core-encounter-type: Expected codes: 15951 Actual codes: 15646
http://hl7.org/fhir/us/core/ValueSet/us-core-medication-codes: Expected codes: 130098 Actual codes: 129310
http://hl7.org/fhir/ValueSet/observation-codes: Expected codes: 270991 Actual codes: 266703
http://hl7.org/fhir/us/core/ValueSet/us-core-procedure-code: Expected codes: 285523 Actual codes: 284654
http://www.nlm.nih.gov/research/umls/rxnorm: Expected codes: 210338 Actual codes: 208846
http://snomed.info/sct: Expected codes: 489140 Actual codes: 485053
http://loinc.org: Expected codes: 270991 Actual codes: 266703
http://www.ama-assn.org/go/cpt: Expected codes: 14654 Actual codes: 14377
http://hl7.org/fhir/sid/cvx: Expected codes: 211 Actual codes: 206
http://unitsofmeasure.org: Expected codes: 1423 Actual codes: 1400
urn:oid:2.16.840.1.113883.6.285: Expected codes: 7783 Actual codes: 7563

When checked with bundle command if the terminology is correctly built, getting following --
bundle exec rake "terminology:check_code[91935009,http://snomed.info/sct]" --trace
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/pry-byebug-3.8.0/lib/pry-byebug/control_d_handler.rb:5: warning: control_d_handler's arity of 2 parameters was deprecated (eval_string, pry_instance). Now it gets passed just 1 parameter (pry_instance)
rake aborted!
LoadError: cannot load such file -- ffi
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rest-client-2.1.0/lib/restclient/windows/root_certs.rb:2:in `require'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rest-client-2.1.0/lib/restclient/windows/root_certs.rb:2:in `<top (required)>'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rest-client-2.1.0/lib/restclient/windows.rb:7:in `require_relative'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rest-client-2.1.0/lib/restclient/windows.rb:7:in `<top (required)>'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rest-client-2.1.0/lib/restclient.rb:17:in `require'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rest-client-2.1.0/lib/restclient.rb:17:in `<top (required)>'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rest-client-2.1.0/lib/rest-client.rb:2:in `require'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rest-client-2.1.0/lib/rest-client.rb:2:in `<top (required)>'
C:/Users/neeta_r/Downloads/onc-certification-g10-test-kit-main/lib/inferno/terminology/tasks/download_umls.rb:2:in `require'
C:/Users/neeta_r/Downloads/onc-certification-g10-test-kit-main/lib/inferno/terminology/tasks/download_umls.rb:2:in `<top (required)>'
C:/Users/neeta_r/Downloads/onc-certification-g10-test-kit-main/lib/inferno/terminology/tasks.rb:2:in `require_relative'
C:/Users/neeta_r/Downloads/onc-certification-g10-test-kit-main/lib/inferno/terminology/tasks.rb:2:in `block in <top (required)>'
C:/Users/neeta_r/Downloads/onc-certification-g10-test-kit-main/lib/inferno/terminology/tasks.rb:1:in `each'
C:/Users/neeta_r/Downloads/onc-certification-g10-test-kit-main/lib/inferno/terminology/tasks.rb:1:in `<top (required)>'
C:/Users/neeta_r/Downloads/onc-certification-g10-test-kit-main/Rakefile:6:in `require_relative'
C:/Users/neeta_r/Downloads/onc-certification-g10-test-kit-main/Rakefile:6:in `<top (required)>'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
C:/Ruby31-x64/bin/rake:33:in `load'
C:/Ruby31-x64/bin/rake:33:in `<main>'

**Comment by Jammjammjamm** [comment]
I recommend you look at the potential solutions in this issue: https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/87

**Comment by yunwwang** [comment]
@NeetaRamani 

Do you still experience the same issue? I will close this issue in a few days if the solution provided above addressed your failure.

Thank you.
