### ISSUE TITLE
Loading test data

### ISSUE THREAD

**Issue by NeetaRamani** [onc-healthit/onc-certification-g10-test-kit#187]
I am looking for how to load the patients data from our system on inferno so we can test the exported files? What is location of test data that can be placed after the installation/setup is done?

**Comment by yunwwang** [comment]
@NeetaRamani I already replied in your zulip thread. Let's continue the discussion there. https://chat.fhir.org/#narrow/stream/179309-inferno/topic/test.20data.20inferno
