### ISSUE TITLE
R4 Observation.id: Invalid Resource id

### ISSUE THREAD

**Issue by MTroianov** [onc-healthit/onc-certification-g10-test-kit#189]
Our FHIR server is generating ids for some records with the following pattern:
`CV:<numeric identifier>:SECT:<numeric identifier>`
For example:
`CV:11111111:SECT:222222`
This results in the failure on the 8th test for us_core_v400_pulse_oximetry profile with following error:
<img width="349" alt="Screenshot 2022-07-29 at 21 19 03" src="https://user-images.githubusercontent.com/79840590/181820607-33ec3fa3-5a3d-4147-8c8f-a674f6079e69.png">

My assumption is that `:` is not allowed in the Resource Id, but I think that it should be allowed according to URI standard.
Could you recommend what would be the best solution to this issue?

**Comment by yunwwang** [comment]
@MTroianov 

Thank you for raising this issue to us. According to FHIR definition, an `id` is


Any combination of upper- or lower-case ASCII letters ('A'..'Z', and 'a'..'z', numerals ('0'..'9'), '-' and '.', with a length limit of 64 characters. (This might be an integer, an un-prefixed OID, UUID or any other identifier pattern that meets these constraints.) 

Regex: [A-Za-z0-9\-\.]{1,64}


So the `:` character is invalid here

**Comment by MTroianov** [comment]
Thank you for help and explanation! We will probably change it to `-` or `.`
