### ISSUE TITLE
Inferno g(10) test fails on underscore in resource id

### ISSUE THREAD

**Issue by vganshin** [onc-healthit/onc-certification-g10-test-kit#192]
Hello. We noticed that Inferno fails on underscore in resource id. I could not find any comment that says underscore is invalid symbol in id.

<img width="1369" alt="Screenshot 2022-08-03 at 12 47 58" src="https://user-images.githubusercontent.com/1931520/182590862-231a1e06-4d76-40fb-bf37-bfa38d38f1a5.png">

**Comment by Jammjammjamm** [comment]
https://www.hl7.org/fhir/datatypes.html#id

**Comment by vganshin** [comment]
Have a look at [Resource](https://www.hl7.org/fhir/resource.html#Resource) spec. id field has `string` type, not `id` one.

**Comment by arscan** [comment]
I'm not sure why they don't just use the `id` type there, but regardless they do describe the format requirement on the `id` element in the [Logical Id](https://www.hl7.org/fhir/resource.html#id) section.

> Logical ids (and therefore locations) are case sensitive. Logical Ids are always opaque, and external systems need not and should not attempt to determine their internal structure. A logical id SHALL always be represented in the same way in resource references and URLs. Ids can be up to 64 characters long, and contain any combination of upper and lowercase ASCII letters, numerals, "-" and ".". 

This error is coming straight out of the HL7 FHIR Validator.

I do wonder why they chose not to use the `id` type in the Resource though.

**Comment by Jammjammjamm** [comment]
That is FHIR 4.3.0. Certification is still based on FHIR 4.0.1, where it's an `id`: http://hl7.org/fhir/R4/resource.html

**Comment by arscan** [comment]
Looks like R4b (4.3.0, the current published release but not the one used in US Core) introduced this problem, which was acknowledged and is fixed in R5.

See https://jira.hl7.org/browse/FHIR-25262 and http://hl7.org/fhir/5.0.0-snapshot1/resource.html#resource
