### ISSUE TITLE
4.0.0 Encounter 29.10 Failure 

### ISSUE THREAD

**Issue by jj027509** [onc-healthit/onc-certification-g10-test-kit#204]
29.10 "Encounter resources returned during previous tests conform to the US Core Encounter Profile" is failing, stating that the "Resource does not conform to the profile http://hl7.org/fhir/us/core/StructureDefinition/us-core-encounter". 

Test session showing error: https://inferno.healthit.gov/suites/test_sessions/c3627b9d-17a9-4388-b3a7-f16f3e46e1f9#us_core_v400-us_core_v400_encounter

We believe this is occurring because the string we are returning contains a colon, however, there are no listed defined character exclusions for internal ids, as shown here https://www.hl7.org/fhir/element.html#id.

The id which is causing an error on 29.10 is an element.id https://www.hl7.org/fhir/element-definitions.html#Element.id which states it can be 'any string value except blank spaces'. Therefore we believe this test should be passing with what we are returning.

**Comment by yunwwang** [comment]
@jj027509 I tested your resource on inferno-dev which does not give any error. Can you re-run the test tomorrow with new Inferno release?

**Comment by jj027509** [comment]
@yunwwang  This passed when I tested today. Thank you!
