### ISSUE TITLE
No support for passing tenant_id for multi-tenant FHIR server

### ISSUE THREAD

**Issue by satyaki-bhargava** [onc-healthit/onc-certification-g10-test-kit#205]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Current version does not have any place to pass tenant_id or Inferno does not append tenant_id received as a parameter **

**Dev/QA/Stage/Prod**
* Edition of inferno (Community or Program): Community and Program
* Version of inferno: V.2.2.1
* Which browser and version(s) is the bug present on?: Edge, Chrome

**Steps to reproduce**
1. New Session->ONC Certification (g)(10) Standardized API->Start Testing
2. Run All Tests
3. Input All Required Details like FHIR base URL, clientids, secret, patient ids etc.
4. 

Include:

* (g)10 Standardized API
* https://fhir-api.fhirdev.aws.greenwayhealth.com/fhir/R4
* 1.2.08 test fails as our FHIR server is multi-tenant and tenant_id needs to appended after FHIR base URL before appending resource specific paths.

**Expected behavior**
There should be a way in Inferno to either pass tenant_id or read response parameter tenant as per Smart On FHIR STU2(http://hl7.org/fhir/smart-app-launch/scopes-and-launch-context.html)

**Actual behavior**
1.2.08 test fails as our FHIR server is multi-tenant and tenant_id needs to appended after FHIR base URL before appending resource specific paths.

**Comment by yunwwang** [comment]
@satyaki-bhargava Steve answered your question on zulip: https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Support.20for.20SMART.20IG.202.2E0.2E0.3A.20.22tenant.22.20launch.20context. Please let us know if you need further help.

**Comment by satyaki-bhargava** [comment]
@yunwwang : That was the answer which lead to come and open this ticket. Current inferno version, does not support multitenant FHIR servers. Which is leading to generate 3000 FHIR URLS for 3000 tenants(Practices). Which shook the whole design of multitenancy that should work in practical.

**Comment by yunwwang** [comment]
Here is Josh's response in the SMART stream: https://chat.fhir.org/#narrow/stream/179170-smart/topic/SoF.20Launch.20Framework.20-.20Multitenancy.20FHIR.20Server.20Support
