### ISSUE TITLE
g10 test kit walkthrough wiki

### ISSUE THREAD

**Issue by rpassas** [onc-healthit/onc-certification-g10-test-kit#208]
We are hoping to updated the wiki with a walkthrough for the test kit. Because wiki branches [do not show ](https://stackoverflow.com/questions/32049506/how-to-access-github-wiki-branches)in github and I cannot open a PR for it, I will point you to [my repo](https://github.com/rpassas/g10_wiki) with the proposed wiki update to be merged in. 

Cheers,
Rob the inferno intern

**Comment by arscan** [comment]
I was able to pull in the updates by moving the commit to the `master` branch and pushing that up, thanks!
