### ISSUE TITLE
Terminology count tests failing with Inferno 2.3.0. in ONC Certification (g)(10) Standardized API

### ISSUE THREAD

**Issue by danielberez** [onc-healthit/onc-certification-g10-test-kit#217]
Hi Team,
I just installed the 2.3.0 version of Inferno, and after running the 2 commands _(
docker-compose -f terminology_compose.yml run terminology_builder bin/prepare_terminology.sh 2021
docker-compose -f terminology_compose.yml run terminology_builder bundle exec rake terminology:create_vs_validators["preferred","2021","false"] )_
I'm still getting non matching count errors below when selecting ONC Certification (a)(10) Standardized API test

- http://hl7.org/fhir/us/core/ValueSet/us-core-encounter-type: Expected codes: 15951 Actual codes: 15949
- http://hl7.org/fhir/us/core/ValueSet/us-core-procedure-code: Expected codes: 285523 Actual codes: 285512
- http://snomed.info/sct: Expected codes: 489140 Actual codes: 489139

Let me know if you have any ideas how to solve this .

**Comment by Jammjammjamm** [comment]
You started by running `docker-compose -f terminology_compose.yml up` rather than just running the two commands you posted, right?

My general advice would be to delete `tmp/terminology` and `resources/terminology/validators/bloom` and try again.

If you have ruby and java set up locally, you could also try running the build without docker with:
```
bundle install
UMLS_API_KEY=YOUR_UMLS_API_KEY bin/run_terminology.sh 2>&1 | tee terminology.log
```
That will also save the log from your build to `terminology.log` so you can look for issues.

**Comment by adunsulag** [comment]
I'm also running into this issue.  I tried the local build process and had to actually change the file ownership during the first execution 
```
bundle install
UMLS_API_KEY=YOUR_UMLS_API_KEY bin/run_terminology.sh 2>&1 | tee terminology.log
```
As all of the files get stored as the root owner.  Running the same command again with the file ownership change downloaded the terminology files and the command successfully executed with a status code of 0.

**Comment by danielberez** [comment]
Hi team, deleting everything, updating the Linux sever, and re-running the same commands fixed the count miss match.
Thanks for your help !
