### ISSUE TITLE
Is there anyway to run the (4. Single Patient API) tests for a Single Resource ?

### ISSUE THREAD

**Issue by nxsahib** [onc-healthit/onc-certification-g10-test-kit#221]
Currently when we run the tests for (4. Single Patient API), it tries to run all 212 Tests which then have numerous sub tests(calls) which takes very long. I was wondering if there is a way to run these tests for a single resource. This will save us a lot of time when trying to resolve some failing tests.

**Comment by yunwwang** [comment]
US Core Test Kit allows tester to run a single test group. There are some difference between g10 Test Kit and US Core Test Kit:
* US Core Test Kit does not include SMART launch. If server requires access token, such token need to pre generated.
* US Core Test Kit has many optional test which are not included in g10 Test Kit
* US Core Test Kit uses general terminology server tx.fhir.org/r4 for terminology validation. Tester MAY see difference validation results between US Core Test Kit and g10 Test Kit.

**Comment by nxsahib** [comment]
Thanks, this helps.
