### ISSUE TITLE
Single Patient API is using the client app details (access token, etc) from the EHR Patient Launch flow

### ISSUE THREAD

**Issue by dhit-mdavis** [onc-healthit/onc-certification-g10-test-kit#227]
Hi there. I have this scenario which I feel is a Inferno v2 bug from the most recent update as this hasn't been an issue previously.

### Understanding

- The Single Patient API is supposed to use the client app credentials from the Standalone Patient App test, correct?
- This is similar to how the Limited Access App uses the patient and access token from the Standalone Patient App
- Is this understanding incorrect?

### Issue
When running the Inferno v2 tests in order, I noticed that the client app details (access token, etc) from the EHR Practitioner Launch was being used for Single Patient API.

This was mainly an issue because 

- the patients contained different data which caused the Single Patient API tests to fail 1 single subtest. 
- this had not been an issue during my many previous Inferno v2 end to end runs
- this contradicted my understanding of which client app details would be used when running Single Patient API
- while ensuring both patients have passing data is definitely important, having the EHR Practitioner Launch patient context be used for the Single Patient API tests was unexpected and not the case for previous versions of Inferno v2 that I can recall

Any confirmation or feedback on expectations would be helpful.

Thanks - Mat

**Comment by Jammjammjamm** [comment]
There have been no changes regarding this. The Single Patient API tests use the credentials for the launch performed most recently. The intent is that the tests are run in order and use the credentials from the EHR Launch because a single patient may not have sufficient data to pass the tests, and the user scopes used in the EHR Launch allow access to multiple patients if necessary. If you run the tests out of order or only run the Standalone Launch, those credentials will be used.

**Comment by dhit-mdavis** [comment]
Thanks for that clarification @Jammjammjamm. The reason I considered it a bug was that this was not an issue previously.

I do at times run just test #1 and #4 back to back but most times, I run from end to end in order and have not had any failures previously.

It's also not clear that the credentials from the launch most recently used will be used for Single Patient API. Maybe that can be a future improvement or note added to the test info. If it already exists, please let me know.

Thank you again for your time.

**Comment by yunwwang** [comment]
@dhit-mdavis 

I will close this ticket as question already answered. If you have further questions, please either reopen this one or create a new github issue. 

Thank you.

**Comment by dhit-mdavis** [comment]
Agreed Yun
