### ISSUE TITLE
ONC Certification (g)(10) V.2.3.0 Document Reference Issue

### ISSUE THREAD

**Issue by canonmagic** [onc-healthit/onc-certification-g10-test-kit#231]
Getting a validation failure during Multi-Patient API testing for Document Reference resource with the following message:

DocumentReference/3d240ab4-2a1b-4d4f-a153-a76edea45235 at DocumentReference.type with code http://loinc.org|100018-1 is not in http://hl7.org/fhir/us/core/ValueSet/us-core-documentreference-type.

And clearly the code is included in the valueSet referenced

![image](https://user-images.githubusercontent.com/56048433/186485284-3e2dc8c3-f7f6-4ea6-8a49-fb09e4a9833b.png)

**Comment by Jammjammjamm** [comment]
I believe the issue here is that that code was added in LOINC 2.7.2, which the g10 test kit is not yet using. We will look into updating our terminology to include this version of LOINC.
