### ISSUE TITLE
1.1.03 Conformance/CapabilityStatement provides OAuth 2.0 endpoints

### ISSUE THREAD

**Issue by sjayswal** [onc-healthit/onc-certification-g10-test-kit#233]
Hello, 

While testing the (Standalone Patient App) in ONC Certification (g)(10) Standardized API V.2.3.0. We are facing this issue. Kindly give your suggestions for the same. 

1.1.03 Conformance/CapabilityStatement provides OAuth 2.0 endpoints

Error: undefined method `service' for nil:NilClass

/usr/local/bundle/gems/smart_app_launch_test_kit-0.1.5/lib/smart_app_launch/discovery_stu1_group.rb:75:in `block (3 levels) in [class:DiscoverySTU1Group](javascript:void(0))'

**Comment by yunwwang** [comment]
Can you post you CapabilityStatement or the url to access your CapabilityStatement?

**Comment by sjayswal** [comment]
[metadata.txt](https://github.com/onc-healthit/onc-certification-g10-test-kit/files/9430981/metadata.txt)

Thank you for your quick reply,
attaching my meta file.

**Comment by yunwwang** [comment]
In the CapbilityStatement, you have two `rest` items. The first one does not have `rest.security`, the second one has only `rest.secruity`. None of them are valid.

**Comment by sjayswal** [comment]
> In the CapbilityStatement, you have two `rest` items. The first one does not have `rest.security`, the second one has only `rest.secruity`. None of them are valid.

Thank you for reply, can give us example of correct file please?

**Comment by yunwwang** [comment]
You can check the example in SMART App Launch v1.0.0

http://hl7.org/fhir/smart-app-launch/1.0.0/CapabilityStatement-smart-app-launch-example.html

**Comment by sjayswal** [comment]
> In the CapbilityStatement, you have two `rest` items. The first one does not have `rest.security`, the second one has only `rest.secruity`. None of them are valid.

Hello, 

We have checked our CapabilityStatement, we found only one 'rest' item. Still following the standard of http://hl7.org/fhir/smart-app-launch/1.0.0/conformance/index.html#example, we made some changes and found the below error. 

**1.1.03 Conformance/CapabilityStatement provides OAuth 2.0 endpoints
No authorize extension found**

Attaching our capability-statement for your reference.  Kindly provide your inputs. 
[metadata.txt](https://github.com/onc-healthit/onc-certification-g10-test-kit/files/9443697/metadata.txt)

**Comment by yunwwang** [comment]
![image](https://user-images.githubusercontent.com/8761175/187222156-8ea3f61b-4a93-4862-9fc6-6a97dc835dfd.png)

`valueString` should be `valueUri`

**Comment by sjayswal** [comment]
Hello @yunwwang ,  Thank you for inputs. We have resolved the specified issue.
