### ISSUE TITLE
Percentile Profile being used to validate regular Head Circumference resource (FI-1702)

### ISSUE THREAD

**Issue by jlgrater** [onc-healthit/onc-certification-g10-test-kit#238]
Hi - We have a resource that was passing validation until recently in the Multi-patient API tests. The resource is a Vital Sign Observation for Head Circumference. It looks like the profile for the head circumference percentile is being applied for validation.

![image](https://user-images.githubusercontent.com/79801587/187478991-0e2b7700-f6e6-469f-be15-9131e4df2e42.png)

Test instance: https://inferno.healthit.gov/suites/test_sessions/68e32f77-be56-4d43-95e7-0abb339af761#g10_certification-multi_patient_api

**Comment by Jammjammjamm** [comment]
Thank you for the report. We will address this issue.

**Comment by yunwwang** [comment]
This will be in release next week.

**Comment by madhavdarji** [comment]
We are seeing the same issue with 1 following difference.. the error says '4 / 37 Observation resources failed profile validation. The line number for the first failed resource is 1.' but only 1 error is listed in the messages tab or is Inferno going to only list 1 error? PFA screenshot.

![2022-09-13 14_20_13-Inferno](https://user-images.githubusercontent.com/23702849/189980584-dcbbcb1f-dd44-44bc-9d41-04f6add7d07d.png)

cc @yunwwang @Jammjammjamm
