### ISSUE TITLE
Clinical Notes Guidance & DocumentReference Tests

### ISSUE THREAD

**Issue by madhavdarji** [onc-healthit/onc-certification-g10-test-kit#239]
Hello Inferno team, I wanted to check if inferno can initiate request for each of the mandatory document types. In our case we return 1 summary document with type = 34133-9 for patient based search. Another issue is that a non DAR value is only present in the context.encounter when encounter is supplied in the query.

**Comment by yunwwang** [comment]
This question is answered on zulip: https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Clinical.20Notes.20Guidance.20.26.20DocumentReference.20Tests
