### ISSUE TITLE
Warnings on 5.9.09 Must Support References within DiagnosticReport (ONC Certification (g)(10) Standardized API - US Core 4.0.0) (FI-1703) 

### ISSUE THREAD

**Issue by fpivonka** [onc-healthit/onc-certification-g10-test-kit#240]
We are receiving the warnings listed below in our test run on 5.9.09 Must Support References within DiagnosticReport must be read. The actual test step passes and you can see in the HTTP requests successful responses are returned, so we are unsure of how to interpret the warnings and whether we have an issue on our side. Could you please help us understand what these warnings indicate?

https://inferno.healthit.gov/suites/test_sessions/ccf69e28-414e-4c21-8c66-812e06c3f8f2#g10_certification-g10_single_patient_us_core_4_api

- Practitioner/1293170:  Practitioner: Specified profile type was 'Organization' in profile  'http://hl7.org/fhir/us/core/StructureDefinition/us-core-organization',  but found type 'Practitioner'
- Practitioner/3863780: Practitioner: Specified profile type was 'Organization' in profile 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-organization', but found type 'Practitioner'
- Practitioner/1293195:  Practitioner: Specified profile type was 'Organization' in profile  'http://hl7.org/fhir/us/core/StructureDefinition/us-core-organization',  but found type 'Practitioner'

**Comment by yunwwang** [comment]
Thanks. That is a bug in our code while handling multiple Must Support target reference. We will fix that asap.

**Comment by fpivonka** [comment]
> Thanks. That is a bug in our code while handling multiple Must Support target reference. We will fix that asap.

@yunwwang I just want to verify, we are seeing a similar warning in 5.5.06 CareTeam must support references. Is this the same issue?

RelatedPerson/4907828: RelatedPerson: Specified profile type was 'Practitioner' in profile 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-practitioner', but found type 'RelatedPerson'
