### ISSUE TITLE
 problem with the terminology resources

### ISSUE THREAD

**Issue by javacup** [onc-healthit/onc-certification-g10-test-kit#243]
I was finally able to build the terminology resources using 

docker-compose -f terminology_compose.yml up

It took a very long time, but it did complete with the following message
terminology_builder_1  | removing terminology precursor files in tmp/terminology/2020

Now, when I launch inferno -> g10 test suite I get an error ribbon "There is a problem with the terminology resources"

The details are presented below. In the info tab, it shows another list of terminology resources, which I'm assuming that were correctly built. I'm wondering if the terminology scripts have to also download for year 2021 & 2022. 

http://hl7.org/fhir/ValueSet/clinical-findings: Expected codes: 158602 Actual codes: 156845
http://hl7.org/fhir/us/core/ValueSet/us-core-careteam-provider-roles: Expected codes: 1731 Actual codes: 1723
http://hl7.org/fhir/us/core/ValueSet/us-core-condition-category: Expected codes: 4 Actual codes: 3
http://hl7.org/fhir/us/core/ValueSet/us-core-condition-code: Expected codes: 297482 Actual codes: 295223
http://hl7.org/fhir/ValueSet/device-kind: Expected codes: 16557 Actual codes: 16507
http://hl7.org/fhir/us/core/ValueSet/us-core-diagnosticreport-report-and-note-codes: Expected codes: 24810 Actual codes: 266703
http://hl7.org/fhir/us/core/ValueSet/us-core-diagnosticreport-lab-codes: Expected codes: 57824 Actual codes: 57115
http://hl7.org/fhir/us/core/ValueSet/us-core-documentreference-type: Expected codes: 10602 Actual codes: 10446
http://hl7.org/fhir/ValueSet/security-labels: Expected codes: 200 Actual codes: 200
http://hl7.org/fhir/us/core/ValueSet/us-core-encounter-type: Expected codes: 15951 Actual codes: 15646
http://hl7.org/fhir/us/core/ValueSet/us-core-usps-state: Expected codes: 62 Actual codes: 59
http://hl7.org/fhir/us/core/ValueSet/us-core-medication-codes: Expected codes: 130098 Actual codes: 129310
http://hl7.org/fhir/ValueSet/observation-codes: Expected codes: 270991 Actual codes: 266703
http://hl7.org/fhir/us/core/ValueSet/omb-race-category: Expected codes: 8 Actual codes: 7
http://hl7.org/fhir/us/core/ValueSet/detailed-race: Expected codes: 919 Actual codes: 917
http://hl7.org/fhir/us/core/ValueSet/omb-ethnicity-category: Expected codes: 4 Actual codes: 2
http://hl7.org/fhir/us/core/ValueSet/detailed-ethnicity: Expected codes: 44 Actual codes: 42
http://hl7.org/fhir/us/core/ValueSet/birthsex: Expected codes: 5 Actual codes: 3
http://hl7.org/fhir/us/core/ValueSet/us-core-provider-role: Expected codes: 862 Actual codes: 237
http://hl7.org/fhir/us/core/ValueSet/us-core-provider-specialty: Expected codes: 862 Actual codes: 862
http://hl7.org/fhir/us/core/ValueSet/us-core-procedure-code: Expected codes: 556515 Actual codes: 284654
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1186.8: Not loaded
http://hl7.org/fhir/ValueSet/narrative-status: Not loaded
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1099.30: Not loaded
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1010.6: Not loaded
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1010.4: Not loaded
http://hl7.org/fhir/ValueSet/medicationrequest-category: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-vital-signs: Not loaded
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.11.20.9.38: Not loaded
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.114222.4.11.1066: Not loaded
http://hl7.org/fhir/ValueSet/resource-types: Not loaded
http://hl7.org/fhir/ValueSet/condition-category: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-problem-or-health-concern: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-goal-description: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-common-sdoh-assessments: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-sexual-orientation: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-survey-codes: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-clinical-test-codes: Not loaded
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1021.32: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-tags: Not loaded
http://hl7.org/fhir/ValueSet/questionnaire-answers-status: Not loaded
http://hl7.org/fhir/ValueSet/relatedperson-relationshiptype: Not loaded
http://hl7.org/fhir/ValueSet/request-intent: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-servicerequest-category: Not loaded
http://www.nlm.nih.gov/research/umls/rxnorm: Expected codes: 210338 Actual codes: 208846
http://snomed.info/sct: Expected codes: 489140 Actual codes: 485053
urn:oid:2.16.840.1.113883.6.101: Not loaded
http://loinc.org: Expected codes: 270991 Actual codes: 266703
http://terminology.hl7.org/CodeSystem/v3-Confidentiality: Not loaded
http://terminology.hl7.org/CodeSystem/v3-ObservationValue: Not loaded
http://www.ama-assn.org/go/cpt: Expected codes: 14654 Actual codes: 14377
http://hl7.org/fhir/sid/cvx: Expected codes: 211 Actual codes: 206
https://www.usps.com/: Expected codes: 62 Actual codes: 59
http://unitsofmeasure.org: Expected codes: 1423 Actual codes: 1400
http://www.cms.gov/Medicare/Coding/HCPCSReleaseCodeSets: Not loaded
http://www.ada.org/cdt: Not loaded
urn:oid:2.16.840.1.113883.6.285: Expected codes: 7783 Actual codes: 7563
http://ada.org/cdt: Not loaded
http://terminology.hl7.org/CodeSystem/v3-ParticipationFunction: Not loaded
http://terminology.hl7.org/CodeSystem/medicationrequest-category: Not loaded
http://hl7.org/fhir/us/core/CodeSystem/us-core-tags: Not loaded
http://hl7.org/fhir/questionnaire-answers-status: Not loaded

**Comment by javacup** [comment]
btw, I did pull the latest from git before building the terminology resources.

**Comment by Jammjammjamm** [comment]
If removing the temporary 2020 files is the last thing you saw, that means the 2021 terminology wasn't processed. These are the commands to just run it for 2021: https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/87#issuecomment-1151055429

**Comment by javacup** [comment]
Awesome! thank you.. just now kicked off the terminology resources for 2021

**Comment by javacup** [comment]
I ran the following command.. 

docker-compose -f terminology_compose.yml run terminology_builder bin/prepare_terminology.sh 2021
docker-compose -f terminology_compose.yml run terminology_builder bundle exec rake terminology:create_vs_validators["preferred","2021","false"]

as posted in the comment above. It went through the download and extract process... I'm not posting the entire log.. to reduce the verbosity of this message. I'm only posting the last part of the log.. when I load inferno.. it still gives the same "problem with the terminology resources" and the mismatched and not loaded resource messages.

Using /opt/inferno/resources/inferno_2021.prop
/opt/inferno/tmp/terminology/2021/umls/2021AA-full
Running MetamorphoSys (this may take a while)...
log4j:WARN No appenders could be found for logger (org.java.plugin.boot.DefaultApplicationInitializer).
log4j:WARN Please initialize the log4j system properly.
done
FHIR Package sources already exist; skipping Package download.
Version: 2021
Dropping existing mrconso table
Creating mrconso table
Removing last pipe from RRF
Populating mrconso table
Dropping existing mrrel table
Creating mrrel table
Removing last pipe from RRF
Populating mrrel table
Dropping existing mrsat table
Creating mrsat table
Removing last pipe from RRF
Populating mrsat table
Dropping existing mrsab table
Creating mrsab table
Removing last pipe from RRF
Populating mrsab table
Indexing mrsat(SAB,ATN,ATV)
Indexing mrconso(AUI)
Indexing mrconso(SAB,TTY)
Indexing mrrel(REL,SAB)
Analyzing Database
zsh: no matches found: terminology:create_vs_validators[preferred,2021,false]

**Comment by Jammjammjamm** [comment]
If you're using `zsh`, you have to escape square brackets:

```
docker-compose -f terminology_compose.yml run terminology_builder bundle exec rake terminology:create_vs_validators\["preferred","2021","false"\]
```

**Comment by javacup** [comment]
Alright... looks like its getting better... but not fully done yet..  After running the above command, I restarted the server, but got the following. 

The Configuration messages tab is now showing 2 messages.  The 2nd message has some entries with matching counts.. but reported as an error message like the first one  Expected codes: 1731 Actual codes: 1731 

Any further suggestions?

1. Unable to connect to Validator: Failed to open TCP connection to validator_service:4567 (Connection refused - connect(2) for "validator_service" port 4567)

2. There is a problem with the terminology resources. See the README for the [G10 Certification Test Kit README](https://github.com/inferno-framework/g10-certification-test-kit#terminology-support) for instructions on building the required terminology resources:

http://hl7.org/fhir/us/core/ValueSet/us-core-careteam-provider-roles: Expected codes: 1731 Actual codes: 1731
http://hl7.org/fhir/us/core/ValueSet/us-core-condition-category: Expected codes: 4 Actual codes: 3
http://hl7.org/fhir/us/core/ValueSet/us-core-condition-code: Expected codes: 297482 Actual codes: 297182
http://hl7.org/fhir/us/core/ValueSet/us-core-diagnosticreport-report-and-note-codes: Expected codes: 24810 Actual codes: 270991
http://hl7.org/fhir/ValueSet/security-labels: Expected codes: 200 Actual codes: 200
http://hl7.org/fhir/us/core/ValueSet/us-core-usps-state: Expected codes: 62 Actual codes: 59
http://hl7.org/fhir/us/core/ValueSet/omb-race-category: Expected codes: 8 Actual codes: 7
http://hl7.org/fhir/us/core/ValueSet/detailed-race: Expected codes: 919 Actual codes: 917
http://hl7.org/fhir/us/core/ValueSet/omb-ethnicity-category: Expected codes: 4 Actual codes: 2
http://hl7.org/fhir/us/core/ValueSet/detailed-ethnicity: Expected codes: 44 Actual codes: 42
http://hl7.org/fhir/us/core/ValueSet/birthsex: Expected codes: 5 Actual codes: 3
http://hl7.org/fhir/us/core/ValueSet/us-core-provider-role: Expected codes: 862 Actual codes: 237
http://hl7.org/fhir/us/core/ValueSet/us-core-provider-specialty: Expected codes: 862 Actual codes: 862
http://hl7.org/fhir/us/core/ValueSet/us-core-procedure-code: Expected codes: 556515 Actual codes: 285523
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1186.8: Not loaded
http://hl7.org/fhir/ValueSet/narrative-status: Not loaded
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1099.30: Not loaded
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1010.6: Not loaded
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1010.4: Not loaded
http://hl7.org/fhir/ValueSet/medicationrequest-category: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-vital-signs: Not loaded
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.11.20.9.38: Not loaded
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.114222.4.11.1066: Not loaded
http://hl7.org/fhir/ValueSet/resource-types: Not loaded
http://hl7.org/fhir/ValueSet/condition-category: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-problem-or-health-concern: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-goal-description: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-common-sdoh-assessments: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-sexual-orientation: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-survey-codes: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-clinical-test-codes: Not loaded
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1021.32: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-tags: Not loaded
http://hl7.org/fhir/ValueSet/questionnaire-answers-status: Not loaded
http://hl7.org/fhir/ValueSet/relatedperson-relationshiptype: Not loaded
http://hl7.org/fhir/ValueSet/request-intent: Not loaded
http://hl7.org/fhir/us/core/ValueSet/us-core-servicerequest-category: Not loaded
urn:oid:2.16.840.1.113883.6.101: Not loaded
http://terminology.hl7.org/CodeSystem/v3-Confidentiality: Not loaded
http://terminology.hl7.org/CodeSystem/v3-ObservationValue: Not loaded
https://www.usps.com/: Expected codes: 62 Actual codes: 59
http://www.cms.gov/Medicare/Coding/HCPCSReleaseCodeSets: Not loaded
http://www.ada.org/cdt: Not loaded
http://ada.org/cdt: Not loaded
http://terminology.hl7.org/CodeSystem/v3-ParticipationFunction: Not loaded
http://terminology.hl7.org/CodeSystem/medicationrequest-category: Not loaded
http://hl7.org/fhir/us/core/CodeSystem/us-core-tags: Not loaded
http://hl7.org/fhir/questionnaire-answers-status: Not loaded

**Comment by javacup** [comment]
btw both these tests matched the expected results as documented in the Readme 

bundle exec rake "terminology:check_code[91935009,http://snomed.info/sct, http://hl7.org/fhir/us/core/ValueSet/us-core-allergy-substance]"

http://snomed.info/sct|91935009 is in http://snomed.info/sct

but 

 bundle exec rake terminology:check_built_terminology

came back with 

Terminology build results different than expected.
http://hl7.org/fhir/us/core/ValueSet/us-core-careteam-provider-roles: Expected codes: 1731 Actual codes: 1731
http://hl7.org/fhir/us/core/ValueSet/us-core-condition-category: Expected codes: 4 Actual codes: 3
http://hl7.org/fhir/us/core/ValueSet/us-core-condition-code: Expected codes: 297482 Actual codes: 297182
http://hl7.org/fhir/us/core/ValueSet/us-core-diagnosticreport-report-and-note-codes: Expected codes: 24810 Actual codes: 270991
http://hl7.org/fhir/ValueSet/security-labels: Expected codes: 200 Actual codes: 200
http://hl7.org/fhir/us/core/ValueSet/us-core-usps-state: Expected codes: 62 Actual codes: 59
http://hl7.org/fhir/us/core/ValueSet/omb-race-category: Expected codes: 8 Actual codes: 7
http://hl7.org/fhir/us/core/ValueSet/detailed-race: Expected codes: 919 Actual codes: 917
http://hl7.org/fhir/us/core/ValueSet/omb-ethnicity-category: Expected codes: 4 Actual codes: 2
http://hl7.org/fhir/us/core/ValueSet/detailed-ethnicity: Expected codes: 44 Actual codes: 42
http://hl7.org/fhir/us/core/ValueSet/birthsex: Expected codes: 5 Actual codes: 3
http://hl7.org/fhir/us/core/ValueSet/us-core-provider-role: Expected codes: 862 Actual codes: 237
http://hl7.org/fhir/us/core/ValueSet/us-core-provider-specialty: Expected codes: 862 Actual codes: 862
http://hl7.org/fhir/us/core/ValueSet/us-core-procedure-code: Expected codes: 556515 Actual codes: 285523
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1186.8: Expected codes: 766 Actual codes: 0
http://hl7.org/fhir/ValueSet/narrative-status: Expected codes: 4 Actual codes: 0
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1099.30: Expected codes: 590 Actual codes: 0
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1010.6: Expected codes: 196 Actual codes: 0
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1010.4: Expected codes: 1000 Actual codes: 0
http://hl7.org/fhir/ValueSet/medicationrequest-category: Expected codes: 4 Actual codes: 0
http://hl7.org/fhir/us/core/ValueSet/us-core-vital-signs: Expected codes: 19 Actual codes: 0
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.11.20.9.38: Expected codes: 8 Actual codes: 0
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.114222.4.11.1066: Expected codes: 856 Actual codes: 0
http://hl7.org/fhir/ValueSet/resource-types: Expected codes: 148 Actual codes: 0
http://hl7.org/fhir/ValueSet/condition-category: Expected codes: 2 Actual codes: 0
http://hl7.org/fhir/us/core/ValueSet/us-core-problem-or-health-concern: Expected codes: 2 Actual codes: 0
http://hl7.org/fhir/us/core/ValueSet/us-core-goal-description: Expected codes: 760133 Actual codes: 0
http://hl7.org/fhir/us/core/ValueSet/us-core-common-sdoh-assessments: Expected codes: 47 Actual codes: 0
http://hl7.org/fhir/us/core/ValueSet/us-core-sexual-orientation: Expected codes: 6 Actual codes: 0
http://hl7.org/fhir/us/core/ValueSet/us-core-survey-codes: Expected codes: 11120 Actual codes: 0
http://hl7.org/fhir/us/core/ValueSet/us-core-clinical-test-codes: Expected codes: 461 Actual codes: 0
http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1021.32: Expected codes: 7 Actual codes: 0
http://hl7.org/fhir/us/core/ValueSet/us-core-tags: Expected codes: 1 Actual codes: 0
http://hl7.org/fhir/ValueSet/questionnaire-answers-status: Expected codes: 5 Actual codes: 0
http://hl7.org/fhir/ValueSet/relatedperson-relationshiptype: Expected codes: 117 Actual codes: 0
http://hl7.org/fhir/ValueSet/request-intent: Expected codes: 9 Actual codes: 0
http://hl7.org/fhir/us/core/ValueSet/us-core-servicerequest-category: Expected codes: 8 Actual codes: 0
urn:oid:2.16.840.1.113883.6.101: Expected codes: 970 Actual codes: 0
http://terminology.hl7.org/CodeSystem/v3-Confidentiality: Expected codes: 20 Actual codes: 0
http://terminology.hl7.org/CodeSystem/v3-ObservationValue: Expected codes: 250 Actual codes: 0
https://www.usps.com/: Expected codes: 62 Actual codes: 59
http://www.cms.gov/Medicare/Coding/HCPCSReleaseCodeSets: Expected codes: 7783 Actual codes: 0
http://www.ada.org/cdt: Expected codes: 867 Actual codes: 0
http://ada.org/cdt: Expected codes: 867 Actual codes: 0
http://terminology.hl7.org/CodeSystem/v3-ParticipationFunction: Expected codes: 49 Actual codes: 0
http://terminology.hl7.org/CodeSystem/medicationrequest-category: Expected codes: 4 Actual codes: 0
http://hl7.org/fhir/us/core/CodeSystem/us-core-tags: Expected codes: 1 Actual codes: 0
http://hl7.org/fhir/questionnaire-answers-status: Expected codes: 5 Actual codes: 0

**Comment by jpdow02** [comment]
I’ve spent about 12 hours trying everything people have suggested. I’ve installed vocabularies 4 times now with the exact same results as described in this open bug report. Odd thing is I can pass all the tests using the Inferno reference server ( using default IG versions).  Seems if the 32 reported vocab that did not get loaded that the tests would not pass. Jim

**Comment by jpdow02** [comment]
@javacup  I found that this issue is just because the startup of Inferno is not yet complete.  I'm also using AWS and Linux2.  This could be slowness inherant with that deployment.  Just wait until no more messages are being output to the Linux console:

Unable to connect to Validator: Failed to open TCP connection to validator_service:4567 (Connection refused - connect(2) for "validator_service" port 4567)

I get all the exact same errors you get elsewhere.  It is just so curious to me that running Inferno 3.01 using the Inferno Reference Server, everything passes.  Probably, luck-of-the-draw that the patient has vocabs that are all present:

![image](https://user-images.githubusercontent.com/108231455/188242808-7a2eece9-a1c9-4be2-9657-6eded1e3f9b4.png)

![image](https://user-images.githubusercontent.com/108231455/188242855-274b9aeb-16a0-4756-9569-1cf43f249b5a.png)

**Comment by Jammjammjamm** [comment]
> I found that this issue is just because the startup of Inferno is not yet complete. I'm also using AWS and Linux2. This could be slowness inherant with that deployment. Just wait until no more messages are being output to the Linux console:
 Unable to connect to Validator: Failed to open TCP connection to validator_service:4567 (Connection refused - connect(2) for "validator_service" port 4567)

That is correct. Since US Core 4 & 5 are now supported, the validator has to load them as well. Those IGs both contain some very large dependencies which causes them to load much more slowly than US Core 3, which means the validator takes longer to start.

Once the validator service is running, you can make the g10 suite recheck its configuration by making a `PUT` request to `/api/test_suites/g10_certification/check_configuration`. That will get rid of the validator message.

**Comment by Jammjammjamm** [comment]
> The Configuration messages tab is now showing 2 messages. The 2nd message has some entries with matching counts.. but reported as an error message like the first one Expected codes: 1731 Actual codes: 1731

Could you post a copy of your `resources/terminology/validators/bloom/manifest.yml` here?

**Comment by jpdow02** [comment]
@Jammjammjamm   Mine is a little different than @javacup.  In addition to mismatch counts, I have about 33 vocabularies that it says have 0 counts.  I've uploaded my manifest.yml. Thank you for looking at this - Jim
[manifest.yml.txt](https://github.com/onc-healthit/onc-certification-g10-test-kit/files/9497350/manifest.yml.txt)

**Comment by jpdow02** [comment]
I will rebuild the terminology and send you the log - Jim

**Comment by javacup** [comment]
@jpdow02  thank you for sharing your output.  It seems strange that we are getting different results. 

Currently this is the state 

![Screen Shot 2022-09-06 at 9 59 56 AM](https://user-images.githubusercontent.com/397774/188696484-286f84a0-bc94-4d06-9e48-fd6c5cb61c1a.png)

**Comment by jpdow02** [comment]
@Jammjammjamm Hi, I removed my tmp/terminoloy/* folders to force a re-download.  I ran the "sudo docker-compose -f terminology_compose.yml up" with output to terminology_compose.log file.  Attached are:

1. Inferno configuration error screen shot after rebuild.
2.  terminology_compose.log
3. manifest.yml

Let me know if I should upload anything else that might help.  Thanks - Jim
<img width="461" alt="Inferno Configuration Error Screen" src="https://user-images.githubusercontent.com/108231455/188725180-ec477ee5
[terminology_compose.log](https://github.com/onc-healthit/onc-certification-g10-test-kit/files/9500245/terminology_compose.log)
-c296-4879-9d54-81b4d373eac1.PNG">
[manifest.yml.txt](https://github.com/onc-healthit/onc-certification-g10-test-kit/files/9500247/manifest.yml.txt)

**Comment by jpdow02** [comment]
[terminology_compose.txt.log](https://github.com/onc-healthit/onc-certification-g10-test-kit/files/9500252/terminology_compose.txt.log)

**Comment by Jammjammjamm** [comment]
That is correct. I'll update our documentation to be more clear.

**Comment by jpdow02** [comment]
Thank you, Stephen.

I will go through those steps and let you know the results.

Jim

**Comment by jpdow02** [comment]
@Jammjammjamm   I did the "sudo docker-compose -f terminology_compose.yml build", but I'm curious as to why it looks like I still have a manifest file from 2 days ago I attached an image:


![image](https://user-images.githubusercontent.com/108231455/189181433-8b77b5b2-1d7a-4edb-9b88-b7ce81bf0a61.png)

Should I start again from scratch...deleting my Git repository and then doing a fresh clone?

Jim

**Comment by jpdow02** [comment]
@Jammjammjamm  My issue is resolved.   I was not able to duplicate it; however, this is what I did differently:

- I downloaded the official tar file release: before I had installed using "git clone"
- I stuck with the standard SQLite install: before I had tried to upgrade to Progress db

No configuration errors.  Thanks for helping me focus on the right steps.  -Jim

**Comment by yashpalk** [comment]
Just chiming in since I was also running into the same issue. I was able to resolve it while still using git with the following steps. Not sure what specifically did the trick, but in case others are also having issues:

```bash
# Clear existing validator resources
rm -rf resources/terminology/validators/

# Clear terminology downloads
rm -rf tmp/terminology/

# Update the .env file to not cleanup build files after each version.
# The terminology build was errorering out after 2019 without this.
# CLEANUP=false

# Start a new terminology build
docker-compose -f terminology_compose.yml up --build

# Build 2021 resources manually
docker-compose -f terminology_compose.yml run terminology_builder bin/prepare_terminology.sh 2021
docker-compose -f terminology_compose.yml run terminology_builder bundle exec rake terminology:create_vs_validators["preferred","2021","false"]
```

**Comment by yunwwang** [comment]
@javacup @jpdow02 @yashpalk 

We published a new terminology build process with v3.2.0. Could you verify if the new process works in your testing environment?

Thank you

~ Yunwei

**Comment by jpdow02** [comment]
I did a full install today on our AWS Linux2 server. New process worked
first time with no issues. For me, vocabulary process dropped from 5.5
hours in the 3.1.0 install to 1. 5 hours with the 3.2.0 install.

Nice job on this!

Jim

**Comment by yashpalk** [comment]
Also worked for me, thanks for the fix! Had to clear the old validator resources and terminology downloads, but that was because we're using git
