### ISSUE TITLE
4.0.0 - 5.14.01 & 5.14.02 Observation Laboratory Results Searching for Vital Signs

### ISSUE THREAD

**Issue by jj027509** [onc-healthit/onc-certification-g10-test-kit#244]
We are seeing failures on 5.14.01 and 5.14.02 within 4.0.0 It appears that Observation Laboratory Results is searching for vital signs. 

Test run: https://inferno.healthit.gov/suites/test_sessions/bd865c39-bf1d-4abc-a234-42ed05c964b5#g10_certification-g10_single_patient_us_core_4_api

On an older dev test, no vitals sign search was being performed: https://inferno-dev.healthit.gov/suites/test_sessions/8005da77-a1ac-4f5a-8b0d-9a9a508a1c6e#g10_certification-g10_single_patient_us_core_4_api

**Comment by yunwwang** [comment]
@jj027509 

Here is the problem. When inferno build queries for the search with code+system, inferno uses the result returned from search with code to build the new query.

The resource returned from search with code contains two categories, as shown in the screen shot. Inferno picks the first one, which is `vital-signs` to form the code+system search.

The reason that the same test passed on dev is that the resource returned there has only one category `laboratory`.

I think there are some improvement we can do. At same time, you can either remove the `vital-sign` category or move it after the category `laboratory`. Inferno should pass that.


<img width="688" alt="image" src="https://user-images.githubusercontent.com/8761175/187814182-ea83dc78-c33f-412c-8604-1e7dc39f53ea.png">

**Comment by jj027509** [comment]
Thank you for the explanation. We were able to remove the result which was causing vital-signs to return here. I will close this issue.
