### ISSUE TITLE
Inconsistent results between SinglePatientAPI and MultiPatient API (FI-1704)

### ISSUE THREAD

**Issue by mcopelli** [onc-healthit/onc-certification-g10-test-kit#245]
I am seeing issues where my Allergy Intolerance items pass US Core on the single patient API but then fail the Multi-Patient API. I am attempting to target US Core 3.1.1. 

This also applies to other items as well.

**Comment by yunwwang** [comment]
Can you provide more details, such as the error message on Multi-Patient test? Thanks

**Comment by mcopelli** [comment]
Here is my session details. I'm not sure what else I should provide.
https://inferno.healthit.gov/suites/test_sessions/163df2d5-773c-465f-9f67-4a75a67587b9
If you look at the allergy items from the single patient they pass. The mutli patient complains about a few things like severity code that the single patient does not.

**Comment by yunwwang** [comment]
I found that the AllergyIntolerance/371 contains JSON element with empty value like 
![image](https://user-images.githubusercontent.com/8761175/187941891-5f7cf158-09ee-4374-b652-5d13049aaf77.png)

This is not allowed in FHIR. (http://hl7.org/fhir/R4/json.html)

We will further investigate why Inferno Single Patient API does not catch that error.

**Comment by mcopelli** [comment]
I am also seeing similar behavior on the DocumentReference and Device tests.

**Comment by yunwwang** [comment]
Removing the empty value (as mentioned above) should pass the MultiPatient API.

We are still investigate how to fix the issue in the SinglePatient API so it could catch this invalid FHIR JSON there.

**Comment by Jammjammjamm** [comment]
This is addressed by the following PR in inferno core: https://github.com/inferno-framework/inferno-core/pull/255
