### ISSUE TITLE
Cannot run docker-compose for terminology due to missing signature

### ISSUE THREAD

**Issue by MartinChavezNC** [onc-healthit/onc-certification-g10-test-kit#249]
I am following the [instructions](https://github.com/onc-healthit/onc-certification-g10-test-kit) to run the terminology server, however, once I run:

```docker-compose -f terminology_compose.yml up```

I get the following error:

<img width="1085" alt="Screen Shot 2022-09-02 at 2 56 01 PM" src="https://user-images.githubusercontent.com/72049707/188240206-92be7281-b350-4f4e-b5c3-70aa4ba9e37f.png">

**Comment by MartinChavezNC** [comment]
Any ideas @Jammjammjamm ?

**Comment by Jammjammjamm** [comment]
It looks like there was an error downloading the zip file. Delete `tmp/terminology` and try again.

**Comment by MartinChavezNC** [comment]
I believe I am able to complete the ```docker-compose -f terminology_compose.yml up``` step, had to manually download the zip files. 

I am now able to spot-check the terminology files:
<img width="887" alt="spot_check" src="https://user-images.githubusercontent.com/72049707/189162162-75b92410-1867-4521-b78e-b8522c53cc6c.png">

**I am unable to connect inferno to the validator service**:
<img width="1505" alt="unable_connect" src="https://user-images.githubusercontent.com/72049707/189162379-a29b3ea4-c761-49e3-ac27-f659c216c8dc.png">

The docker containers seem to be running as expected:
![docker](https://user-images.githubusercontent.com/72049707/189162675-c4bdf165-2775-4f81-ac2d-077fa40cea0c.png)

@Jammjammjamm , any ideas on what could be missing?

**Comment by Jammjammjamm** [comment]
Basically, you're loading inferno before the validator has finished starting. There are some more details here: https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/243#issuecomment-1238113517

**Comment by MartinChavezNC** [comment]
ok, that HTTP POST worked. Lastly, I am stuck on the 'Expected codes' issue:
<img width="1369" alt="Screen Shot 2022-09-08 at 10 06 40 AM" src="https://user-images.githubusercontent.com/72049707/189183308-196d5893-7134-4781-9a62-fc086c49322e.png">

I ran the prepare_terminalogy script for 2021:
![prepare](https://user-images.githubusercontent.com/72049707/189183617-6211dc72-c59b-462e-892a-844b5307f36b.png)

which was completed successfully. However, when I run:
`docker-compose -f terminology_compose.yml run terminology_builder bundle exec rake terminology:create_vs_validators\["preferred","2021","false"\]`

I get a missing table error:

![missing_table](https://user-images.githubusercontent.com/72049707/189184177-d956ab83-5d5b-4c33-a06b-542563758548.png)

**Comment by Jammjammjamm** [comment]
It looks like that step didn't actually finish successfully if that table is missing. You should remove `tmp/terminology/2021` (or everything in there except the zip file) and try again.

It seems like you have a local ruby environment set up, so you could try running everything outside of docker.

**Comment by MartinChavezNC** [comment]
I realized I didn't run :
`docker-compose -f terminology_compose.yml run terminology_builder bin/prepare_terminology.sh 2021`
Now, the **mrrel** table gets created, however, after I run:
`docker-compose -f terminology_compose.yml run terminology_builder bundle exec rake terminology:create_vs_validators\["preferred","2021","false"\]`

it exits, without any error:

<img width="632" alt="processing" src="https://user-images.githubusercontent.com/72049707/189225330-0f936d22-e2c0-429a-adf6-7aa3f55c68a2.png">

Unfortunately, the issue of the missing code still remains, even after running:

`bash run.sh`

**Comment by MartinChavezNC** [comment]
@Jammjammjamm , after so much trial and error, I got it working, I can summarize the issues into the following:

- Downloading the zip files fails (following README instructions), you need to manually download them and place them into the tmp folder
- The `docker-compose -f terminology_compose.yml up` command **does not** run for 2021
- Need to run the two commands from my previous comment (prepare_terminology and terminology:create_vs_validators) for 2021

**Note: Be careful to download the specific versions:**
I was using **umls-2021AB-full.zip**, and got the check errors from [Issue 243](https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/243)

![image](https://user-images.githubusercontent.com/72049707/189423148-dfd9a6a6-e0b2-4084-a642-5e179194082f.png)

FYI - @jpdow02 and @javacup, as I believe you are facing similar issues on [Issue 243](https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/243)
