### ISSUE TITLE
Getting Error "No Observation resources found that conform to profile: http://hl7.org/fhir/us/core/StructureDefinition/us-core-smokingstatus."

### ISSUE THREAD

**Issue by CreativeConsultingServices** [onc-healthit/onc-certification-g10-test-kit#250]
[SMOK01-39076.txt](https://github.com/onc-healthit/onc-certification-g10-test-kit/files/9482760/SMOK01-39076.txt)
[SMOK01-43.txt](https://github.com/onc-healthit/onc-certification-g10-test-kit/files/9482761/SMOK01-43.txt)
Hi,

We are getting error "No Observation resources found that conform to profile: http://hl7.org/fhir/us/core/StructureDefinition/us-core-smokingstatus." for Observation Resource.

Attached are the responses that are failing.

**Comment by yunwwang** [comment]
Is this for US core 4.0?

**Comment by CreativeConsultingServices** [comment]
This is for STU 3.1.1

**Comment by yunwwang** [comment]
These two resources looks correct. What is the detailed error message of test 4.14.04?

Do you have the url of your test session? You can either post it here or you can send me to my email (yunweiw@mitre.org). 

Thanks.

**Comment by CreativeConsultingServices** [comment]
https://inferno.healthit.gov/suites/test_sessions/1e6489b1-2643-42b5-a528-c04ec0d98f31#g10_certification-multi_patient_api

**Comment by yunwwang** [comment]
I think the problem is related to this setting for bulk data export:
![image](https://user-images.githubusercontent.com/8761175/188649477-40d4bc89-9cfa-4ff8-a4ea-c557ee2dcf25.png)

This instruct Inferno to only validate the first 5 Observation resources and skip the rest lines in the NDJSON files

**Comment by CreativeConsultingServices** [comment]
Thanks, let us verify by changing this setting.

**Comment by CreativeConsultingServices** [comment]
Its working now. Thanks @yunwwang for a response.
