### ISSUE TITLE
Single Patient API calling issue

### ISSUE THREAD

**Issue by CreativeConsultingServices** [onc-healthit/onc-certification-g10-test-kit#251]
DocumentReference 4.10.04 - Passing %2B instead of + in datatimeoffset
Procedure - 4.26.02 - Passing %2B instead of + in datatimeoffset

https://inferno.healthit.gov/suites/test_sessions/9a5eeecf-cf1e-4c91-a435-822f9c8baeab#g10_certification-g10_single_patient_api

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/12527606/188318616-e4394f25-8341-4859-b25a-3bee20724793.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/12527606/188318617-095c1a52-6f58-47b8-8e97-d638a2b56608.png)

**Comment by yunwwang** [comment]
`%2B` is url encoded for ASCII character `+`. Please see
https://www.w3schools.com/tags/ref_urlencode.ASP
