### ISSUE TITLE
wrong `context-ehr-patient` requirement (FI-1707)

### ISSUE THREAD

**Issue by ddegr** [onc-healthit/onc-certification-g10-test-kit#254]
### Definintion of the problem
Inferno started throws error `The following capabilities required for this scenario are missing: context-ehr-encounter` in the `3 EHR Practitioner App` sequence.

Our solutions uses `SMART on FHIR v1` and it doesn't support `launch/encounter` scope. That is why there is no `context-ehr-encounter` in the capability statement.

[ONC says](https://www.healthit.gov/test-method/standardized-api-patient-and-population-services#ccg)

> Since "Encounter" is not a USCDI v1 data class or data element, ONC will not test Health IT Modules for support for "context-ehr-encounter" SMART on FHIR® Core Capabilities described in the standard adopted at § 170.215(a)(3).

### The desired behavior
Inferno doesn't make it compulsary to have `context-ehr-encounter` in the `SMART on FHIR` v1 app launch.

**Comment by Jammjammjamm** [comment]
We will address this issue. `context-ehr-encounter` should only required when using US Core 5.

**Comment by ddegr** [comment]
The problem seems to be solved. Thanks

**Comment by Jammjammjamm** [comment]
We will leave this issue open until we do a realease which includes the fix.
