### ISSUE TITLE
Error: 783: unexpected token in Inferno (FI-1730)

### ISSUE THREAD

**Issue by madhavdarji** [onc-healthit/onc-certification-g10-test-kit#275]
We are seeing below error while running bulk data test.

7.2.05 Bulk Data Server returns "202 Accepted" or "200 OK" for status check
Error: 783: unexpected token at ''

/usr/local/lib/ruby/2.7.0/json/common.rb:156:in `parse'

What is error on the server side that would cause this error?

**Comment by Jammjammjamm** [comment]
It means that the response body was not valid json.

**Comment by yunwwang** [comment]
When server finishes export job, server returns status 200 with a JSON payload of file locations. The error means the JSON file is not valid. Most possible reason is that the JSON file has extra "invisible" control characters at the end of the file. We had a similar issue reported, see blow. It may give you some hint of where to look at.

https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/232

**Comment by arscan** [comment]
We should catch the parsing error and display a better error message, I think.  Especially since the test name doesn't indicate it is looking at the response body too.
