### ISSUE TITLE
Request: Follow redirects on _search post requests

### ISSUE THREAD

**Issue by SavannahDearing** [onc-healthit/onc-certification-g10-test-kit#276]
For all **Single Patient API** tests for **4.2.01, 4.3.01 etc**, we are succeeding on Get _id requests, but failing on Post _search _id requests with 302.

Based on issues before, seems that the Get is following redirects, but the Post is not

**Comment by SavannahDearing** [comment]
Hi,
I re-tested this with Postman and found a few problems that have been fixed, but the Inferno test is still reporting 302 errors:
https://inferno.healthit.gov/suites/test_sessions/0308b68b-579e-40df-bcb3-2681790481ed

**Comment by yunwwang** [comment]
@SavannahDearing Since server returned 302, does the server want client to redirect the request as http GET?

**Comment by SavannahDearing** [comment]
Hi,
Coming back to this one after fixing another redirect issue.  Been on/off trying to find a solution for this.

This is our base url:
https://www.medentfhirtest.com/fhir/R4/savcw237

For GET requests this redirects to:
https://www.medentfhirtest.com/fhir/R4/Patient.php?medent_practice_id=savcw237

For POST request:
https://www.medentfhirtest.com/fhir/R4/savcw237/Patient/_search
needs to also redirect:
/fhir/R4/Patient.php?medent_practice_id=savcw237

I'm not seeing an alternate way to do this.. like defining a search endpoint with a tenant parameter..?
My other redirect issue [with Delete] was fixed by defining a URL with the parameter included.  I was hoping to find a way to do this in the CapabilityStatement, but that doesn't seem possible.

I think all this is to say

> @SavannahDearing Since server returned 302, does the server want client to redirect the request as http GET?

Yes, I think this is the only solution for a multi-tenant server.  I'm willing to listen to other ideas but currently I cant think of an alternative

**Comment by SavannahDearing** [comment]
After much discussion:
https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Multi-Tenant.20FHIR.20Server/near/307818291

we implemented Reverse Proxy in order to "re-direct" things internally, such that no changes to Inferno need to be made.  Closing but leaving comments for others, the thread above was very helpful and full of other suggestions for multi tenant servers.
