### ISSUE TITLE
Can we change inferno redirect_uri: Oauth2 server doesn't support localhost in Inferno redirect_uri

### ISSUE THREAD

**Issue by sjayswal** [onc-healthit/onc-certification-g10-test-kit#277]
Hello,

We are trying to redirect to inferno after Oauth2 authentication. However,  Oauth2 server doesn't support "localhost" in redirect_uri. 

1. Can we change the redirect_uri of inferno ? 
2. Can we change the localhost to 127.0.0.1 in inferno redirect_uri ? 

Kindly provide your valuable inputs on this. 

Thank you.

**Comment by Jammjammjamm** [comment]
Change the value of `INFERNO_HOST` in `.env`, or use some other method to set the `INFERNO_HOST` environment variable.

https://github.com/onc-healthit/onc-certification-g10-test-kit/blob/main/.env#L2
