### ISSUE TITLE
HealthIT.gov instance of Inferno is down

### ISSUE THREAD

**Issue by BobCardillo** [onc-healthit/onc-certification-g10-test-kit#286]
We're getting 500s and errors like:
> PG::ConnectionBad: could not translate host name \"inferno_db\" to address: Name or service not known\n
from https://inferno.healthit.gov/suites/api/test_runs

and
> Internal Server Error
from https://inferno.healthit.gov/suites/api/test_runs/undefined?include_results=true

**Comment by Jammjammjamm** [comment]
Should be back to normal now.
