### ISSUE TITLE
Error: undefined method `source_text=' for nil:NilClass"

### ISSUE THREAD

**Issue by gsambasiva** [onc-healthit/onc-certification-g10-test-kit#293]
We are using Inferno 3.0.1 Version for our Single API testing.

We are getting the following internal Inferno error which is not understandable by our dev team.
It would be much appreciated if any advice/clue on this error to fix by our dev team.
4.16.04 Server returns correct Observation resource from Observation read interaction
Error: undefined method `source_text=' for [nil:NilClass](url)
/usr/local/bundle/gems/us_core_test_kit-0.3.1/lib/us_core_test_kit/ext/fhir_models.rb:30:in `from_json'

[Observation_Lab.txt](https://github.com/onc-healthit/onc-certification-g10-test-kit/files/9718456/Observation_Lab.txt)

Please let us know if any further inputs needed from our end. We attached both error details and the actual output of this specific Observation (Lab) Resource Response.

Attached Inferno error test Image for referecne

![Observation_Lab_Undefined_method_Source_text_Error (1)](https://user-images.githubusercontent.com/22830714/194149794-4faa45c1-b24a-4dd6-a74d-2e01ef3139e6.png)

**Comment by yunwwang** [comment]
The `resourceType` is not correct. It should be `Observation`

<img width="369" alt="image" src="https://user-images.githubusercontent.com/8761175/194191976-9bb2158a-1117-42c8-b394-295c0fe84d2e.png">
