### ISSUE TITLE
Updated Wiki Documentation (FI-1716)

### ISSUE THREAD

**Issue by dhit-mdavis** [onc-healthit/onc-certification-g10-test-kit#296]
I've been exploring the Inferno site and the github page to better understand all the helpful details that you all provide.

I came across the wiki and was happy to see this as a source of info to provide to other, less experienced users.
https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki/Walkthrough

Can the wiki be updated to reflect the new tests and new tests numbering?

Thank you

**Comment by yunwwang** [comment]
That is on our backlog. We will update the walkthrough.

**Comment by arscan** [comment]
Hi @dhit-mdavis -- thanks for the suggestion.  I just updated the [walkthrough](https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki/Walkthrough) for the latest version of the (g)(10) tests.  We'll try to do better to keep this up to date!
