### ISSUE TITLE
Test Numbering

### ISSUE THREAD

**Issue by dhit-mdavis** [onc-healthit/onc-certification-g10-test-kit#297]
Hi there.

Is there any explicit reason for the test numbering going from sequential order to the latest order?

**Previously** the order was 1,2,3,4,5,6

**Now** it's, 1,2,3,4,7,9.

![image](https://user-images.githubusercontent.com/56314435/194723155-d7c2af57-403d-43b8-b5cf-de19f03a5f2e.png)

Thank you

**Comment by yunwwang** [comment]
Inferno reassigned group number due to the recent SVAP update:
Group 5: Single Patient API for US Core v4.0.0
Group 6: Single Patient API for US Core v5.0.1
Group 8: Multi Patient API for Bulk Data v2.0.0

**Comment by dhit-mdavis** [comment]
Interesting. Okay, this is helpful. I can echo this to clients.
