### ISSUE TITLE
(g)(10) Certification US Core 5.0.1 Inferno Reference Server Errors

### ISSUE THREAD

**Issue by skaranfilovski** [onc-healthit/onc-certification-g10-test-kit#300]
Hello there,

In this test run https://inferno.healthit.gov/suites/test_sessions/f2dd3a69-4770-412e-bcbf-d024b1456af0#g10_certification we are executing the Inferno tests for Standalone Patient App and Single Patient API (US Core 5.0.1) against the Inferno Reference Server and there are a lot of resources that have errors or are skipped. We are using the default selections and inputs when running the tests.

I noticed that there is already an open issue for the ServiceRequest related errors (https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/287) so those should be covered with that one, but there are many more unrelated to that. Until recently we worked on certification for US Core 3.1.1 and the Inferno tests against the Reference Server were all passing.

We also tried the same run on the Inferno dev instance, but we got the same output https://inferno-dev.healthit.gov/suites/test_sessions/f3f50641-3eef-4cee-84f3-231784b99099#g10_certification.

Is this behavior expected for US Core 5.0.1 or are we doing something wrong?

Thanks.

**Comment by Jammjammjamm** [comment]
The reference server does not support US Core 4 or 5 yet.

**Comment by skaranfilovski** [comment]
Is there a rough timeframe for when that would be added?

**Comment by yunwwang** [comment]
We don't have a timeline yet. We are working on updating Inferno demo server to US Core v4.0.0.
