### ISSUE TITLE
Issue in encounter type code

### ISSUE THREAD

**Issue by varshini39** [onc-healthit/onc-certification-g10-test-kit#301]
Recently after the tool was updated to v.0.3.2, there is an issue in encounter type, where one of the snomed codes isn't getting passed.

Here is the "**type**" value for encounter:
`"type": [
          {
            "coding": [
              {
                "system": "http://snomed.info/sct",
                "code": "453701000124103",
                "display": "In-person encounter"
              }
            ],
            "text": "In-person encounter"
          }
        ],`

For this, I'm getting the error as below:
![image](https://user-images.githubusercontent.com/14819986/195838534-68070e45-dc50-488e-a98a-87cdde157bdd.png)

I have also verified with the latest snomed codes, that this code "**453701000124103**" is valid one and this issue occurred only after  the tool got updated to v.0.3.2 and not in previous version.

Please look into this and let us know.

**Comment by Jammjammjamm** [comment]
Is then when running the g10 suite or the US Core suite?

**Comment by varshini39** [comment]
> Is then when running the g10 suite or the US Core suite?

This error occurs in both view.

**Comment by Jammjammjamm** [comment]
Could you provide me with a link to test session where this is occurring in the g10 suite?

**Comment by varshini39** [comment]
> Could you provide me with a link to test session where this is occurring in the g10 suite?

Here is the link for US core v3.1.1, where we are facing this issue. 
https://inferno.healthit.gov/suites/test_sessions/a45ddd43-566a-45ec-b75d-cc61f302fece#us_core_v311-us_core_v311_encounter

**Comment by yunwwang** [comment]
US Core test kit uses the tx.fhir.org to do the validation. Running this query on tx.fhir.org (http://tx.fhir.org/r4/ValueSet/$validate-code?code=453701000124103&system=http://snomed.info/sct) returns the same error. 

That terminology server is not maintained by Inferno team. It could be that server does not have the latest SNOMED CT.

If you are confident the code is correct, then you can ignore that terminology error.

**Comment by varshini39** [comment]
> Running this query on tx.fhir.org (http://tx.fhir.org/r4/CodeSystem/$validate-code?code=453701000124103&system=http://snomed.info/sct) returns the same error.

So is this code not valid anymore?

**Comment by yunwwang** [comment]
What do you mean "local setup"?

It could be the server does not have the latest SNOME CT update.

**Comment by varshini39** [comment]
> What do you mean "local setup"?
> 
> The code is valid. It could be the server does not have the latest SNOME CT update.

I have downloaded the test kit from this [https://github.com/onc-healthit/onc-certification-g10-test-kit/releases](link) and running it in my machine. I didn't get this issue in that, but I'm getting the error in live.
