### ISSUE TITLE
How to configure SSL certificate in FHIR server which can listen from inferno without SSL certificate error

### ISSUE THREAD

**Issue by sjayswal** [onc-healthit/onc-certification-g10-test-kit#303]
Hello, 

Our HAPI-Server & Auth Server is on SSL. 
Inferno is running on ip-address. We haven't bind any SSL to it. 

We are getting below given error while executing test cases from inferno. 

Error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

/usr/local/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock'

**Comment by Jammjammjamm** [comment]
Are you using self-signed certs?

**Comment by sjayswal** [comment]
@Jammjammjamm No,  we are not using selg-signed certs.

**Comment by Jammjammjamm** [comment]
That error is indicates that Inferno is unable to verify the certificate of the server it is connecting to. It isn't related to whether Inferno itself is being served over https.

**Comment by sjayswal** [comment]
@Jammjammjamm ,

Hello,

How we can identify which certificate inferno getting from our FHIR server. Actually we are not able to find out which certificate inferno is listening to.

**Comment by Jammjammjamm** [comment]
I don't know, you'll have to google that.
