### ISSUE TITLE
How to execute 9.10 Visual Inspection and Attestation Test cases on Inferno ?

### ISSUE THREAD

**Issue by sjayswal** [onc-healthit/onc-certification-g10-test-kit#304]
Hello, 

Can you please brief us about the process of  **9.10 Visual Inspection and Attestation** test case on inferno testing tool.

**Comment by yunwwang** [comment]
Those are the requirements that Inferno could not test automatically. You need to talk to your proctor to figure out how to test those items.

**Comment by sjayswal** [comment]
@yunwwang , Thank you for quick response. We will communicate further with our proctor.
