### ISSUE TITLE
Issue in patient resource validation

### ISSUE THREAD

**Issue by naveensahukari** [onc-healthit/onc-certification-g10-test-kit#308]
The patient resource validation tests are getting failed in US core suite, while the same patient validation tests are passed in the g10 suite.

Here is the screenshot of US Core suite from Inferno test data.
![image](https://user-images.githubusercontent.com/116081575/196581013-b9c6b882-268a-4c40-a45d-19595e294dfb.png)

Session link for above screenshot : https://inferno.healthit.gov/suites/test_sessions/fa666476-55cb-4dd2-859b-4960995143c5#us_core_v311-us_core_v311_patient

Here is the screenshot of g10 suite from inferno test data.
![image](https://user-images.githubusercontent.com/116081575/196581369-24b40766-6032-4f6e-8238-29e154ece604.png)

Session link for above screenshot : https://inferno.healthit.gov/suites/test_sessions/8ac14959-0a64-423c-aaaa-f29bbfd7bf3c#g10_certification-g10_single_patient_api

The same patient tests are failed when I run the tests against our server data. Please check the session link below.
https://inferno.healthit.gov/suites/test_sessions/39a7fc7d-69fd-4d53-9dd4-aa8717719b46#us_core_v311-us_core_v311_patient

**Comment by yunwwang** [comment]
Please check this FAQ: https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki/FAQ#q-why-some-resources-failed-in-us-core-test-kit-with-terminology-validation-errors-but-passed-in-g10-test-kit
