### ISSUE TITLE
EHR Practitioner App

### ISSUE THREAD

**Issue by hemasatheesh** [onc-healthit/onc-certification-g10-test-kit#309]
the below link is not working in SMART App Launch 2.0.0

https://github.com/inferno-framework/inferno-core/

**Comment by arscan** [comment]
That is the repository for the inferno core library.  Could you explain what you are trying to accomplish?

I saw that you opened a few more tickets in the legacy repository (https://github.com/onc-healthit/inferno-program/issues/), and it sounds like you are having trouble with SMART App Launch 2.0?  Could you provide more details about what you are trying to accomplish?  Are you trying out the tests against our demonstration server (https://inferno.healthit.gov/reference-server/r4) to see how the tests work?  Or are you trying to test your own implementation?
