### ISSUE TITLE
Getting inconsistent response for some FHIR Resources in the Single Patient API test case

### ISSUE THREAD

**Issue by sjayswal** [onc-healthit/onc-certification-g10-test-kit#311]
Hello, 

We are trying to test the inferno test case no **4 Single Patient API**. And somewhere we aren't able to get the required output for below test cases. The response is inconsistent as it working sometime and giving us the desired output.  

**4.8.03 Server returns valid results for DiagnosticReport search by patient + category + date**
**4.10.04 Server returns valid results for DocumentReference search by patient + category + date**
**4.26.02 Server returns valid results for Procedure search by patient + date**

**These above test-cases are getting passed for the same data at one time and failed at another.** We have checked the FHIR Resource data for the same from our side and it is following the US Core Standards. 

Can you please suggest us something which might help us ? 

Thank you.

**Comment by yunwwang** [comment]
Can you provide more details:

Are you running using inferno.healthit.gov or your local installation?

If you use inferno.healthit.gov, do you have a url to your test session? If you don't want to post the url here, you can send to my email yunweiw@mitre.org.

If you don't have a public available session url, then

What is the failed message?

What are FHIR resource server returned?

**Comment by yunwwang** [comment]
I compared the urls from the passed test and failed test. They are the same. The server does not respond to the query consistently. 

Could you check why your server did not return any result for this query in some sessions?
[base]/DiagnosticReport?category=LP29684-5&date=2022-10-11T18:35:00Z&patient=781

**Comment by yunwwang** [comment]
@sjayswal I will close this issue. If you experience similar issue, you can either reopen this one or create a new issue. Thank you.
