### ISSUE TITLE
Inferno ignores the cardinality for must support fields

### ISSUE THREAD

**Issue by Nbhatin** [onc-healthit/onc-certification-g10-test-kit#312]
eg: address.period for patient profile

Our system doesnt have this information and since the cardinality of this must support field is 0-* , this field is not present in the fhir api response for all patients.

However, Inferno test fails and it requires address.period to be present. ideally, it should look if the cardinality is not 1-* then the test should not fail for the missing fields.

Fhir API response -
...
<img width="386" alt="image" src="https://user-images.githubusercontent.com/63259147/196996693-cd726a97-4512-488a-a02d-6ab33f6ff3d0.png">
---

Inferno screenshot-

<img width="708" alt="image" src="https://user-images.githubusercontent.com/63259147/196996889-9ac50e01-7203-454e-a36c-c18f73d45ed0.png">

Reference-
http://hl7.org/fhir/us/core/STU3.1.1/general-guidance.html#missing-data

1. If the source system does not have data for a Must Support data element, the data element is omitted from the resource.
2. If the source system does not have data for a required data element (in other words, where the minimum cardinality is > 0), use the [DataAbsentReason Extension](http://hl7.org/fhir/R4/extension-data-absent-reason.html), etc.

This is same case for all the data elements where it lies in must support category but cardinality is 0-*

**Comment by yunwwang** [comment]
Here is an FAQ for Must Support test: https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki/FAQ#q-how-does-inferno-test-mustsupport-flag-on-an-element

Please let me know if you have further questions.

**Comment by Nbhatin** [comment]
Thanks @yunwwang 

I went through the link you shared and the link refers to  http://hl7.org/fhir/us/core/STU3.1.1/general-guidance.html#must-support
which mentions-
![image](https://user-images.githubusercontent.com/63259147/196999737-b3f81cf9-3fc5-414f-b63f-43c1663fb012.png)


To which I assume, the elements with cardinality =0 may not be present

**Comment by yunwwang** [comment]
For optional element with MS label, it is not required that each resource must have a value for that element. It is required that the server shall be able to populate that value.

**Comment by Nbhatin** [comment]
Thanks @yunwwang  for the clarification.

**Comment by Nbhatin** [comment]
Based on http://hl7.org/fhir/us/core/STU3.1.1/general-guidance.html#missing-data
I tried adding dataAbsentReason extension to address.period and somehow Inferno still complaints.

Server response-
{
    "resourceType": "Patient",
    "id": "999013",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2022-10-20T19:22:48.101+00:00",
        "profile": [
            "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
        ]
    },
    "extension": [
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
            "extension": [
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "urn:oid:2.16.840.1.113883.6.238",
                        "code": "2106-3",
                        "display": "Black"
                    }
                },
                {
                    "url": "text",
                    "valueString": "Black"
                }
            ]
        },
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
            "extension": [
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "urn:oid:2.16.840.1.113883.6.238",
                        "code": "2186-5",
                        "display": "Not Hispanic or Latino"
                    }
                },
                {
                    "url": "text",
                    "valueString": "Not Hispanic or Latino"
                }
            ]
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
            "valueString": "Lorrie Murphy561"
        },
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
            "valueCode": "F"
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
            "valueAddress": {
                "city": "Berlin",
                "state": "Berlin",
                "country": "DE"
            }
        },
        {
            "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
            "valueDecimal": 24.285486783792628
        },
        {
            "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
            "valueDecimal": 58.71451321620737
        }
    ],
    "identifier": [
        {
            "system": "https://github.com/synthetichealth/synthea",
            "value": "cccfa08b-c57c-0670-9c37-d2975aebcd40"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "MR",
                        "display": "Medical Record Number"
                    }
                ],
                "text": "Medical Record Number"
            },
            "system": "http://hospital.smarthealthit.org",
            "value": "cccfa08b-c57c-0670-9c37-d2975aebcd40"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "SS",
                        "display": "Social Security Number"
                    }
                ],
                "text": "Social Security Number"
            },
            "system": "http://hl7.org/fhir/sid/us-ssn",
            "value": "999-39-9668"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "DL",
                        "display": "Driver's License"
                    }
                ],
                "text": "Driver's License"
            },
            "system": "urn:oid:2.16.840.1.113883.4.3.25",
            "value": "S99942851"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "PPN",
                        "display": "Passport Number"
                    }
                ],
                "text": "Passport Number"
            },
            "system": "http://standardhealthrecord.org/fhir/StructureDefinition/passportNumber",
            "value": "X76852719X"
        }
    ],
    "name": [
        {
            "use": "official",
            "family": "Dach178",
            "given": [
                "Dania217"
            ],
            "prefix": [
                "Ms."
            ]
        }
    ],
    "telecom": [
        {
            "system": "phone",
            "value": "555-488-9748",
            "use": "home"
        }
    ],
    "gender": "female",
    "birthDate": "1936-05-09",
    "deceasedDateTime": "2020-03-30T12:24:03-04:00",
    "address": [
        {
            "extension": [
                {
                    "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
                    "extension": [
                        {
                            "url": "latitude",
                            "valueDecimal": 41.878373897189995
                        },
                        {
                            "url": "longitude",
                            "valueDecimal": -71.31546023783606
                        }
                    ]
                }
            ],
            "line": [
                "283 Kessler Manor Suite 47"
            ],
            "city": "Attleboro",
            "state": "MA",
            "postalCode": "02703",
            "country": "US",
            **"period": {
                "extension": [
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
                        "valueCode": "unknown"
                    }
                ]
            }**
        }
    ],
    "maritalStatus": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
                "code": "S",
                "display": "S"
            }
        ],
        "text": "S"
    },
    "multipleBirthBoolean": false,
    "communication": [
        {
            "language": {
                "coding": [
                    {
                        "system": "urn:ietf:bcp:47",
                        "code": "de-DE",
                        "display": "German (Germany)"
                    }
                ],
                "text": "German (Germany)"
            }
        }
    ]
}


Inferno 
<img width="643" alt="image" src="https://user-images.githubusercontent.com/63259147/197039855-a1015510-f537-494b-9d50-3e547925ca63.png">

**Comment by Nbhatin** [comment]
Tried Same with exact example shown in the guide : patient.name

<img width="786" alt="image" src="https://user-images.githubusercontent.com/63259147/197040683-7ba1e0ff-5ff2-4d7d-b559-35d7ce20bf91.png">


FHir response :
{
    "resourceType": "Patient",
    "id": "999015",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2022-10-20T19:29:26.711+00:00",
        "source": "#84aeec6b-a3f7-4e",
        "profile": [
            "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
        ]
    },
    "extension": [
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
            "extension": [
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "urn:oid:2.16.840.1.113883.6.238",
                        "code": "2106-3",
                        "display": "Black"
                    }
                },
                {
                    "url": "text",
                    "valueString": "Black"
                }
            ]
        },
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
            "extension": [
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "urn:oid:2.16.840.1.113883.6.238",
                        "code": "2186-5",
                        "display": "Not Hispanic or Latino"
                    }
                },
                {
                    "url": "text",
                    "valueString": "Not Hispanic or Latino"
                }
            ]
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
            "valueString": "Lorrie Murphy561"
        },
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
            "valueCode": "F"
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
            "valueAddress": {
                "city": "Berlin",
                "state": "Berlin",
                "country": "DE"
            }
        },
        {
            "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
            "valueDecimal": 24.285486783792628
        },
        {
            "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
            "valueDecimal": 58.71451321620737
        }
    ],
    "identifier": [
        {
            "system": "https://github.com/synthetichealth/synthea",
            "value": "cccfa08b-c57c-0670-9c37-d2975aebcd40"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "MR",
                        "display": "Medical Record Number"
                    }
                ],
                "text": "Medical Record Number"
            },
            "system": "http://hospital.smarthealthit.org",
            "value": "cccfa08b-c57c-0670-9c37-d2975aebcd40"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "SS",
                        "display": "Social Security Number"
                    }
                ],
                "text": "Social Security Number"
            },
            "system": "http://hl7.org/fhir/sid/us-ssn",
            "value": "999-39-9668"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "DL",
                        "display": "Driver's License"
                    }
                ],
                "text": "Driver's License"
            },
            "system": "urn:oid:2.16.840.1.113883.4.3.25",
            "value": "S99942851"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "PPN",
                        "display": "Passport Number"
                    }
                ],
                "text": "Passport Number"
            },
            "system": "http://standardhealthrecord.org/fhir/StructureDefinition/passportNumber",
            "value": "X76852719X"
        }
    ],
    "name": [
        {
            "extension": [
                {
                    "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
                    "valueCode": "unknown"
                }
            ]
        }
    ],
    "telecom": [
        {
            "system": "phone",
            "_value": {
                "extension": [
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
                        "valueCode": "unknown"
                    }
                ]
            },
            "use": "home"
        }
    ],
    "gender": "female",
    "birthDate": "1936-05-09",
    "deceasedDateTime": "2020-03-30T12:24:03-04:00",
    "address": [
        {
            "extension": [
                {
                    "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
                    "extension": [
                        {
                            "url": "latitude",
                            "valueDecimal": 41.878373897189995
                        },
                        {
                            "url": "longitude",
                            "valueDecimal": -71.31546023783606
                        }
                    ]
                }
            ],
            "line": [
                "283 Kessler Manor Suite 47"
            ],
            "city": "Attleboro",
            "state": "MA",
            "postalCode": "02703",
            "country": "US",
            "period": {
                "extension": [
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
                        "valueCode": "unknown"
                    }
                ]
            }
        }
    ],
    "maritalStatus": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
                "code": "S",
                "display": "S"
            }
        ],
        "text": "S"
    },
    "multipleBirthBoolean": false,
    "communication": [
        {
            "language": {
                "coding": [
                    {
                        "system": "urn:ietf:bcp:47",
                        "code": "de-DE",
                        "display": "German (Germany)"
                    }
                ],
                "text": "German (Germany)"
            }
        }
    ]
}

**Comment by yunwwang** [comment]
DAR extension does not count for MustSupport test which is also mentioned in the FAQ: https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki/FAQ#q-how-does-inferno-test-mustsupport-flag-on-an-element

Inferno does not consider using a "Data Absent Reason" (DAR) extension on a "MustSupport" element as supporting the element "in a meaningful way," so Inferno ignores elements with DAR extensions when looking for "MustSupport" elements.

**Comment by Nbhatin** [comment]
> DAR extension does not count for MustSupport test which is also mentioned in the FAQ: https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki/FAQ#q-how-does-inferno-test-mustsupport-flag-on-an-element
> 
> Inferno does not consider using a "Data Absent Reason" (DAR) extension on a "MustSupport" element as supporting the element "in a meaningful way," so Inferno ignores elements with DAR extensions when looking for "MustSupport" elements.

I see. Thanks
