### ISSUE TITLE
Handling of escaped commas in search parameters (FI-1768)

### ISSUE THREAD

**Issue by jwjahns** [onc-healthit/onc-certification-g10-test-kit#314]
Hello,

In a local build, test 8.03 failed with the following:
![image](https://user-images.githubusercontent.com/83475323/197267842-58651ab5-8436-4244-8957-8fbfe188fda2.png)

However, the resource does have a category of "Path,Cyt" (see attached for full Bundle):
`        "category": [
          {
            "coding": [
              {
                "system": "urn:oid:1.2.840.114350.1.13.1545.1.7.10.798268.30",
                "code": "Path,Cyt"
              }
            ],
            "text": "Pathology and Cytology"
          }`

I think this test should be passing, so I'm assuming there's either an issue with commas in search param values, or in the escaping of the comma itself. The actual request Inferno makes is:

`https://[base]/api/FHIR/R4/DiagnosticReport?category=Path%5C,Cyt&date=2021-11-24T15:55:00Z&patient=ep0PiK6gWzcruJYb6zjNFoQ3`

Which seems correct (%5C is a backslash, so the comma is correctly escaped).

Full error text:

```
    Expected: Path,Cyt
    Found: #<FHIR::CodeableConcept:0x00007f449c390638 @id=nil, @extension=[], @coding=[#<FHIR::Coding:0x00007f449c390250 @id=nil, @extension=[], @system="urn:oid:1.2.840.114350.1.13.1545.1.7.10.798268.30", @version=nil, @code="Path,Cyt", @display=nil, @userSelected=nil, @source_hash={"system"=>"urn:oid:1.2.840.114350.1.13.1545.1.7.10.798268.30", "code"=>"Path,Cyt"}>], @text="Pathology and Cytology", @source_hash={"coding"=>[{"system"=>"urn:oid:1.2.840.114350.1.13.1545.1.7.10.798268.30", "code"=>"Path,Cyt"}], "text"=>"Pathology and Cytology"}>, #<FHIR::CodeableConcept:0x00007f449c38b8b8 @id=nil, @extension=[], @coding=[#<FHIR::Coding:0x00007f449c38b408 @id=nil, @extension=[], @system="http://loinc.org", @version=nil, @code="LP7839-6", @display="Pathology", @userSelected=nil, @source_hash={"system"=>"http://loinc.org", "code"=>"LP7839-6", "display"=>"Pathology"}>], @text="Pathology", @source_hash={"coding"=>[{"system"=>"http://loinc.org", "code"=>"LP7839-6", "display"=>"Pathology"}], "text"=>"Pathology"}>
```

Full Bundle: [DiagnosticReport_with_comma_in_category.txt](https://github.com/onc-healthit/onc-certification-g10-test-kit/files/9841713/DiagnosticReport_with_comma_in_category.txt)

**Comment by yunwwang** [comment]
@jwjahns 

Thank you for reporting this issue to us. We will fix it.
