### ISSUE TITLE
patient resource test indicating that gender, ethnicity and race are invalid 

### ISSUE THREAD

**Issue by druannew** [onc-healthit/onc-certification-g10-test-kit#315]
When testing Patient Resource via Inferno testing tool, we are receiving errors indicating we have invalid codes, but the references provided in the error message, have the code we are sending: 

Patient/706: Patient.extension[2].value.ofType(code): The value provided ('F') is not in the value set 'Birth Sex' (http://hl7.org/fhir/us/core/ValueSet/birthsex), and a code is required from this value set) (error message = Code System URI 'null' is unknown so the code cannot be validated)

This also happens for ethnicity where the code is: 2180-8 and Race where the code is: 1002-5.  

When we click the link, we see a note indicating that "The publication tooling does not currently support generation of this Value Set expansion. We anticipate updates to enable this feature before the next version of this guide is published. We have provided the manual expansion below for your review."

Is that why we are receiving the error?  What is the timeline for resolution?

**Comment by yunwwang** [comment]
Are you using US Core test kit or ONC (g)(10) test kit. 

Please check if this FAQ helps: https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki/FAQ#q-why-some-resources-failed-in-us-core-test-kit-with-terminology-validation-errors-but-passed-in-g10-test-kit

**Comment by druannew** [comment]
HI - Thanks for the answer, but I'm not sure it has answered my question.  We are using the G10 kit and I did review the above mentioned FAQ from previous question I posted in another forum.  But, the FAQ said to report issue here, which is what I thought I was doing?    I'm just trying to figure out is this a known issue.  The FAQ doesn't seem to indicate that it is.  

From FAQ.  
ONC (g)(10) Standardized API Test Kit uses its own terminology service. This terminology service is updated regularly with the latest release from the Unified Medical Language System (UMLS). If you see a terminology validation error in (g)(10) Test Kit, and you are certain the code is correct, please report the issue to the [issue page](https://github.com/onc-healthit/onc-certification-g10-test-kit/issues).

**Comment by yunwwang** [comment]
Are you using the inferno.healthit.gov? If so, could you email the url of your test session to inferno@mitre.org?

**Comment by druannew** [comment]
Hi - I sent an email with the session ID like requested yesterday.  I haven't heard back from anyone.  Just trying to confirm that you got what you needed?

**Comment by arscan** [comment]
@druannew thanks for following up.  That is the wrong email, it is inferno@groups.mitre.org

**Comment by druannew** [comment]
No worries...just did.  Please let me know if you need something else.

**Comment by yunwwang** [comment]
Your session indicated that you were running the US Core test kit. 
![image](https://user-images.githubusercontent.com/8761175/197885601-219b6f13-1ffe-40b0-8109-d6adbd3ec780.png)

As we discussed above, the US Core test kit uses tx.fhir.org for terminology validation and that server could return terminology error if the server did not have the specific concept.

**Comment by druannew** [comment]
Thanks for reviewing the session.
