### ISSUE TITLE
Multi-Patient API DELETE request

### ISSUE THREAD

**Issue by SavannahDearing** [onc-healthit/onc-certification-g10-test-kit#316]
https://inferno.healthit.gov/suites/test_sessions/0a997c5a-8a22-425f-bf1c-318d3fa27184

It looks like 7.2.07 test is sending a GET request instead of a DELETE request?
I removed all redirect logic from our server just in case that was causing it to redirect as a GET.
  
I also tested using postman and it was able to do the delete correctly, and the server was correctly able to see the REQUEST_METHOD as DELETE.

The test "passes" because sending a GET is triggers the status check logic, which also returns a 202.   But it is not triggering the actual remove logic.

**Comment by yunwwang** [comment]
The test does sent DELETE request. This is the messages from Inferno demo server:

![image](https://user-images.githubusercontent.com/8761175/198037718-acb0aacb-6c2d-4633-9fe5-ffbe13e4d658.png)

I assume this is caused by redirect

**Comment by SavannahDearing** [comment]
The content-location we were giving ended with /async/, which then redirected to a GET to /async/index.php

Resolving this fixed the issue, thanks!
