### ISSUE TITLE
Is there a way to change the redirect uri? Changing INFERNO_HOST in the .env file doesn't seem to work

### ISSUE THREAD

**Issue by jsandoval-kareo** [onc-healthit/onc-certification-g10-test-kit#318]
First off, I looked through the previous issues and came across this https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/277. However, changing that value doesn't seem to do anything for me in terms of the redirect/launch uris. 

However, throughout all of the codebase, I see that these values are retrieved from config.options, e.g., config.options[:launch_uri], config.options[:redirect_uri].

I don't see where these config.options values are set initially though. Is there a way to modify those values, or perhaps something I may be overlooking?

**Comment by Jammjammjamm** [comment]
It's set in the SMART tests: https://github.com/inferno-framework/smart-app-launch-test-kit/blob/main/lib/smart_app_launch/smart_stu1_suite.rb#L24

You could copy those lines into the g10 suite and set them to the values you want, but its current value is based on the value of the `INFERNO_HOST` and `BASE_PATH` environment variables. By setting those environment variables you should be able to host inferno at any host/path.

**Comment by Jammjammjamm** [comment]
I should note that you can't just change the launch and redirect uris to completely arbitrary values. They do not affect the path where those routes are actually hosted. They are just a way to turn the relative url where the routes are hosted into an absolute url.

**Comment by jsandoval-kareo** [comment]
So it looks like i need to set the base_url, where does the base_url get set on the docker deployment?

**Comment by Jammjammjamm** [comment]
It is set based on `INFERNO_HOST` and `BASE_PATH`. If you update those values in `.env`, it should pick up those values.

**Comment by jsandoval-kareo** [comment]
@Jammjammjamm we were able to fix our issue per https://github.com/onc-healthit/onc-certification-g10-test-kit/pull/319

**Comment by Jammjammjamm** [comment]
Are you using `run.sh` to run Inferno?

**Comment by jsandoval-kareo** [comment]
@Jammjammjamm i believe it was through docker compose

**Comment by Jammjammjamm** [comment]
I am trying to understand why something that those of us on the Inferno team use all the time, including in multiple production environments, isn't working for you.

After making changes to `.env`, you need to use the run script, or do `docker-compose build` to rebuild the image. Inferno is reading values from the `.env` file, so the image needs to be rebuilt after changes are made to the file. If you set the environment values directly in the docker-compose file, it will override the values in `.env`.
