### ISSUE TITLE
Inferno doesnt validate terminology codes (FI-1780)

### ISSUE THREAD

**Issue by Nbhatin** [onc-healthit/onc-certification-g10-test-kit#320]
I am running g10 suite for uscore3.1 . I had invalid codes and display for Patient Race, Ethnicity, language , birthsex etc
But Inferno passed the patient tests.

Does Inferno validate the codes with system ? eg if incorrect snomed code is provided for a profile, should it fail ?
I tried giving incorrect snomed code for Patient smoking observation as well, but the test passed.

Patient profile -
{
    "resourceType": "Patient",
    "id": "999321",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2022-10-28T12:55:24.919+00:00",
        "source": "#e9fbb090-9c4d-41",
        "profile": [
            "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
        ]
    },
    "extension": [
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
            "extension": [
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "urn:oid:2.16.840.1.113883.6.238",
                        "code": "123",
                        "display": "Black"
                    }
                },
                {
                    "url": "text",
                    "valueString": "Black"
                }
            ]
        },
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
            "extension": [
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "urn:oid:2.16.840.1.113883.6.238",
                        "code": "ABCD",
                        "display": "ABCD"
                    }
                },
                {
                    "url": "text",
                    "valueString": "Not Hispanic or Latino"
                }
            ]
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
            "valueString": "Lorrie Murphy561"
        },
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
            "valueCode": "ZZZ"
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
            "valueAddress": {
                "city": "Berlin",
                "state": "Berlin",
                "country": "XYZ"
            }
        },
        {
            "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
            "valueDecimal": 24.285486783792628
        },
        {
            "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
            "valueDecimal": 58.71451321620737
        }
    ],
    "identifier": [
        {
            "system": "https://github.com/synthetichealth/synthea",
            "value": "cccfa08b-c57c-0670-9c37-d2975aebcd40"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "MR",
                        "display": "Medical Record Number"
                    }
                ],
                "text": "Medical Record Number"
            },
            "system": "http://hospital.smarthealthit.org",
            "value": "cccfa08b-c57c-0670-9c37-d2975aebcd40"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "SS",
                        "display": "Social Security Number"
                    }
                ],
                "text": "Social Security Number"
            },
            "system": "http://hl7.org/fhir/sid/us-ssn",
            "value": "999-39-9668"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "DL",
                        "display": "Driver's License"
                    }
                ],
                "text": "Driver's License"
            },
            "system": "urn:oid:2.16.840.1.113883.4.3.25",
            "value": "S99942851"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "PPN",
                        "display": "Passport Number"
                    }
                ],
                "text": "Passport Number"
            },
            "system": "http://standardhealthrecord.org/fhir/StructureDefinition/passportNumber",
            "value": "X76852719X"
        }
    ],
    "name": [
        {
            "use": "official",
            "family": "Dach178",
            "given": [
                "Dania217"
            ],
            "prefix": [
                "Ms."
            ]
        }
    ],
    "telecom": [
        {
            "system": "phone",
            "value": "123",
            "use": "home"
        }
    ],
    "gender": "female",
    "birthDate": "1936-05-09",
    "deceasedDateTime": "2020-03-30T12:24:03-04:00",
    "address": [
        {
            "extension": [
                {
                    "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
                    "extension": [
                        {
                            "url": "latitude",
                            "valueDecimal": 41.878373897189995
                        },
                        {
                            "url": "longitude",
                            "valueDecimal": -71.31546023783606
                        }
                    ]
                }
            ],
            "line": [
                "283 Kessler Manor Suite 47"
            ],
            "city": "Attleboro",
            "state": "MA",
            "postalCode": "02703",
            "country": "US"
        }
    ],
    "maritalStatus": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
                "code": "S",
                "display": "S"
            }
        ],
        "text": "S"
    },
    "multipleBirthBoolean": false,
    "communication": [
        {
            "language": {
                "coding": [
                    {
                        "system": "urn:ietf:bcp",
                        "code": "abcd",
                        "display": "abcd"
                    }
                ],
                "text": "German (Germany)"
            }
        }
    ]
}

**Comment by Nbhatin** [comment]
![image](https://user-images.githubusercontent.com/63259147/198602943-34fa49c6-2f90-4ca0-b954-e20130ff5828.png)

**Comment by Jammjammjamm** [comment]
Are you running this on inferno.healthit.gov or on a local installation?

**Comment by Nbhatin** [comment]
local installation.
If I turn off validator, it gives error that validator is down which is good.
If the validator is working, the terminologies are not validated.

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/63259147/198629560-b51e40aa-d120-47e8-9548-7dfe85547537.png">

**Comment by Jammjammjamm** [comment]
We've verified this issue and will address it in the next release.

**Comment by Nbhatin** [comment]
Hi, Could you confirm if it was fixed for all terminologies ?

My local installation is on V.3.3.1 and I am running g10 suite with US Core 3.1.1 / USCDI v1
Somehow my tests are still passing for incorrect terminology codes, not sure if I'm missing something..

Smoking Status profile had incorrect snomed code for value and the tests passed all validations.
Similarly, for lab result observation, the code had incorrect loinc code but the test passed.

<img width="690" alt="image" src="https://user-images.githubusercontent.com/63259147/205167492-435fc653-4958-4162-9f5c-9687c068f2a4.png">

smoking observation:
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/63259147/205165985-ba7f0e96-e171-4e23-ae2e-691b1706a89e.png">

<img width="700" alt="image" src="https://user-images.githubusercontent.com/63259147/205167422-c4baafad-d22d-490d-b8a9-98f14713b6f8.png">


lab result:

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/63259147/205167218-2207a7c1-f55d-4490-b8fa-9eaccb033c47.png">

<img width="773" alt="image" src="https://user-images.githubusercontent.com/63259147/205167101-6277a61a-2dbb-4d3d-95a6-76a79cdc32d0.png">

**Comment by Nbhatin** [comment]
Thanks for the quick response. I will verify..
