### ISSUE TITLE
Vital Sign failing on valid UCUM units

### ISSUE THREAD

**Issue by drtootsie** [onc-healthit/onc-certification-g10-test-kit#323]
http://hl7.org/fhir/R4B/valueset-ucum-vitals-common.html

For our body height test, we are sending back valid UCUM units as seen at unitsofmeasure.org
                    {
                        "valueQuantity": {
                            "value": 5.433333333333334,
                            "unit": "ft",
                            "system": "http://unitsofmeasure.org",
                            "code": "ft"
                        }
                    },
                    
as well as getting an invalid one for blood glucose too
                    {
                        "code": {
                            "coding": [
                                {
                                    "system": "http://loinc.org",
                                    "code": "2339-0",
                                    "display": "Glucose [Mass/volume] in Blood"
                                }
                            ],
                            "text": "Glucose [Mass/volume] in Blood"
                        },
                        "valueQuantity": {
                            "value": 98.0,
                            "unit": "mg/dL",
                            "system": "http://unitsofmeasure.org",
                            "code": "mg/dL"
                        }

with the error of

<html>
<body>

Observation/vs..20220818130000166339--67469.656186: Observation.component[14].value.ofType(Quantity): The Coding provided (http://unitsofmeasure.org#mg/dL) is not in the value set http://hl7.org/fhir/ValueSet/ucum-vitals-common\|4.0.1(which actually refers to http://hl7.org/fhir/ValueSet/ucum-vitals-common), and a code is required from this value set. (error message = Not in value set http://hl7.org/fhir/ValueSet/ucum-vitals-common)
--

</body>
</html>
and
<html>
<body>

Observation/vs..20220818130000166339--67469.656186: Observation.component[7].value.ofType(Quantity): The Coding provided (http://unitsofmeasure.org#ft) is not in the value set http://hl7.org/fhir/ValueSet/ucum-vitals-common\|4.0.1(which actually refers to http://hl7.org/fhir/ValueSet/ucum-vitals-common), and a code is required from this value set. (error message = Not in value set http://hl7.org/fhir/ValueSet/ucum-vitals-common)
--

</body>
</html>

Do we need to convert our measurements to the units listed in the URL form the error?

**Comment by yunwwang** [comment]
Are you testing US core profiles? If so, which profile are you using?

For US Core body height, the only allowed codes are `cm` and `[in_i]`. See: http://hl7.org/fhir/R4/valueset-ucum-bodylength.html

I am not sure which profile you use for blood glucose.

**Comment by drtootsie** [comment]
@yunwwang  I figured it out in the end, I was providing back results that were not compliant with that specific resource test.
