### ISSUE TITLE
Practitioner Reference not picked up in Care Team

### ISSUE THREAD

**Issue by drtootsie** [onc-healthit/onc-certification-g10-test-kit#325]
https://inferno.healthit.gov/suites/test_sessions/efcbf834-1ae7-4914-a0eb-a5f27864cbef 

In our test, our encounter reference test fails; however, condition returns a reference to encounter that the encounter service can return form.  Are we formatting something incorrectly?

**Comment by Jammjammjamm** [comment]
https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki/FAQ#q-how-does-inferno-test-us-core-encounter-resource

**Comment by drtootsie** [comment]
@Jammjammjamm  that was perfect, thank you
