### ISSUE TITLE
[Multi-Patient API] Test # 7.2.07 making delete call and Test # 7.3.03 making get call without creating export call again

### ISSUE THREAD

**Issue by satyaki-bhargava** [onc-healthit/onc-certification-g10-test-kit#326]
Hi Team,

My organization and I are testing Test suit # 7 with inferno version (BUILT WITH) V.0.3.12. We are seeing strange API sequence.
1. In Test Case 7.2.7(Bulk Data Server returns "202 Accepted" for delete request), we are seeing that inferno did a get call and then made a delete API call. which is correct as per test case intention goes.
![image](https://user-images.githubusercontent.com/35564781/198963562-76546124-4094-4d6c-a5f0-371b6a83218a.png)
3. However, In Test Case # 7.3.03 - inferno is making a get call on deleted resource. Which is returning zero count.
![image](https://user-images.githubusercontent.com/35564781/198963698-3afd245e-c3d9-4d1a-a8ee-89c9a94e3b67.png)

I have also checked this behavior by running test suit running with US Gov Open Source Server.

Would you please let me know if this is expected behavior. Technically it is making almost impossible to get back the deleted resources, unless my understanding is incorrect.

**Comment by Jammjammjamm** [comment]
Here's a summary of how those tests work.

The tests in 7.03 are performed based on the output of 7.2.06. So Inferno requests a bulk export (7.2.04), waits for it to complete (7.2.05), and then verifies and saves the contents of the final status check (7.2.06).

![Screen Shot 2022-10-31 at 9 16 25 AM](https://user-images.githubusercontent.com/15969967/199016717-1889cc2b-36ca-4333-87a9-bec20bf0865e.png)

Then 7.2.07 requests a new bulk export and immediately cancels it (note that it does not save any output).

![Screen Shot 2022-10-31 at 9 18 01 AM](https://user-images.githubusercontent.com/15969967/199017031-2a610ff6-7497-4d60-9a07-a2f29f4528c9.png)

The tests in 7.3 are performed based on the output which was saved in 7.2.06.

![Screen Shot 2022-10-31 at 9 20 11 AM](https://user-images.githubusercontent.com/15969967/199017532-4a5e3767-1c01-4696-8a5c-fa5affd0e852.png)

**Comment by satyaki-bhargava** [comment]
@Jammjammjamm : Thank you, I did not know that there was a delete but with a cancel one.

**Comment by satyaki-bhargava** [comment]
Closing as issue lies with our side of implementation of FHIR server.
