### ISSUE TITLE
Clinical Test Observations not correctly identified in Bulk Data tests

### ISSUE THREAD

**Issue by Jammjammjamm** [onc-healthit/onc-certification-g10-test-kit#327]
When using US Core 5, Clinical Test Observations are not identified. See https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Multi-Patient.20Authorization.20and.20API.20STU2.20.288.2E3.2E16.29

**Comment by agasthahyd06** [comment]
Is the fix pushed to Inferno

**Comment by Jammjammjamm** [comment]
It should be available on inferno-dev.healthit.gov, but it won't be on the main site until the official release next week.
