### ISSUE TITLE
Standalone Patient App and EHR Practitioner App tests do not adequately validate granted scopes

### ISSUE THREAD

**Issue by Jammjammjamm** [onc-healthit/onc-certification-g10-test-kit#333]
The Standalone Patient App and EHR Practitioner App tests validate that patient-level and user-level scopes are requested. However, they do not validate that patient-level and user-level scopes are granted, so it is possible for a system to pass both of these sets of tests even if it only grants either patient-level or user-level scopes.

**Comment by arscan** [comment]
Our initial solution (#390) to this gap was to check systems were granting scopes to the Standalone Patient App and EHR Practitioner App tests.  However, an implementer pointed out that their interpretation was that it would be ok to only grant patient-level scopes when a patient context is provided, even if user-level scopes is desired by the app and user.  See https://chat.fhir.org/#narrow/stream/179309-inferno/topic/SMART.201.2E0.2E0.20.2B.20EHR.20Launch.20with.20Patient.20Scopes

Should a system be able to claim support for the [Clinician Access for EHR Launch](http://hl7.org/fhir/smart-app-launch/1.0.0/conformance/index.html#clinician-access-for-ehr-launch) capability set if they do not allow for user-level scopes to be granted when providing patient context in the same launch?  Is the ability to be granted user-level scopes and patient context for an ehr-launched app an important feature from an app's  perspective?
