### ISSUE TITLE
Connection refused to g10 validator service.

### ISSUE THREAD

**Issue by naveensahukari** [onc-healthit/onc-certification-g10-test-kit#334]
When I run the Single Patient API tests,  all the fhir profiles are failed to validate. 

I am attaching the screenshot of the issue and session link for reference.

![image](https://user-images.githubusercontent.com/116081575/200308937-9d965528-3264-4a71-a18d-e224d3773625.png)

Session link : https://inferno.healthit.gov/suites/test_sessions/e32804d3-0346-4885-9057-3bdc30e00bc7#g10_certification-g10_single_patient_api

Please suggest on further steps.

**Comment by SavannahDearing** [comment]
Same on bulk tests, is something down?
![image](https://user-images.githubusercontent.com/58518170/200310922-f170dd5d-30cc-4aee-bb25-be21371f3db4.png)

**Comment by yunwwang** [comment]
Did you test using inferno.healthit.gov, local docker image, or ruby command line?

**Comment by yunwwang** [comment]
Thank you for letting us know the issue. We are working on it.

**Comment by yunwwang** [comment]
The issue is resolved now.

**Comment by SavannahDearing** [comment]
Thanks !

**Comment by naveensahukari** [comment]
Thank you for the fix @yunwwang
