### ISSUE TITLE
Documentation issue (broken web page)

### ISSUE THREAD

**Issue by NACHC-CAD** [onc-healthit/onc-certification-g10-test-kit#336]
Not sure if this is the right place to report this but I figured I'd start here.  

For the web page:
https://inferno.healthit.gov/ 

Clicking on the link (blue oval button) for (g)(10)Standardized API Test Kit opens a web page where the gui thrashes and flickers so that it is unusable.  

Direct link to the page that thrashes is:
https://inferno.healthit.gov/suites/g10_certification

**Comment by yunwwang** [comment]
@NACHC-CAD We have noticed that UI issue. We have a fix and will be included in this upcoming release. At the same time, you can try to adjust your screen's resolution or zoom ratio to avoid the flicking. Or you can try the new release on inferno-dev.healthit.gov.

**Comment by yunwwang** [comment]
https://github.com/inferno-framework/inferno-core/pull/272
