### ISSUE TITLE
Invalid JSON bug when attempting "3 EHR Practitioner App test"

### ISSUE THREAD

**Issue by dhit-mdavis** [onc-healthit/onc-certification-g10-test-kit#338]
Hi there.

When using the following client secret for the 3 EHR Practitioner App tests, I get the following behavior

- the test step counter that usually appears at the bottom right of the page doesn't load
- I get a number of errors in the browser console
![image](https://user-images.githubusercontent.com/56314435/200851161-5dd49a7a-7a7e-453c-8d5c-84e94fcd76b1.png)

![image](https://user-images.githubusercontent.com/56314435/200851179-e193a32a-619a-430d-8b09-895e4aac8360.png)

Here is the client secret
**NOTE:** this client secret has been updated and expected functionality has been confirmed after updating

Prz&w%K[M[jCYk_11u(o_^wdR

**Comment by Jammjammjamm** [comment]
I'm pretty sure it's the `%` that is causing the problem. It'll take some time to debug further.

**Comment by dhit-mdavis** [comment]
Thanks for the update Jamm - I was able to move forward on my end by creating a new client secret but just wanted to pass it on
