### ISSUE TITLE
Request: is it possible to have the "Perform Invalid Launch" URL open in a new tab automatically when clicked?

### ISSUE THREAD

**Issue by dhit-mdavis** [onc-healthit/onc-certification-g10-test-kit#339]
![image](https://user-images.githubusercontent.com/56314435/200862318-d6ae7757-ac4d-4400-b959-55e85de98099.png)

**Comment by Jammjammjamm** [comment]
We really wish it were possible, but it isn't. For safety reasons, we don't allow arbitrary html in those messages and only render markdown, which doesn't provide a mechanism for that.

**Comment by dhit-mdavis** [comment]
Thanks for this info Jamm! I get it, no pressure from my end. I can at least relay this message to clients. 

It came up again recently so that's why I thought I'd ask

**Comment by yunwwang** [comment]
@dhit-mdavis  will close this issue. If you still have questions about this issue, you can either reopen this one or create a new issue. Thank you.
