### ISSUE TITLE
 Ruby 3.1.2 for Gemfile in Inferno 3.3.0

### ISSUE THREAD

**Issue by danielberez** [onc-healthit/onc-certification-g10-test-kit#342]
Hi,

In trying to rebuild the terminology  in Inferno Version 3.3.0 using the command
`docker-compose -f terminology_compose.yml up --build`
I get the following error :

...
```
Step 10/14 : RUN gem install bundler
 ---> Using cache
 ---> df29fbc1b434
Step 11/14 : RUN bundle install
 ---> Running in 0598ed7ff0b0
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Resolving dependencies...
Resolving dependencies...
Resolving dependencies...
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    onc_certification_g10_test_kit was resolved to 3.3.0, which depends on
      Ruby (>= 3.1.2)

  Current Ruby version:
    Ruby (= 2.7.2)
The command '/bin/sh -c bundle install' returned a non-zero code: 6
```

Do you have any idea how to fix this issue ?
Thanks

**Comment by Jammjammjamm** [comment]
Sorry, we'll get that fixed ASAP. For now, you can build the terminology using [version 3.2.0](https://github.com/onc-healthit/onc-certification-g10-test-kit/releases/tag/v3.2.0), then copy `resources/terminology/validators/bloom` to version 3.3.0.

**Comment by danielberez** [comment]
Thanks, 

That works !
