### ISSUE TITLE
Test script version via API?

### ISSUE THREAD

**Issue by ddegr** [onc-healthit/onc-certification-g10-test-kit#349]
Hi,

There is an endpoint `https://inferno.healthit.gov/suites/api/version` returning the current Inferno Test Kit version.

And it would be nice to be able get the current test script version. 
For example, that `3.1.1` string.

![image](https://user-images.githubusercontent.com/9136211/201998746-beab7e80-cead-4780-a8f8-8a3d7693bec3.png)

**Comment by Jammjammjamm** [comment]
We don't expose just the version of the test suites, but if you fetch the list of test suites at `https://inferno.healthit.gov/suites/api/test_suites`, you'll get a summary JSON view of each suite including the version.

**Comment by ddegr** [comment]
@Jammjammjamm thanks a lot. I'll try to use that instead

**Comment by ddegr** [comment]
It worked for me. Thanks
