### ISSUE TITLE
Single Patient #4.27.04 - Could not resolve location.location 

### ISSUE THREAD

**Issue by WMTadmin** [onc-healthit/onc-certification-g10-test-kit#353]
I am unable to determine why we continue to receive the "Could not resolve location.location reference" error?

The output from the initial encounter query is...
{
	"id": "97a24acd-c078-425e-addf-62d7eb0faf01",
	"meta": {
		"versionId": "1",
		"lastUpdated": "2022-11-17T12:36:04-06:00"
	},
	"resourceType": "Encounter",
	"identifier": [
		{
			"system": "urn:uuid:97a24acd-c078-425e-addf-62d7eb0faf01",
			"value": "97a24acd-c078-425e-addf-62d7eb0faf01"
		}
	],
	"status": "finished",
	"class": {
		"system": "http:\\/\\/terminology.hl7.org\\/CodeSystem\\/v3-ActCode",
		"code": "AMB",
		"display": "ambulatory"
	},
	"type": [
		{
			"coding": [
				{
					"system": "http:\\/\\/snomed.info\\/sct",
					"code": "185349003",
					"display": "Encounter for check up (procedure)"
				}
			]
		}
	],
	"subject": {
		"reference": "Patient\\/97a248d4-d1ba-4a77-80a0-56ee037d47e7",
		"type": "Patient"
	},
	"participant": [
		{
			"type": [
				{
					"coding": [
						{
							"system": "http:\\/\\/terminology.hl7.org\\/CodeSystem\\/v3-ParticipationType",
							"code": "PPRF",
							"display": "Primary Performer"
						}
					]
				}
			],
			"period": {
				"start": "2015-06-22T10:00:00-06:00"
			},
			"individual": {
				"reference": "Practitioner\\/97a3fb1e-8f88-4b80-a0ed-d5c5e90c0535",
				"type": "Practitioner"
			}
		},
		{
			"type": [
				{
					"coding": [
						{
							"system": "http:\\/\\/terminology.hl7.org\\/CodeSystem\\/v3-ParticipationType",
							"code": "REF",
							"display": "Referrer"
						}
					]
				}
			],
			"period": {
				"start": "2015-06-22T10:00:00-06:00"
			},
			"individual": {
				"reference": "Practitioner\\/97a3fb1e-8f88-4b80-a0ed-d5c5e90c0535",
				"type": "Practitioner"
			}
		}
	],
	"period": {
		"start": "2015-06-22T10:00:00-06:00"
	},
	"reasonCode": [
		{
			"text": "Acute visit for fever"
		}
	],
	"hospitalization": {
		"dischargeDisposition": {
			"extension": [
				{
					"valueCode": "unknown",
					"url": "http:\\/\\/hl7.org\\/fhir\\/StructureDefinition\\/data-absent-reason"
				}
			]
		}
	},
	"location": [
		{
			"location": {
				"reference": "Location\\/97b17dc2-022a-4dbf-ad33-c5eac2770696",
				"type": "Location"
			}
		}
	],
	"serviceProvider": {
		"reference": "Organization\\/97a23a90-a326-41b0-aa2c-9ce0b3feb928",
		"type": "Organization"
	}
}

The last output from Inferno contains the location query output...
{
  "id": "97b17dc1-fde3-4a5c-af3d-d31c51d186bc",
  "meta": {
    "versionId": "1",
    "lastUpdated": "2022-11-17T13:28:45-06:00"
  },
  "resourceType": "Location",
  "status": "active",
  "name": "Organization Address",
  "telecom": [
    {
      "system": "phone",
      "value": "+1(555)-777-1234"
    },
    {
      "system": "email",
      "value": "ron@williamsmedtech.net"
    }
  ],
  "address": {
    "type": "physical",
    "line": [
      "1357 AMBER DR"
    ],
    "city": "BEAVERTON",
    "state": "OR",
    "postalCode": "97006",
    "country": "USA",
    "period": {
      "start": "2021-11-17T13:28:45.147-06:00"
    }
  }
}

Both of these resources validate using "https://inferno.healthit.gov/validator".
I do not understand what Inferno thinks is wrong with this data.

Thanks for any assistance you can provide!

Ron

**Comment by Jammjammjamm** [comment]
It means that Inferno wasn't able to retrieve the referenced Location from the server.

**Comment by WMTadmin** [comment]
Turned out to be internal data retrieval issue.
