### ISSUE TITLE
Configuration error after new session is created

### ISSUE THREAD

**Issue by ddegr** [onc-healthit/onc-certification-g10-test-kit#354]
After create new test session the page says 

`There is 1 configuration error that must be resolved.`

If I click the error message the page says 

`Unable to connect to Validator: Failed to open TCP connection to g10_validator_service:4567 (Connection refused - connect(2) for 172.20.0.11:4567)`

**Comment by SavannahDearing** [comment]
Same here.

**Comment by dhit-mdavis** [comment]
Test still runs but have been seeing this since last night
![image](https://user-images.githubusercontent.com/56314435/202744910-8b228952-79b7-495a-b14c-daed62c46729.png)
![image](https://user-images.githubusercontent.com/56314435/202744944-68febe2a-d4c5-4c9e-8f53-1d481fa96179.png)

**Comment by dhit-mdavis** [comment]
Same here
