### ISSUE TITLE
4.32 Missing Data Tests - Guidance

### ISSUE THREAD

**Issue by SavannahDearing** [onc-healthit/onc-certification-g10-test-kit#355]
Hi,

For ONC Certification (g)(10) Standardized API V.3.3.1 on inferno.healthit.gov

I seem to be having trouble with these tests.. this is my current understanding:

Looking at other issues reported, and the descriptions of the tests, there seems to be two items we're looking at:
1) Required Fields [Cardinality 1+ for FHIR endpoint specifications]
2) Must Support fields [Cardinality 1+ for FHIR endpoints under U.S. Core]

Then for Missing Data: 
1) If the missing data is a CodeableConcept, and has no 'unk' / 'unknown' value in the code system, use the data-absent-reason codeset: https://www.hl7.org/FHIR/valueset-data-absent-reason.html
2) If the missing data is NOT a CodeableConcept, use the extension: https://hl7.org/FHIR/extension-data-absent-reason.html

Then these are the specific tests:

> 4.32.01 Server represents missing data with the DataAbsentReason Extension
> _For non-coded data elements, servers SHALL use the DataAbsentReason Extension to represent missing data in a required field_

So, is this test looking SPECIFICALLY for fields that are REQUIRED per FHIR, but NOT Must Support per US Core?

> 4.32.02 Server represents missing data with the DataAbsentReason CodeSystem
> _For coded data elements with example, preferred, or extensible binding strengths to ValueSets which do not include an appropriate "unknown" code, servers SHALL use the "unknown" code from the DataAbsentReason CodeSystem._

So, is this test looking at ANY for fields that are represented by code systems that dont have unknown values?  Maybe Loinc as an example?

I seem to be having trouble being able to pass this test, but also pass all other Must Support and Required Fields tests for each endpoint.  Maybe an example for each test would help me understand.

**Comment by yunwwang** [comment]
For test 4.32.01, Inferno looks the DAR extension in any non-coded data elements. 
For test 4.32.02, Inferno looks the DAR code `unknown` in any coded data elements.

The exception here is Observation.value since Observation has a dedicated Observation.dataAbsentReason element.
 
These two tests are independent from validation tests and MS tests.

Inferno demo server has Condition resource which has DAR extension in Condition.category for US Core v3.1.1 and US Core v4.0.0.

**Comment by SavannahDearing** [comment]
so, if I just have an extension for CareTeam.participant, we will fail the CareTeam tests:
_CareTeam/30560df3-fa14-4bc2-9834-7d1c360c34f0: CareTeam.participant[0]: CareTeam.participant.member: minimum required = 1, but only found 0 (from http://hl7.org/fhir/us/core/StructureDefinition/us-core-careteam)_

BUT we pass the Data Absent test:
_4.32.01 Server represents missing data with the DataAbsentReason Extension_


So essentially to pass both tests, we MUST include multiple patients?  One which has data, and one which does not.  
I'm not sure if its more appropriate to "skip" a test using the extension than failing, but now that I know what to do, its easier to understand.

**Comment by SavannahDearing** [comment]
This led me to a follow-up question.. how to use Additional Patient IDs for the Single Patient API Test?

This seems to use the same token as the patient you logged in as during Standalone Patient App.. you cant give a second token? You must have one token that allows inferno to pull info for multiple patients?  Currently we don't allow for this... there might be a use case here for primary / dependent accounts, but we don't have that feature yet.

**Comment by yunwwang** [comment]
May be CareTeam.participant.member.

You can have multiple CareTeam for a patient or a CareTeam with multiple participant and one of which has a DAR extension on participant.member.

The Test 3 is EHR practitioner login. A practitioner may have access to multiple patients. If you run the tests in sequence, the token in Test 3 is the one used for the following Single Patient (Test 4) tests.

**Comment by yunwwang** [comment]
The system value is wrong. it should be `http://terminology.hl7.org/CodeSystem/data-absent-reason`

**Comment by SavannahDearing** [comment]
I was JUST looking that up after I re-read!! Testing :)
