### ISSUE TITLE
Multi-Patient Authorization and API

### ISSUE THREAD

**Issue by Bismi10** [onc-healthit/onc-certification-g10-test-kit#357]
For Bulk Data Client ID (required) * We are providing Client ID assertion but its not validating. Can any one Specify the what data need to provide in "Bulk Data Client ID (required) *"

![image](https://user-images.githubusercontent.com/118447363/203309894-9df69bbc-8f52-43c4-905d-f541615426a2.png)

**Comment by yunwwang** [comment]
This is the client ID that server assigned during the bulk data registration.

For example, if I register Inferno test kit to bulk-data.smarthealthit.org, the server assigns a client ID to Inferno test kit. This is the ID that should be used in this popup

![image](https://user-images.githubusercontent.com/8761175/203361072-35b95e87-d6ee-4104-8d87-00bcd9380bc8.png)

**Comment by Bismi10** [comment]
Thanks
