### ISSUE TITLE
Could not find Patient Reference Patient/e91975f5-9445-c11f-cabf-c3c6dae161f2 in reference fields patient of resource Provenance/85807868-f29c-1ca9-1d2a-91665d2c4f05

### ISSUE THREAD

**Issue by vohuythao** [onc-healthit/onc-certification-g10-test-kit#359]
Hello, 

When I run the Single Patient API test, I met this problem

![image](https://user-images.githubusercontent.com/14121587/204093011-39620643-f22a-4e2f-b559-8b107493eb0e.png)

Go to more details

`"fullUrl": "https://sfp-proxy23604.azurewebsites.net/fhir/Provenance/85807868-f29c-1ca9-1d2a-91665d2c4f05",
      "resource": {
        "resourceType": "OperationOutcome",
        "id": "3072650f-7d47-4426-ae20-e7ff1264c31d",
        "issue": [
          {
            "severity": "warning",
            "code": "forbidden",
            "diagnostics": "Could not find Patient Reference Patient/e91975f5-9445-c11f-cabf-c3c6dae161f2 in reference fields patient of resource Provenance/85807868-f29c-1ca9-1d2a-91665d2c4f05"
          }
        ]
      },`

Then I search in FHIR data for Provenance ID and saw it also has reference to this Patient ID

![image](https://user-images.githubusercontent.com/14121587/204093127-c3413ea9-b45b-4abd-95f8-a3ddb38cea58.png)

I think all the correct data is there in FHIR, just don't know why Inferno throw error.

If you guys can suggest any hint, any keyword or any direction to troubleshoot, I am appreciate your help

Thank you

**Comment by yunwwang** [comment]
Have you check if this query to your server returns a Bundle with both Patient and Provenance resources?

{{fhirurl}}/Patient?_id=e91975f5-9445-c11f-cabf-c3c6dae161f2&_revinclude=Provenance:target

**Comment by vohuythao** [comment]
Hello @yunwwang 


I use US Core 3.1.1

And I can get the patient and provenance from this above query

provenance
![image](https://user-images.githubusercontent.com/14121587/204323488-75bf7fbf-1287-437c-a6a0-a91f42af183f.png)

patient
![image](https://user-images.githubusercontent.com/14121587/204323600-ac70bae9-cc7e-4eb9-9291-68dcceff3737.png)


I will try with US Core 4.0.0

Thank you

**Comment by vohuythao** [comment]
Yes @yunwwang , there is another issue that was raised in the github of Microsoft FHIR proxy
https://github.com/microsoft/fhir-proxy/issues/69

We are using the managed version is Azure API for FHIR and to pass all the Inferno ONC Certification (g)(10) Standardized API Test Kit, we must use the FHIR Proxy.

**Comment by yunwwang** [comment]
@vohuythao I will mark this issue as "question answered" and close it in a few days. If you still have questions about this issue, please either reopen this one or create a new issue. Thank you.
