### ISSUE TITLE
Postgres support not working

### ISSUE THREAD

**Issue by danielki33** [onc-healthit/onc-certification-g10-test-kit#36]
Thanks for the quick turnaround on my last issue/PR!

I tried configuring Postgres using the parameters in the repo template's `config/database.yml`, but got the error `Unable to connect to database: LoadError: cannot load such file pg`.

After some light Googling and trial and error, it seems that the Ruby `pg` package wasn't included anywhere. I was able to get Postgres to work with the following changes:

1. Add the line `spec.add_runtime_dependency 'pg', '~> 1.0'` to `onc_certification_g10_test_kit.gemspec`
2. Install libpg (required by `pg` package) in the `Dockerfile` by adding the line `RUN apt-get install libpq-dev` above the install steps.

I have the changes locally in a branch, and can submit a PR if you'd like, but I'm unsure of whether to submit it here, to the `inferno-template` repo, both, or neither (if you don't want it included by default). Just let me know what works best. 

Thanks,
Daniel

**Comment by yunwwang** [comment]
@danielki33 It has been more than a month so I assume that your question has been addressed. You can reopen this ticket or create a new one if you are still experience the same problem. Thanks.
