### ISSUE TITLE
Configuration Messages Error

### ISSUE THREAD

**Issue by bnjeongwo** [onc-healthit/onc-certification-g10-test-kit#360]
![image](https://user-images.githubusercontent.com/98240947/204350427-e06a730d-34bc-467f-9712-38e5caf67976.png)
![image](https://user-images.githubusercontent.com/98240947/204350557-4853a76b-9f8d-45c3-a15a-5ef6aa9e1f63.png)
Not sure how to fix this error. please i need help.

**Comment by Jammjammjamm** [comment]
Something went wrong with your terminology build. You should delete `tmp/terminology` and `resources/terminology/validators/bloom` and rebuild the terminology.

**Comment by bnjeongwo** [comment]
Rebuilding Terminology Fixed the issue. @Jammjammjamm thanks.
