### ISSUE TITLE
Search test by patient + revInclude:Provenance for Condition includes search test without patient too

### ISSUE THREAD

**Issue by Nbhatin** [onc-healthit/onc-certification-g10-test-kit#365]
Session: https://inferno.healthit.gov/suites/test_sessions/7c909cc4-3a95-4c3b-8e44-a4afe5365570#g10_certification-g10_single_patient_api

test : 4.6.03

The test is supposed to perform a search with patient + other params
Where as it runs two tests : 1) with patient as a parameter and 2) without patient 

I did not notice a similar test in other resource profiles but Condition.
Wanted to understand why is there a special test in conditions for a search without using patient parameter. 
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/63259147/205102032-ea5b8105-7097-4436-925d-e199c2fee67a.png">

**Comment by Jammjammjamm** [comment]
Are you asking why the second request is made?

That is the url for the next page of results. If you look at the response from the first request, you'll see that the Bundle contains that link for the next page. When a search returns enough results that they are split among multiple Bundles, Inferno retrieves them all.

**Comment by Nbhatin** [comment]
Thanks for quick response. 
This answers my question...
