### ISSUE TITLE
Use Refresh Tokens in Inferno

### ISSUE THREAD

**Issue by jj027509** [onc-healthit/onc-certification-g10-test-kit#377]
Would it be possible for inferno to use refresh tokens? Our tokens have a time limit of 10 minutes and that is no longer enough time to run through the 5.0.1 test suite, due to the additional tests. 
As we assume inferno will continue to add tests as ONC requirements expand, it would be helpful if inferno could utilize refresh tokens to account for the additional needed time. 

Thank you!

**Comment by Jammjammjamm** [comment]
Inferno does use refresh tokens.

**Comment by jj027509** [comment]
The  refresh token field in test 6 is not able to be filled out and does not pull forward from the tests that generate the authorization token. 
![image](https://user-images.githubusercontent.com/101205874/207934898-4b482480-c108-479d-a305-0efc85e60a7f.png)

**Comment by Jammjammjamm** [comment]
That will be populated if a refresh token is granted.

![Screen Shot 2022-12-15 at 1 08 43 PM](https://user-images.githubusercontent.com/15969967/207935572-5bb058fc-f15c-445b-a9f2-c3ccd6cfec61.png)

Did the token refresh tests pass?

**Comment by jj027509** [comment]
Yes, the refresh token test passed. 
![image](https://user-images.githubusercontent.com/101205874/207936824-60df38eb-e9a6-4c70-8a65-e92bd36c27e1.png)

**Comment by Jammjammjamm** [comment]
If you look at test 3.6.04, do the outputs contain a refresh token? If you look at this session, you can see that the refresh token from that test is present in the single patient inputs:

![Screen Shot 2022-12-15 at 1 20 58 PM](https://user-images.githubusercontent.com/15969967/207937698-cf4a384e-e97b-4ccb-b629-aa74ca3586d2.png)

![Screen Shot 2022-12-15 at 1 21 23 PM](https://user-images.githubusercontent.com/15969967/207937769-a5e80a76-8ac8-4f04-bc95-0eacfa2d92bc.png)

https://inferno.healthit.gov/suites/test_sessions/ab27d38d-95d6-4f55-ab30-dbadf22bce88#g10_certification-g10_smart_ehr_practitioner_app

**Comment by jj027509** [comment]
hmmm. We do not have a refresh token as part of the output. 
![image](https://user-images.githubusercontent.com/101205874/207938792-4bfe1af2-1afc-4702-b8e5-ce2bd45abacb.png)

**Comment by Jammjammjamm** [comment]
So I'm assuming if you look at the response to the token request in that test, no refresh token was granted, so there is no refresh token available for the client to use.

**Comment by jj027509** [comment]
We have done more investigation and we are granting a refresh token, but it is not being pulled into the system. The output can be seen on 3.3.07 in [this test run](https://inferno.healthit.gov/suites/test_sessions/8aa2ea35-9089-4c7c-b52d-859440334b6d#g10_certification-g10_smart_ehr_practitioner_app), as well as the highlighted portion in the below screenshot.
![image](https://user-images.githubusercontent.com/101205874/208484219-47587c0a-f2e2-4a60-b14e-3522fe2afc3d.png)

**Comment by Jammjammjamm** [comment]
It is going to use the credentials received from refreshing the access token in 3.6.04. If you look at the token request in 3.6.04, it does not contain a refresh token.

![Screen Shot 2022-12-19 at 12 38 25 PM](https://user-images.githubusercontent.com/15969967/208486521-3370ea47-12f2-4d13-8a8d-ede10da99006.png)

**Comment by jj027509** [comment]
I understand that is the current functionality. Is there a possibility to change the functionality? Because there is no requirement to return a new refresh token at that point when a valid token has already been returned in a different portion of the test.

**Comment by Jammjammjamm** [comment]
So in this case the duration of the refresh token is being extended even though a new refresh token is not being granted?

**Comment by jj027509** [comment]
I'm not sure I understand what you mean.
My question is why that refresh token that was granted is not slotted into the single patient tests in the g10 kit. You can copy and paste it into the individual US Core tests, but it doesn't carry through in the g10 test kit and you can't copy it in manually since that field is locked.

**Comment by Jammjammjamm** [comment]
[From the CCG](https://www.healthit.gov/test-method/standardized-api-patient-and-population-services#ccg):
> For subsequent connections, access must be granted...when a valid refresh token is supplied by the application. Additionally, a Health IT Module's authorization server must issue a refresh token valid for a new period of no less than three months to applications capable of storing a client secret.

It is a requirement that when a token is refreshed, the new refresh token has a lifetime of at least three months, so I am asking whether the lifetime of the refresh token is being extended in this case even though a new refresh token is not being issued.

**Comment by Arkitechtual** [comment]
@Jammjammjamm The core issue is the way inferno is implemented.  By not using the refresh token from the initial auth, inferno is enforcing that a refresh token be supplied during the token refresh process which is not a requirement in smart v1.  How we handle the duration of the refresh token is immaterial to the issue raised.   

Per spec: http://hl7.org/fhir/smart-app-launch/1.0.0/#step-5-later-app-uses-a-refresh-token-to-obtain-a-new-access-token

refresh token in response to a refresh request is optional. 

For the record, the refresh token is extended with each use.

**Comment by arscan** [comment]
Right, we shouldn't discard the original refresh token if we do not receive a `refresh_token` claim in the refresh token response.  We can fix that -- thanks for identifying that issue for us.  We had [previously updated the tests](https://github.com/onc-healthit/inferno-program/pull/213) so that systems wouldn't explicitly fail the token refresh tests with this behavior, but we either missed this separate problem or introduced it inadvertently.

@Jammjammjamm's question was motivated by the fact that these tests are in the context of (g)(10), which layers on some requirements on top of SMART, and in that context this behavior is only ok if the duration of the existing refresh token is extended.  Your answer doesn't change that we should fix this behavior in the tests.

**Comment by jj027509** [comment]
Thank you for looking into this, we appreciate it.
