### ISSUE TITLE
Inferno Reference Server: error, invalid client

### ISSUE THREAD

**Issue by dhit-mdavis** [onc-healthit/onc-certification-g10-test-kit#381]
When selecting the Inferno Reference Server preset

1. No patients are showing in the patient selection list
2. I get back an error as a javascript alert saying "invalid client"
![image](https://user-images.githubusercontent.com/56314435/208441074-92fce9af-b763-445c-9708-77d79e0acebf.png)

**Comment by Jammjammjamm** [comment]
We just restarted the server, which should resolve this issue.

**Comment by dhit-mdavis** [comment]
Much appreciated Jamm! I confirmed all is well
![image](https://user-images.githubusercontent.com/56314435/208442859-07e60419-cdd6-4c5f-bedb-0bbd18ed09d2.png)
