### ISSUE TITLE
When server response 4xx with non FHIR JSON payload, Inferno test crashed (FI-1885)

### ISSUE THREAD

**Issue by yunwwang** [onc-healthit/onc-certification-g10-test-kit#397]
When server response 4xx with a non FHIR JSON payload, see the attachment, Inferno test crashed with a purple error.
![image](https://user-images.githubusercontent.com/8761175/215795081-3886e40c-f8e5-48cd-89e1-1dff9650ebc3.png)

What is expected:
Inferno should not crash but shows the correct error message, like server returns 4xx instead of 2xx

**Comment by yunwwang** [comment]
Link to Pull Request: https://github.com/inferno-framework/inferno-core/pull/320

**Comment by Jammjammjamm** [comment]
This has been fixed in core, but the gem extension is still in the US Core and IPA test kits, so it needs to be removed from there.
