### ISSUE TITLE
Slice not matched correctly in US Core 5.0.1 tests for ServiceRequest.category (FI-1914)

### ISSUE THREAD

**Issue by alexzautke** [onc-healthit/onc-certification-g10-test-kit#406]
See https://chat.fhir.org/#narrow/stream/179309-inferno/topic/US.20Core.205.2E0.2E1.20ServiceRequest.20tests

A ServiceRequest with the following category does falsely not match the slice ServiceRequest.catgeory:us-core:

```
"category": [
        {
            "coding": [
                {
                    "system": "http://snomed.info/sct",
                    "code": "409063005",
                    "display": "Counselling"
                }
            ]
        }
    ]
```

**Comment by yunwwang** [comment]
This is an US Core test generator issue. The generator failed to expand valueset.
