### ISSUE TITLE
Unable to find DocumentReference.category in US Core 5.0.1 tests when provided

### ISSUE THREAD

**Issue by bcastillomartel-va** [onc-healthit/onc-certification-g10-test-kit#407]
### What happened?

After running US Core 5.0.1 tests on DocumentReference, Inferno was unable to find DocumentReference.category:us-core when our resource has the category field:

```
 "category": [{
      "coding": [{
          "system": "http://hl7.org/fhir/us/core/CodeSystem/us-core-documentreference-category",
          "code": "clinical-note",
          "display": "Clinical Note"
        }
      ],
      "text": "Clinical Note"
    }
  ]
```

Error message: Could not find identifier, content.format, DocumentReference.category:us-core in the 8 provided DocumentReference resource(s)

**Comment by yunwwang** [comment]
@bcastillomartel-va Did you run tests on inferno.healthit.gov or your local installation? If you run on inferno.healthit.gov, could you provide your test session url? If you don't want to post it here, you could send to inferno@groups.mitre.org. Thank you.

**Comment by bcastillomartel-va** [comment]
Hi @yunwwang, I'll send the test session url to the email you provided. Thank you for your help!

**Comment by bcastillomartel-va** [comment]
@yunwwang I'll also post the test session url here https://inferno.healthit.gov/suites/test_sessions/477e194a-9bce-48d8-9609-b2ccdf646e53#us_core_v501-us_core_v501_document_reference
