### ISSUE TITLE
Public Inferno Validator fails Null type ethnicity

### ISSUE THREAD

**Issue by rberge** [onc-healthit/onc-certification-g10-test-kit#414]
A patient resource with a us core ethnicity that is of the null type fails to validate

Here is an example
{
    "resourceType": "Patient",
    "id": "63e54700b76fa019b592e231",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2023-03-03T21:15:07.549+00:00",
        "source": "file://planet_member_anon.json#EWUGxf9lKemiEKqB",
        "profile": [
            "http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Patient|2.0.0"
        ],
        "tag": [
            {
                "system": "http://green.com/fhir/env",
                "code": "TEST"
            }
        ]
    },
    "language": "en-US",
    "extension": [
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
            "valueCode": "M"
        },
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
            "extension": [
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "http://terminology.hl7.org/CodeSystem/v3-NullFlavor",
                        "code": "ASKU",
                        "display": "asked but unknown"
                    }
                },
                {
                    "url": "text",
                    "valueString": "patient shrugged"
                }
            ]
        },
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
            "extension": [
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "http://terminology.hl7.org/CodeSystem/v3-NullFlavor",
                        "code": "ASKU",
                        "display": "Unknown"
                    }
                },
                {
                    "url": "text",
                    "valueString": "unknown"
                }
            ]
        }
    ],
    "identifier": [
        {
            "use": "official",
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "MB"
                    }
                ]
            },
            "system": "http://green.com/bestco/fhir/planet/memberid",
            "value": "11138201"
        },
        {
            "use": "official",
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "MR"
                    }
                ]
            },
            "system": "http://green.com/fhir/masterpatientindexidentifier",
            "value": "63e54700b76fa019b592e231"
        },
        {
            "use": "official",
            "type": {
                "coding": [
                    {
                        "system": "http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType",
                        "code": "um"
                    }
                ]
            },
            "system": "http://green.com/bestco/fhir/PLANET/uniquememberid",
            "value": "111382"
        },
        {
            "use": "official",
            "type": {
                "coding": [
                    {
                        "system": "http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType",
                        "code": "um"
                    }
                ]
            },
            "system": "http://green.com/bestco/fhir/planet/uniquememberid",
            "value": "111382001"
        }
    ],
    "active": true,
    "name": [
        {
            "use": "usual",
            "text": "Jonathan Jensen",
            "family": "JENSEN",
            "given": [
                "JONATHAN"
            ]
        }
    ],
    "gender": "male",
    "birthDate": "1993-03-14",
    "address": [
        {
            "use": "home",
            "type": "both",
            "text": "4441 VENUS,JUNEAU,AK,99801",
            "line": [
                "4441 VENUS"
            ],
            "city": "JUNEAU",
            "district": "JUNEAU",
            "state": "AK",
            "country": "USA",
            "period": {
                "start": "2020-05-04T09:31:57-04:00"
            }
        }
    ],
    "communication": [
        {
            "language": {
                "coding": [
                    {
                        "system": "urn:ietf:bcp:47",
                        "code": "en-US"
                    }
                ]
            }
        }
    ]
}

This is the error from the validator
Validated the uploaded resource against the http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Patient StructureDefinition
Validation error:
Patient.extension[2].extension[0].value.ofType(Coding): The Coding provided (http://terminology.hl7.org/CodeSystem/v3-NullFlavor#ASKU) is not in the value set 'OMB Ethnicity Categories' (http://hl7.org/fhir/us/core/ValueSet/omb-ethnicity-category|3.1.1), and a code is required from this value set. (error message = Not in value set http://hl7.org/fhir/us/core/ValueSet/omb-ethnicity-category) on line 46. 

I get the same error if I set the ethnicity code to UNK.  
Using this html page as the reference
http://build.fhir.org/ig/HL7/US-Core/ValueSet-omb-ethnicity-category.html

**Comment by yunwwang** [comment]
ASKU and UNK are added in US Core v5.0.1. 

The http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Patient profile is based on US Core v3.1.1 and these codes are not defined in the value set for v3.1.1. Here is the value set:
http://hl7.org/fhir/us/core/STU4/ValueSet-omb-ethnicity-category.html
