### ISSUE TITLE
Inferno should allow customized tests

### ISSUE THREAD

**Issue by bcastillomartel-va** [onc-healthit/onc-certification-g10-test-kit#422]
Our API does not support resources such as `CarePlan`, `CareTeam`, or `Provenance`. Is there a way to exclude these resources when running the US Core 5.0.1 or (g)(10) test suites, or a plan to add this feature?

**Comment by yunwwang** [comment]
For (g)(10) test suites, these resources are required by (g)(10) test procedure and could not be removed.

If you just want to test server conformance to US Core IG, you can use US Core Test kit https://inferno.healthit.gov/suites/
![image](https://user-images.githubusercontent.com/8761175/230930513-260ddd5c-663c-4f0d-b5c9-298bf1319540.png)

Though you cannot remove these tests from the test suite, you can either skip these test groups for these resources, or ignore results from these groups

**Comment by bcastillomartel-va** [comment]
Thank you @yunwwang, we'll stick to the previous version.
