### ISSUE TITLE
'F' is not in the value set 'Birth Sex' - but it actually is

### ISSUE THREAD

**Issue by KevinCranmer** [onc-healthit/onc-certification-g10-test-kit#423]
One of the errors we've received was:

> Patient.extension[2].value.ofType(code): The value provided ('F') is not in the value set 'Birth Sex' (http://hl7.org/fhir/us/core/ValueSet/birthsex|5.0.1), and a code is required from this value set) (error message = Code System URI 'http://hl7.org/fhir/v3/AdministrativeGender' is unknown so the code cannot be validated)

However, when I go to the [linked value set](http://hl7.org/fhir/us/core/ValueSet/birthsex|5.0.1), I see that 'F' is a valid code:
<img width="553" alt="Screenshot 2023-04-14 at 1 49 14 PM" src="https://user-images.githubusercontent.com/51764175/232131318-b2d3a2c6-f257-4b5c-89ae-a1822e33c6ae.png">

Here's the extension object in question:
```
{
      "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
      "valueCode": "F"
}
```

Am I misreading this somehow?

Thanks!

**Comment by KevinCranmer** [comment]
Similar issue for Marital Status:

> Patient.maritalStatus: None of the codings provided are in the value set 'MaritalStatus' (http://hl7.org/fhir/ValueSet/marital-status|4.0.1), and a coding should come from this value set unless it has no suitable code (note that the validator cannot judge what is suitable) (codes = http://hl7.org/fhir/marital-status#M)

<img width="679" alt="Screenshot 2023-04-14 at 2 12 19 PM" src="https://user-images.githubusercontent.com/51764175/232135498-2cdeb7f7-3459-4038-8e1f-73dd3f51546d.png">

Object in question:
```
  "maritalStatus": {
    "coding": [
      {
        "system": "http://hl7.org/fhir/marital-status",
        "code": "M",
        "display": "Married"
      }
    ],
    "text": "Married"
  },
```

Perhaps it's because the system is incorrect?

**Comment by KevinCranmer** [comment]
> Patient.address[0].state: The value provided ('FL') is not in the value set 'USPS Two Letter Alphabetic Codes' (http://hl7.org/fhir/us/core/ValueSet/us-core-usps-state|5.0.1), and a code should come from this value set unless it has no suitable code (note that the validator cannot judge what is suitable) (error message = Local Error: Unable to resolve system https://www.usps.com/. Server Error: Error from server: Unable to resolve value set "http://hl7.org/fhir/us/core/ValueSet/us-core-usps-state|5.0.1")

Looking at http://hl7.org/fhir/us/core/ValueSet/us-core-usps-state|5.0.1 , 'FL' is a valid state code

**Comment by yunwwang** [comment]
Hi @KevinCranmer Did you get these results from US Core Test Kit? If so, these are caused by tx.fhir.org terminology server. Please see this FAQ: https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki/FAQ#q-why-do-some-resources-fail-in-us-core-test-kit-with-terminology-validation-errors

**Comment by KevinCranmer** [comment]
Yes these were from the US Core Test Kit. So must be an issue on the terminology server then

**Comment by yunwwang** [comment]
Yes. That is a known issue between tx.fhir.org (the terminology server) and VSAC (the code system and value set publisher).
