### ISSUE TITLE
"MustSupport references within DocumentReference resources" provides different results

### ISSUE THREAD

**Issue by bcastillomartel-va** [onc-healthit/onc-certification-g10-test-kit#427]
We're currently facing difficulties in comprehending why section 11.12 yields inconsistent results across multiple testing sessions. In the [previous session](https://inferno.healthit.gov/suites/us_core_v501/lzSCMheva56#11), the test passed with a single Practitioner request. However, in the [latest session](https://inferno.healthit.gov/suites/us_core_v501/fhW0sN1Kiug), the section was skipped despite having 41 Practitioner requests, all of which returned a status code of 200. This inconsistency is causing confusion and we're seeking clarification on why the test is now being skipped.

**Comment by bcastillomartel-va** [comment]
<img width="1388" alt="Screenshot 2023-05-03 at 12 55 02 PM" src="https://user-images.githubusercontent.com/106621044/235986201-e0ec0e1c-3b36-4ca6-ab5f-18adfcaedf14.png">

**Comment by bcastillomartel-va** [comment]
<img width="1388" alt="Screenshot 2023-05-03 at 12 55 45 PM" src="https://user-images.githubusercontent.com/106621044/235986384-bfbfdc45-e515-4ecf-90e3-7d01b8133d79.png">

**Comment by yunwwang** [comment]
This is a terminology validation issue. The validation error is on the Practitioner resource. The test result of 39.05 shows error. 

Running validation on tx.fhir.org manually returns the same error: http://tx.fhir.org/r4/CodeSystem/$validate-code?code=MR&system=http://hl7.org/fhir/v2/0203
```
{
      "name" : "message",
      "valueString" : "The CodeSystem http://hl7.org/fhir/v2/0203 is unknown; The provided code http://hl7.org/fhir/v2/0203#MR is not in the value set 'http://hl7.org/fhir/ValueSet/@all'"
    },
```
Further investigation shows that the code system used in the Practitioner resource has a wrong url. The correct url is `http://terminology.hl7.org/CodeSystem/v2-0203` (see https://terminology.hl7.org/CodeSystem-v2-0203.html)

There are some updates on HL7 V2/V3 code systems with the latest terminology.fhir.org. You may double check your resources to comply with these updates.

**Comment by bcastillomartel-va** [comment]
Thank you so much @yunwwang! We'll double check our other resources.
