### ISSUE TITLE
Getting socket error in Multi-Patient authorization tests

### ISSUE THREAD

**Issue by jlgrater** [onc-healthit/onc-certification-g10-test-kit#428]
Hello - We are getting a socket error when running the Multi-Patient tests. Can you help to identify the cause of the error?

Test run is https://inferno.healthit.gov/suites/g10_certification/5ciYEyqR2Lq#7

7.1.02
Authorization request fails when client supplies invalid grant_type
Error: Net::ReadTimeout with #Socket:(closed)
/usr/local/lib/ruby/3.1.0/net/protocol.rb:219:in `rbuf_fill'
7.1.03
Authorization request fails when supplied invalid client_assertion_type
Error: Net::ReadTimeout with #Socket:(closed)
/usr/local/lib/ruby/3.1.0/net/protocol.rb:219:in `rbuf_fill'
7.1.04
Authorization request fails when client supplies invalid JWT token
Error: Net::ReadTimeout with #Socket:(closed)
/usr/local/lib/ruby/3.1.0/net/protocol.rb:219:in `rbuf_fill'
7.1.05
Authorization request succeeds when supplied correct information
Error: Net::ReadTimeout with #Socket:(closed)
/usr/local/lib/ruby/3.1.0/net/protocol.rb:219:in `rbuf_fill'

**Comment by yunwwang** [comment]
Hello @jlgrater: I received time out  when tring backend authorization using the same parameter using Postman. Would you mind to check if the auth url is correct?

![image](https://user-images.githubusercontent.com/8761175/236233193-10f95b33-4b7a-40e4-9b8c-4652d4f03a37.png)

**Comment by yunwwang** [comment]
BTW, the authorization I used for testing is https://fhirstage.fhirpointstage.open.allscripts.com/fhirroute/authorization/ProCertStageCH/connect/token

**Comment by jlgrater** [comment]
I believe the team who owns the authorization endpoint on our side has reached out to you and identified the issue to be in our product. We can close this thread. Thanks for your help!
