### ISSUE TITLE
Multi-Patient API: Client Assertion Claims Suggestions

### ISSUE THREAD

**Issue by mikaelweave** [onc-healthit/onc-certification-g10-test-kit#436]
I'm attempting to integrate the client assertion generated by the test kit with my auth provider. It's strict about the format of the generated client assertion and I have some suggestions after reviewing the [IETF RFC for JWTs](https://datatracker.ietf.org/doc/html/rfc7523).

- Change the `iss` (issuer) claim to something that is unique to the server (URL would be great) that is generating the token vs just the client id of the application. The RFC says *The JWT MUST contain an "iss" (issuer) claim that contains a unique identifier for the entity that issued the JWT.* The client id is not unique to the entity that issues the JWT as it's tied to the client it. I suggest `Inferno::Application[:base_url]`.

- Add the `iat` (issued at) / claim. My auth provider checks to ensure tokens aren't issued for longer than 61 minutes so it requires `iat. This can just be the current date/time when the assertion is generated.

- Add a x5t/x5c claim for IDPs that require certificate based assertions. The kid/x5c claims can be the same.

- Add a `.well-known/openid-connect` endpoint for IDPs that require this to confirm the ownership of the JWK.

 I'm happy to submit a PR but want to ensure agreement first.

Thanks!!

**Comment by Jammjammjamm** [comment]
According the [Bulk Data v1 IG](http://hl7.org/fhir/uv/bulkdata/STU1.0.1/authorization/index.html#protocol-details) and the [SMART App Launch v2 IG](http://hl7.org/fhir/smart-app-launch/client-confidential-asymmetric.html#authenticating-to-the-token-endpoint), the `iss` claim is the client id. I don't see a problem here unless that RFC has a specific definition of "entity" that conflicts with this.

Regarding `iat`, as a general rule, we do not include optional fields as part of the certification tests. If we did, then systems could impose additional requirements on clients by saying they must include fields which the spec says are optional. I think we would be unlikely to make a change here without input from ONC and the authors of the spec.
