### ISSUE TITLE
Example URLs are not allowed in this context Error for identifier field

### ISSUE THREAD

**Issue by Nbhatin** [onc-healthit/onc-certification-g10-test-kit#437]
Hi, 
I am running ONC g(10) test suite with uscore 3.1 version.

Noticed that inferno is giving an error when using identifier.system as "http://acme.com/ids/patients/risks"
Tried the same url using acme.con for other resources and got the same error.
Same error when tried with https://inferno.healthit.gov/validator

However , if I replace acme with something else, it works.

Error: AllergyIntolerance.identifier[0].system: Example URLs are not allowed in this context (http://acme.com/ids/patients/risks) on line 14.

Resource json:
{
    "resourceType": "AllergyIntolerance",
    "id": "A115118",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2023-06-01T18:35:24.602+00:00"
    },
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative</b></p><div style=\"display: inline-block; background-color: #d9e0e7; padding: 6px; margin: 4px; border: 1px solid #8da1b4; border-radius: 5px; line-height: 60%\"><p style=\"margin-bottom: 0px\">Resource &quot;example&quot; </p></div><p><b>identifier</b>: id: 49476534</p><p><b>clinicalStatus</b>: Active <span style=\"background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki\"> (<a href=\"codesystem-allergyintolerance-clinical.html\">AllergyIntolerance Clinical Status Codes</a>#active)</span></p><p><b>verificationStatus</b>: Confirmed <span style=\"background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki\"> (<a href=\"codesystem-allergyintolerance-verification.html\">AllergyIntolerance Verification Status Codes</a>#confirmed)</span></p><p><b>type</b>: allergy</p><p><b>category</b>: food</p><p><b>criticality</b>: high</p><p><b>code</b>: Cashew nuts <span style=\"background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki\"> (<a href=\"https://browser.ihtsdotools.org/\">SNOMED CT</a>#227493005)</span></p><p><b>patient</b>: <a href=\"patient-example.html\">Patient/example</a> &quot;Peter CHALMERS&quot;</p><p><b>onset</b>: 2004</p><p><b>recordedDate</b>: 2014-10-09T14:58:00+11:00</p><p><b>recorder</b>: <a href=\"practitioner-example.html\">Practitioner/example</a> &quot;Adam CAREFUL&quot;</p><p><b>asserter</b>: <a href=\"patient-example.html\">Patient/example</a> &quot;Peter CHALMERS&quot;</p><p><b>lastOccurrence</b>: 2012-06</p><p><b>note</b>: The criticality is high becasue of the observed anaphylactic reaction when challenged with cashew extract.</p><blockquote><p><b>reaction</b></p><p><b>substance</b>: cashew nut allergenic extract Injectable Product <span style=\"background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki\"> (<a href=\"http://terminology.hl7.org/3.1.0/CodeSystem-v3-rxNorm.html\">RxNorm</a>#1160593)</span></p><p><b>manifestation</b>: Anaphylactic reaction <span style=\"background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki\"> (<a href=\"https://browser.ihtsdotools.org/\">SNOMED CT</a>#39579001)</span></p><p><b>description</b>: Challenge Protocol. Severe reaction to subcutaneous cashew extract. Epinephrine administered</p><p><b>onset</b>: 2012-06-12</p><p><b>severity</b>: severe</p><p><b>exposureRoute</b>: Subcutaneous route <span style=\"background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki\"> (<a href=\"https://browser.ihtsdotools.org/\">SNOMED CT</a>#34206005)</span></p></blockquote><blockquote><p><b>reaction</b></p><p><b>manifestation</b>: Urticaria <span style=\"background: LightGoldenRodYellow; margin: 4px; border: 1px solid khaki\"> (<a href=\"https://browser.ihtsdotools.org/\">SNOMED CT</a>#64305001)</span></p><p><b>onset</b>: 2004</p><p><b>severity</b>: moderate</p><p><b>note</b>: The patient reports that the onset of urticaria was within 15 minutes of eating cashews.</p></blockquote></div>"
    },
    "identifier": [
        {
            "system": "http://acme.com/ids/patients/risks",
            "value": "49476534"
        }
    ],
    "clinicalStatus": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical",
                "code": "active",
                "display": "Active"
            }
        ]
    },
    "verificationStatus": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-verification",
                "code": "confirmed",
                "display": "Confirmed"
            }
        ]
    },
    "type": "allergy",
    "category": [
        "food"
    ],
    "criticality": "high",
 "code": {
        "coding": [
            {
                "system": "http://snomed.info/sct",
                "code": "762952008",
                "display": "Peanut"
            }
        ]
    },
    "patient": {
        "reference": "Patient/A78238"
    },
    "onsetDateTime": "2004",
    "recordedDate": "2014-10-09T14:58:00+11:00",
    "lastOccurrence": "2012-06",
    "note": [
        {
            "text": "The criticality is high becasue of the observed anaphylactic reaction when challenged with cashew extract."
        }
    ]
}

**Comment by yunwwang** [comment]
Very interesting. This is coming from FHIR validator:

```
          } else if (url.contains("example.org") || url.contains("acme.com")) {
            ok = rule(errors, NO_RULE_DATE, IssueType.INVALID, e.line(), e.col(), path, false, I18nConstants.TYPE_SPECIFIC_CHECKS_DT_URL_EXAMPLE, url) && ok;;
```
https://github.com/hapifhir/org.hl7.fhir.core/blob/60fe0fd0f89f5a163fff4fd1373c3f55574da2cc/org.hl7.fhir.validation/src/main/java/org/hl7/fhir/validation/instance/InstanceValidator.java#LL2691C16-L2691C16

I don't know why it singles out "acme.com". 

You can raise an issue to that github repo.
