### ISSUE TITLE
Inferno G10 not pulling in correct default scopes

### ISSUE THREAD

**Issue by richfirely** [onc-healthit/onc-certification-g10-test-kit#445]
Hi,
Please see this test https://inferno.healthit.gov/suites/g10_certification/1L90gjrye1o
Core 5. Smart 2, Bulk 2.

When you navigate to the Start for standalone, the scopes listed are for US Core 4.

It seems like the presets didn't get loaded correctly
https://github.com/onc-healthit/onc-certification-g10-test-kit/blob/main/config/presets/inferno_reference_server_preset.json

**Comment by yunwwang** [comment]
@richfirely Sorry for the late reply. Could you specify what scopes are incorrect? I just checked current inferno.healthit.gov, the scopes looks correct.

**Comment by yunwwang** [comment]
Closed as no further feedback
