### ISSUE TITLE
Get outbound IP for https://inferno.healthit.gov/

### ISSUE THREAD

**Issue by Nbhatin** [onc-healthit/onc-certification-g10-test-kit#446]
Hi, 

So far I have been using local instance of inferno to test our fhir server.
But in order to run my tests on public inferno instance, I would need  https://inferno.healthit.gov/ outbound ip address to white list it on our fhir server's firewall.

Could you please help here.

**Comment by yunwwang** [comment]
Hello @Nbhatin We don't have that information. I think your IT team should have the ip address of incoming requests.

**Comment by Nbhatin** [comment]
nvm.. got it working. Thanks
