### ISSUE TITLE
8.3.10 Device resources returned conform to the US Core Implantable Device Profile No Device resource file item returned by server.

### ISSUE THREAD

**Issue by nksainiroorkee** [onc-healthit/onc-certification-g10-test-kit#472]
Hello Guys,

We are not able to group export "device" resource while added device data has passed the inferno test for a single patient, but group export is giving me "No device resource file item returned by server."

HAPI-0512: Resource types [Device] are invalid for this type of export, as they do not contain search parameters that refer to patients.

**Comment by yunwwang** [comment]
(g)(10) Bulk Data export is a Group export, as defined [here](https://hl7.org/fhir/uv/bulkdata/STU1.0.1/export/index.html#endpoint---group-of-patients). The error message indicates that HAPI server expects some kind of patient reference. Please check HAPI server maual for the settings or requirements to process group export as defined by Bulk Data IG.
