### ISSUE TITLE
Could not determine profile of PractitionerRole (US Core 5.0.1) (FI-2481/2483)

### ISSUE THREAD

**Issue by cheng13231** [onc-healthit/onc-certification-g10-test-kit#477]
When running tests with combination of US Core 5.0.1 / USCDI v2, SMART App Launch 2.0.0, Bulk Data 2.0.0, test 8.3.27 is skipped. See screenshot below for the error message. It is not clear to me where goes wrong.

![image](https://github.com/onc-healthit/onc-certification-g10-test-kit/assets/81763984/85352195-17f7-47fe-93c1-301ee9136a0a)

I'm running inferno g(10) v4.1.0 locally, the testing PractionerRole resource is returned from Bulk Data Export request and it looks normal to me. Here is the resource that I used

`{"resourceType":"PractitionerRole","id":"test","meta":{"profile":["http://hl7.org/fhir/us/core/StructureDefinition/us-core-practitionerrole"],"versionId":"002863e2-cee2-499a-8f75-9f332c1ca742","lastUpdated":"2023-09-14T16:00:41.638+00:00"},"practitioner":{"reference":"Practitioner/test"},"organization":{"reference":"Organization/test"},"code":[{"coding":[{"system":"http://nucc.org/provider-taxonomy","code":"101200000X","display":"Drama Therapist"}]}],"specialty":[{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/v3-HealthcareProviderTaxonomyHIPAA","code":"101Y00000N","display":"Behavioral Health & Social Service; Counselor"}]}],"location":[{"reference":"Location/test"}],"healthcareService":[{"reference":"HealthcareService/test"}],"telecom":[{"system":"email","value":"example@fire.ly"}],"endpoint":[{"reference":"Endpoint/test"}]}`

**Comment by yunwwang** [comment]
Hello @cheng13231, Sorry for the late reply. We are investing this issue. It looks like a design bug in our code.

**Comment by yunwwang** [comment]
This should be solved as part of #485
