### ISSUE TITLE
error prop is required in the Multy-Patient API $export-status operation

### ISSUE THREAD

**Issue by ddegr** [onc-healthit/onc-certification-g10-test-kit#486]
We tested our solution against `7 Multi-Patient Authorization and API` and caught an error in the `$export-status` operation.

**Inferno says**
The JSON object of Complete Status SHALL contain these required field: transactionTime, request, requiresAccessToken, output, and error.

**Our approach**
We remove the `error` when it is empty to sanitize the output.

**The question**
Is this a bug in the Inferno test cases? Why not simply check for the existence of the `error` when necessary?

### Test launch context

ONC Certification (g)(10) Standardized API v.5.0.0
US Core 3.1.1 / USCDI v1, SMART App Launch 1.0.0, Bulk Data 1.0.1
Inferno Built with v.0.4.26

**Comment by yunwwang** [comment]
Hello @ddegr: Thank you for reaching to us about bulk data testing question. 

`error` field is **required** by Bulk Data IG Section [2.5.5.4](https://build.fhir.org/ig/HL7/bulk-data/export.html#response---complete-status):

![image](https://github.com/onc-healthit/onc-certification-g10-test-kit/assets/8761175/16393210-e43e-453c-98c6-17f81e7d9478)

Inferno testing has to follow this requirement in IG. If you have comment about this requirement, you can raise a FHIR JIRA ticket for the IG author to consider. To raise a FHIR JIRA ticket, go to the bottom of IG and click "Propose a change"

![image](https://github.com/onc-healthit/onc-certification-g10-test-kit/assets/8761175/2cb2153b-2426-4407-9ced-e192ab5cd830)

**Comment by ddegr** [comment]
@yunwwang thanks you very much. It is clear now
