### ISSUE TITLE
Make 403 error to pass "SMART Invalid ..." tests 

### ISSUE THREAD

**Issue by bholyshevskyi** [onc-healthit/onc-certification-g10-test-kit#495]
We use Auth0 for authentication in our project. When running `ONC Certification (g)(10) Standardized API V.5.1.0
 (US Core 6.1.0 / USCDI v3, SMART App Launch 2.0.0, Bulk Data 2.0.0)` tests. Some tests which assert invalid auth flow fail because 403 is not counted as expected result.
The tests are:
![image](https://github.com/onc-healthit/onc-certification-g10-test-kit/assets/114926438/9caf5b7c-4963-4c22-91a5-0b8b0c6e9f48)
![image](https://github.com/onc-healthit/onc-certification-g10-test-kit/assets/114926438/34688fd4-226d-4a9f-98f1-b82ca97b2ee3)
![image](https://github.com/onc-healthit/onc-certification-g10-test-kit/assets/114926438/6993d81c-5eef-4bcd-963e-b40fa4725b80)
![image](https://github.com/onc-healthit/onc-certification-g10-test-kit/assets/114926438/ddc4f2b5-1244-4ce2-9611-fc68fe50d7cc)
![image](https://github.com/onc-healthit/onc-certification-g10-test-kit/assets/114926438/289a54e1-f042-46a1-9b70-e337ce4365e1)

Is it possible to make returned 403 error to pass the tests above?

**Comment by yunwwang** [comment]
@bholyshevskyi:

Thank you for reach to us for this Inferno test issue.

The designated response code(s) are outlined in RFC-6749 "The OAuth 2.0 Authorization Framework," specifically in [Section 5.2](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2). 

> The authorization server responds with an HTTP 400 (Bad Request)
>    status code (unless specified otherwise) and includes the following
>    parameters with the response:

Should there be a consideration to include an HTTP 403 status code, please inform us of the corresponding standard that supports this inclusion.

**Comment by yunwwang** [comment]
Closed as question answered
