### ISSUE TITLE
US Core v6.1.0 Tests treat Patient name.period as MS (FI-2534)

### ISSUE THREAD

**Issue by jwjahns** [onc-healthit/onc-certification-g10-test-kit#496]
Hello,

The US Core 6.1.0 tests are considering Patient `name.period` as MS in test 10.2.09:
![image](https://github.com/onc-healthit/onc-certification-g10-test-kit/assets/83475323/a339cf27-6a6e-462f-9a55-39f193e10797)

This does not seem to be a requirement of US Core or USCDI. This is distinct from the additional USCDI MS requirement of `name.period.end or name.use = old`, which is the requirement called out more specifically in US Core (for communicating a "previous name").

In the above image, a patient with `name.use = old` was provided, but the MS error was still shown. 

Related chat.fhir.org thread:
https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Patient.20name.2Eperiod.20MS.20-.20US.20Core.206.2E1.2E0

**Comment by yunwwang** [comment]
In US Core v6.1.0, `Patient.name.period` is marked as `USCDI` element while the narrative section states `Patient.name.period.end` be one of choice for Patient's previous name. That inconsistentcy between structure definition and narrative causes this issue.

Resolution: 
* Will move `MS/USCDI` tag from `Patient.name.period` to `Patient.name.period.end` in Inferno metadata. 

Effect:
* Compatible. This change does not cause any new failure for already certified system.
