### ISSUE TITLE
Minor Typo in Release Notes

### ISSUE THREAD

**Issue by dhit-mdavis** [onc-healthit/onc-certification-g10-test-kit#503]
First off, I appreciate the release notes being provided, especially when it mentions changes that may cause systems to fail due to changes.

Secondly, please see the word "eithing" below and confirm if it is a typo or not.

![image](https://github.com/onc-healthit/onc-certification-g10-test-kit/assets/56314435/28a7cdee-2566-4efc-8b7a-81059cedeba5)

Thanks - Mat

**Comment by Jammjammjamm** [comment]
Thank you for bringing this to our attention. The release notes have been updated.
