### ISSUE TITLE
Error during 5.4.0 Setup

### ISSUE THREAD

**Issue by BryanWork** [onc-healthit/onc-certification-g10-test-kit#512]
When attempting to setup 5.4.0, I get an error and I'm not sure how to resolve it.  In WSL this is what I am seeing.

sh setup.sh

cannot extend service "validator_service" in docker-compose.background.yml: service not found
cannot extend service "validator_service" in docker-compose.background.yml: service not found
cannot extend service "validator_service" in docker-compose.background.yml: service not found

The change log for 5.4.0 says the validator version was increased.  I wonder if that could be the root cause of this issue.  setup.sh works as expected with version 5.3.0.

Thanks,
Bryan

**Comment by dehall** [comment]
Hi, yes confirmed I'm seeing the same thing. Not sure how that happened. We'll formally release a fix as soon as we can but if you want to try to correct it yourself in the meantime you can either delete or comment out (add a # in front of) each of the following lines in the file docker-compose.yml:

line 10:
```
- validator_service
```

lines 19-22:
```
  validator_service:
    extends:
      file: docker-compose.background.yml
      service: validator_service
```

**Comment by BryanWork** [comment]
Thanks for your quick reply.  Yesterday we came up with a very similar fix and it seems to have worked correctly but I will go ahead and try your exact solution.  Below are the changes that we came up with.  We don't know if uncommenting the hl7_validator_service made a difference or not.

docker-compose.yml

...
depends_on:
      - hl7_validator_service
    #  - validator_service
...
#validator_service:
  #  extends:
  #    file: docker-compose.background.yml
  #    service: validator_service

**Comment by dehall** [comment]
Your fix is more technically correct (and what we're implementing for our fixed release) so no need to change anything further if you have it working. I just simplified a little for the quick fix mentioned above. In practice you shouldn't see a difference based on uncommenting the depends_on: - hl7_validator_service line , that just helps to ensure the services start up in the right order, but that one starts up quickly enough it usually doesn't matter.

**Comment by BryanWork** [comment]
Good to know,
By the way we are much happier with this version because it resolved some bugs that caused some of the tests to fail locally that would pass on the online testing tool.
Thanks so much,
Bryan
