### ISSUE TITLE
9.10.12 Visual Inspection and Attestation 

### ISSUE THREAD

**Issue by bink1lala** [onc-healthit/onc-certification-g10-test-kit#515]
Good Day, 
Is there a 9.10.12 Visual Inspection and Attestation ? 
If so, what options trigger it? 
I have attempted multiple combinations upon sign in and 9.10.12 Visual Inspection and Attestation does not generate. 
Am I missing something? Or is 9.10.12 skipped? 

Please advise. 

Thank you

**Comment by yunwwang** [comment]
9.10.12 was the old test for Patient's previous name in US Core v3.1.1. This test has been merged into Patien test group.

https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/416

**Comment by bink1lala** [comment]
Thank you for the quick response!
