### ISSUE TITLE
Error: mimetype not found

### ISSUE THREAD

**Issue by SavannahDearing** [onc-healthit/onc-certification-g10-test-kit#523]
Error reported:
DiagnosticReport/fc5054c7-19d1-4d62-acd3-8862230c6548: DiagnosticReport.presentedForm[0].contentType: The System URI could not be determined for the code '**application/pdf**' in the ValueSet '[http://hl7.org/fhir/ValueSet/mimetypes|4.0.1](http://hl7.org/fhir/ValueSet/mimetypes%7C4.0.1)': include #0 has system urn:ietf:bcp:13 which could not be found, and the server returned error [Error from http://tx.fhir.org/r4: The code System "urn:ietf:bcp:13" has a grammar, and cannot be enumerated directly]

I'm trying to figure out if this is a problem with the validator not able to retrieve the mimetypes, or if 'application/pdf' is no longer accepted.

Thanks!

**Comment by Jammjammjamm** [comment]
Are you encountering this on inferno.healthit.gov?

**Comment by SavannahDearing** [comment]
yes
https://inferno.healthit.gov/suites/g10_certification/35jmkqBeT1y#g10_certification-multi_patient_api
sorry, I should have added the link in my previous post!

**Comment by Jammjammjamm** [comment]
That does indicate an issue with the validator rather than your system, but I'm not seeing that issue when I run tests right now. If you rerun your tests, do you still see the error?

**Comment by SavannahDearing** [comment]
OK I retested and no longer see this message.  That was an easy "fix" ;D 

Thanks!~

**Comment by Jammjammjamm** [comment]
Ok, we are still investigating this issue as we have seen it pop up periodically.

**Comment by SavannahDearing** [comment]
FYI, catching it again today:
https://inferno.healthit.gov/suites/g10_certification/13CPfpXPb9U
