### ISSUE TITLE
Inferno Test Cases 5.1.02 , 5.9.07, 5.10.08, 7.3.11 and 7.3.12 are failing with  Error: application/fhir+json or application/pdf mimetype not found for  Capability Statement for the FHIR server

### ISSUE THREAD

**Issue by Saiyed-GWHI** [onc-healthit/onc-certification-g10-test-kit#524]
**Description**: We are getting following errors  on https://inferno.healthit.gov/
**Test Case 5.1.02**
CapabilityStatement: CapabilityStatement.format[0]: The System URI could not be determined for the code 'application/fhir+json' in the ValueSet '[http://hl7.org/fhir/ValueSet/mimetypes|4.0.1](http://hl7.org/fhir/ValueSet/mimetypes%7C4.0.1)': include #0 has system urn:ietf:bcp:13 which could not be found, and the server returned error [Error from http://tx.fhir.org/r4: The code System "urn:ietf:bcp:13" has a grammar, and cannot be enumerated directly]
CapabilityStatement: CapabilityStatement.format[0]: The value provided ('application/fhir+json') was not found in the value set 'MimeType' ([http://hl7.org/fhir/ValueSet/mimetypes|4.0.1](http://hl7.org/fhir/ValueSet/mimetypes%7C4.0.1)), and a code is required from this value set (error message = The System URI could not be determined for the code 'application/fhir+json' in the ValueSet '[http://hl7.org/fhir/ValueSet/mimetypes|4.0.1](http://hl7.org/fhir/ValueSet/mimetypes%7C4.0.1)': include #0 has system urn:ietf:bcp:13 which could not be found, and the server returned error [Error from http://tx.fhir.org/r4: The code System "urn:ietf:bcp:13" has a grammar, and cannot be enumerated directly]; None of the provided codes ['#application/fhir+json'] are in the value set '[http://hl7.org/fhir/ValueSet/mimetypes|4.0.1](http://hl7.org/fhir/ValueSet/mimetypes%7C4.0.1)')

**Test Case 7.3.11**
DiagnosticReport/028607558944a937eb1a06b21b43075d85d0d811: DiagnosticReport.presentedForm[0].contentType: The value provided ('application/pdf') was not found in the value set 'MimeType' (http://hl7.org/fhir/ValueSet/mimetypes\|4.0.1), and a code is required from this value set (error message = The System URI could not be determined for the code 'application/pdf' in the ValueSet 'http://hl7.org/fhir/ValueSet/mimetypes\|4.0.1': include #0 has system urn:ietf:bcp:13 which could not be found, and the server returned error [Error from http://tx.fhir.org/r4: The code System "urn:ietf:bcp:13" has a grammar, and cannot be enumerated directly]; None of the provided codes ['#application/pdf'] are in the value set 'http://hl7.org/fhir/ValueSet/mimetypes\|4.0.1')
![ONC1](https://github.com/onc-healthit/onc-certification-g10-test-kit/assets/174034191/137f8e4f-a770-4b9a-bb85-bddf1cf29b89)
![ONC2](https://github.com/onc-healthit/onc-certification-g10-test-kit/assets/174034191/e46f82f0-5ac1-4d6c-bbab-4037fa8ac9e8)
![ONC3](https://github.com/onc-healthit/onc-certification-g10-test-kit/assets/174034191/5b769056-dc83-4761-bb44-5230e5bef208)

 
We have observed that this error stared occurring from 25 June 2024 before that it was working fine. We have also check at our system and noting changed in last two days in our fhir system.
We have also captured the response body json(CapabilityStatement resource) received in test case 5.1.02 and tried to validate  inferno validator https://infernotest.healthit.gov/validator with US Core Implementation Guide and it validated successfully without error.

Test case link https://inferno.healthit.gov/suites/g10_certification/4HcNVO1fZC2#5

**Comment by arscan** [comment]
@Saiyed-GWHI thanks for the report.  We've recently had an intermittent problem in our shared FHIR validator service on inferno.healthit.gov where it seems to cache bad terminology validation data, though its hard to track down exactly how or why that it is happening. The intermittent nature of the issue has made it hard to reproduce and fix.

We do not believe this affects users that run the g10 test kit locally.

I restarted the service and it appears to have fixed the issue for now -- could you let me know if it is working for you now or if you still have the same problem?

Thanks,
Rob

**Comment by Saiyed-GWHI** [comment]
Today We have run inferno test cases and mime type issue started appearing again.

**Comment by dletter** [comment]
Any updates on this getting updated/fixed on https://inferno.healthit.gov/

**Comment by yunwwang** [comment]
This has been fixed in v7.2.5
