### ISSUE TITLE
US Core CapabilityStatement Validation Checks on Canonical URLs + Versioning (FI-2497)

### ISSUE THREAD

**Issue by weiyuzh** [onc-healthit/onc-certification-g10-test-kit#525]
Currently, the US Core 6.1.0 CapabilityStatement tests validates that the server under test declares support for US Core profiles in `CapabilityStatement.instantiates`  and `CapabilityStatement.rest.resource.supportedProfile`.

These fields are validated against non-versioned canonical URLs (e.g. `CapbilityStatement.instantiates` must include `http://hl7.org/fhir/us/core/CapabilityStatement/us-core-server`), and versioned canonical URLs will not pass the test (e.g. `CapabilityStatemnt.instantiates` with only `http://hl7.org/fhir/us/core/CapabilityStatement/us-core-server|6.1.0` will fail the test).

(Defer to the community on the usefulness of versioned canonical URLs in the CapabilityStatement - see [https://chat.fhir.org/#narrow/stream/179309-inferno/topic/US.20Core.206.2E1.2E0.20.2B.20CapabilityStatement.20Canonical.20URLs](https://chat.fhir.org/#narrow/stream/179309-inferno/topic/US.20Core.206.2E1.2E0.20.2B.20CapabilityStatement.20Canonical.20URLs) for more discussion)

**Comment by yunwwang** [comment]
We will update testing logic to ignore version postfix in canonical urls for both elements.
