### ISSUE TITLE
HTI-1 US Core v6.1.0 giving terminology error on 2.20.08 

### ISSUE THREAD

**Issue by jj027509** [onc-healthit/onc-certification-g10-test-kit#532]
We are receiving an error indicating incorrect SNOMED codes on Observation Pregnancy Intent Tests 2.20.08 
[Inferno Run](https://inferno.healthit.gov/suites/us_core_v610/gyJjEc14CiO#2.20)

From our examination, it does appear we are sending a valid SNOMED code of 454401000124105.

**Comment by yunwwang** [comment]
Hello @jj027509 This is a know error on tx.fhir.org (see this zulip thread: https://chat.fhir.org/#narrow/stream/179202-terminology/topic/pregnancy-intent.20validation.20failure/near/394649688)

Inferno US Core Test Kit relies on tx.fhir.org (which is maintained by HL7) for terminology validation. Please see this FAQ about terminology validation errors (https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki/FAQ#q-why-do-some-resources-fail-in-us-core-test-kit-with-terminology-validation-errors)

Inferno g10 Certification Test Kit uses its own terminology service which removes this dependency.

**Comment by yunwwang** [comment]
Yes. tx.fhir.org returns the same error on 454411000124108

https://tx.fhir.org/r4/ValueSet/us-core-pregnancy-intent/$validate-code?code=454411000124108&system=http://snomed.info/sct

You can reply to the zulip thread to let Grahame know the issue still exists.

While waiting for tx server to fix, you can just ignore the error if you are certain the code provided is correct (as in this case)

**Comment by jj027509** [comment]
Will do, thank you!
