### ISSUE TITLE
Terminology build error - "SQLite3::SQLException: no such table: test_sessions: SELECT * FROM `test_sessions`" (FI-1510)

### ISSUE THREAD

**Issue by dkriebel** [onc-healthit/onc-certification-g10-test-kit#54]
When I attempt building the terminology I am getting a SQLite exception and the build process exits soon after. Per the instructions I have our API key in the .env file and have run setup.sh and run.sh prior to running the command `docker-compose -f terminology_compose.yml up`

Below is the full log from running this:

`WARNING: Found orphan containers (onc-certification-g10-test-kit-main_inferno_1, onc-certification-g10-test-kit-main_redis_1, onc-certification-g10-test-kit-main_worker_1, onc-certification-g10-test-kit-main_validator_service_1, onc-certification-g10-test-kit-main_nginx_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting onc-certification-g10-test-kit-main_terminology_builder_1 ... done
Attaching to onc-certification-g10-test-kit-main_terminology_builder_1
terminology_builder_1  | Prepare version 2019
terminology_builder_1  | /usr/local/bundle/gems/pry-byebug-3.8.0/lib/pry-byebug/control_d_handler.rb:5: warning: control_d_handler's arity of 2 parameters was deprecated (eval_string, pry_instance). Now it gets passed just 1 parameter (pry_instance)
terminology_builder_1  | I, [2022-03-24T19:06:50.898969 #13]  INFO -- : (0.001601s) PRAGMA foreign_keys = 1
terminology_builder_1  | I, [2022-03-24T19:06:50.899069 #13]  INFO -- : (0.000028s) PRAGMA case_sensitive_like = 1
terminology_builder_1  | E, [2022-03-24T19:06:50.903994 #13] ERROR -- : SQLite3::SQLException: no such table: test_sessions: SELECT * FROM 'test_sessions' LIMIT 1
terminology_builder_1  | rake aborted!
terminology_builder_1  | Sequel::DatabaseError: SQLite3::SQLException: no such table: test_sessions
terminology_builder_1  | /usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in 'initialize'
terminology_builder_1  | /usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in 'new'
terminology_builder_1  | /usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in 'prepare'
terminology_builder_1  | /usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:336:in 'query'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/adapters/sqlite.rb:200:in 'block (2 levels) in _execute'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/database/logging.rb:43:in 'log_connection_yield'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/adapters/sqlite.rb:200:in 'block in _execute'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/connection_pool/threaded.rb:88:in 'hold'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/database/connecting.rb:269:in 'synchronize'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/adapters/sqlite.rb:193:in '_execute'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/adapters/sqlite.rb:139:in 'execute'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/dataset/actions.rb:1093:in 'execute'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/adapters/sqlite.rb:327:in 'fetch_rows'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/dataset/actions.rb:152:in 'each'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/dataset/actions.rb:86:in 'columns!'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/dataset/actions.rb:76:in 'columns'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:242:in 'columns'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:788:in 'block (2 levels) in get_db_schema'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:686:in 'block in check_non_connection_error'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/database/transactions.rb:201:in 'block in transaction'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/connection_pool/threaded.rb:92:in 'hold'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/database/connecting.rb:269:in 'synchronize'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/database/transactions.rb:195:in 'transaction'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:686:in 'check_non_connection_error'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:788:in 'block in get_db_schema'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:821:in 'get_db_schema'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:606:in 'set_dataset'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:192:in 'Model'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:140:in 'block in def_Model'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno/repositories/test_sessions.rb:40:in '<class:TestSessions>'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno/repositories/test_sessions.rb:6:in '<module:Repositories>'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno/repositories/test_sessions.rb:4:in '<module:Inferno>'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno/repositories/test_sessions.rb:3:in '<top (required)>'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno/entities/test_group.rb:3:in 'require_relative'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno/entities/test_group.rb:3:in '<top (required)>'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno/entities.rb:10:in 'require_relative'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno/entities.rb:10:in '<top (required)>'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno.rb:9:in 'require_relative'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno.rb:9:in '<top (required)>'
terminology_builder_1  | /opt/inferno/lib/onc_certification_g10_test_kit/tasks/generate_matrix.rb:3:in 'require'
terminology_builder_1  | /opt/inferno/lib/onc_certification_g10_test_kit/tasks/generate_matrix.rb:3:in '<top (required)>'
terminology_builder_1  | /opt/inferno/Rakefile:7:in 'require_relative'
terminology_builder_1  | /opt/inferno/Rakefile:7:in '<top (required)>'
terminology_builder_1  | /usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in '<top (required)>'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in 'load'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in 'kernel_load'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:23:in 'run'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli.rb:483:in 'exec'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in 'run'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'invoke_command'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor.rb:392:in 'dispatch'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli.rb:31:in 'dispatch'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in 'start'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli.rb:25:in 'start'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/exe/bundle:48:in 'block in <top (required)>'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/friendly_errors.rb:103:in 'with_friendly_errors'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/exe/bundle:36:in '<top (required)>'
terminology_builder_1  | /usr/local/bundle/bin/bundle:23:in 'load'
terminology_builder_1  | /usr/local/bundle/bin/bundle:23:in '<main>'
terminology_builder_1  |
terminology_builder_1  | Caused by:
terminology_builder_1  | SQLite3::SQLException: no such table: test_sessions
terminology_builder_1  | /usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in 'initialize'
terminology_builder_1  | /usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in 'new'
terminology_builder_1  | /usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in 'prepare'
terminology_builder_1  | /usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:336:in 'query'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/adapters/sqlite.rb:200:in 'block (2 levels) in _execute'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/database/logging.rb:43:in 'log_connection_yield'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/adapters/sqlite.rb:200:in 'block in _execute'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/connection_pool/threaded.rb:88:in 'hold'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/database/connecting.rb:269:in 'synchronize'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/adapters/sqlite.rb:193:in '_execute'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/adapters/sqlite.rb:139:in 'execute'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/dataset/actions.rb:1093:in 'execute'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/adapters/sqlite.rb:327:in 'fetch_rows'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/dataset/actions.rb:152:in 'each'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/dataset/actions.rb:86:in 'columns!'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/dataset/actions.rb:76:in 'columns'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:242:in 'columns'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:788:in 'block (2 levels) in get_db_schema'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:686:in 'block in check_non_connection_error'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/database/transactions.rb:201:in 'block in transaction'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/connection_pool/threaded.rb:92:in 'hold'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/database/connecting.rb:269:in 'synchronize'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/database/transactions.rb:195:in 'transaction'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:686:in 'check_non_connection_error'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:788:in 'block in get_db_schema'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:821:in 'get_db_schema'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:606:in 'set_dataset'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:192:in 'Model'
terminology_builder_1  | /usr/local/bundle/gems/sequel-5.42.0/lib/sequel/model/base.rb:140:in 'block in def_Model'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno/repositories/test_sessions.rb:40:in '<class:TestSessions>'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno/repositories/test_sessions.rb:6:in '<module:Repositories>'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno/repositories/test_sessions.rb:4:in '<module:Inferno>'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno/repositories/test_sessions.rb:3:in '<top (required)>'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno/entities/test_group.rb:3:in 'require_relative'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno/entities/test_group.rb:3:in '<top (required)>'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno/entities.rb:10:in 'require_relative'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno/entities.rb:10:in '<top (required)>'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno.rb:9:in 'require_relative'
terminology_builder_1  | /usr/local/bundle/gems/inferno_core-0.2.0/lib/inferno.rb:9:in '<top (required)>'
terminology_builder_1  | /opt/inferno/lib/onc_certification_g10_test_kit/tasks/generate_matrix.rb:3:in 'require'
terminology_builder_1  | /opt/inferno/lib/onc_certification_g10_test_kit/tasks/generate_matrix.rb:3:in '<top (required)>'
terminology_builder_1  | /opt/inferno/Rakefile:7:in 'require_relative'
terminology_builder_1  | /opt/inferno/Rakefile:7:in '<top (required)>'
terminology_builder_1  | /usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in '<top (required)>'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in 'load'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in 'kernel_load'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:23:in 'run'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli.rb:483:in 'exec'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in 'run'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'invoke_command'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor.rb:392:in 'dispatch'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli.rb:31:in 'dispatch'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in 'start'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli.rb:25:in 'start'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/exe/bundle:48:in 'block in <top (required)>'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/friendly_errors.rb:103:in 'with_friendly_errors'
terminology_builder_1  | /usr/local/bundle/gems/bundler-2.3.9/exe/bundle:36:in '<top (required)>'
terminology_builder_1  | /usr/local/bundle/bin/bundle:23:in 'load'
terminology_builder_1  | /usr/local/bundle/bin/bundle:23:in '<main>'
terminology_builder_1  | (See full trace by running task with --trace)
onc-certification-g10-test-kit-main_terminology_builder_1 exited with code 1`

**Comment by Jammjammjamm** [comment]
Have you run `setup.sh`? That should setup the database.

**Comment by dkriebel** [comment]
I have - a few times at this point. This is the output of that.

```
Pulling validator_service ... done
Pulling inferno           ... done
Pulling nginx             ... done
Pulling redis             ... done
Pulling worker            ... done
validator_service uses an image, skipping
nginx uses an image, skipping
redis uses an image, skipping
Building inferno
[+] Building 2.2s (14/14) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 38B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 35B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/ruby:2.7.3                                                      1.5s
 => [1/9] FROM docker.io/library/ruby:2.7.3@sha256:ee2b19ced1d44600963c52691b9b6975e209286e7168230d03afe7894f9c81  0.0s
 => [internal] load build context                                                                                  0.4s
 => => transferring context: 9.22kB                                                                                0.4s
 => CACHED [2/9] RUN mkdir -p /opt/inferno/                                                                        0.0s
 => CACHED [3/9] WORKDIR /opt/inferno/                                                                             0.0s
 => CACHED [4/9] ADD *.gemspec /opt/inferno/                                                                       0.0s
 => CACHED [5/9] ADD Gemfile* /opt/inferno/                                                                        0.0s
 => CACHED [6/9] ADD lib/onc_certification_g10_test_kit/version.rb /opt/inferno//lib/onc_certification_g10_test_k  0.0s
 => CACHED [7/9] RUN gem install bundler                                                                           0.0s
 => CACHED [8/9] RUN bundle install                                                                                0.0s
 => [9/9] ADD . /opt/inferno/                                                                                      0.1s
 => exporting to image                                                                                             0.1s
 => => exporting layers                                                                                            0.1s
 => => writing image sha256:8028db923977edda688cc57a4c257ee42bdc003ca654e7da1907fbfa3a7649f5                       0.0s
 => => naming to docker.io/library/onc-certification-g10-test-kit-main_inferno                                     0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Building worker
[+] Building 1.3s (14/14) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 38B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 35B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/ruby:2.7.3                                                      0.7s
 => [1/9] FROM docker.io/library/ruby:2.7.3@sha256:ee2b19ced1d44600963c52691b9b6975e209286e7168230d03afe7894f9c81  0.0s
 => [internal] load build context                                                                                  0.4s
 => => transferring context: 8.68kB                                                                                0.4s
 => CACHED [2/9] RUN mkdir -p /opt/inferno/                                                                        0.0s
 => CACHED [3/9] WORKDIR /opt/inferno/                                                                             0.0s
 => CACHED [4/9] ADD *.gemspec /opt/inferno/                                                                       0.0s
 => CACHED [5/9] ADD Gemfile* /opt/inferno/                                                                        0.0s
 => CACHED [6/9] ADD lib/onc_certification_g10_test_kit/version.rb /opt/inferno//lib/onc_certification_g10_test_k  0.0s
 => CACHED [7/9] RUN gem install bundler                                                                           0.0s
 => CACHED [8/9] RUN bundle install                                                                                0.0s
 => CACHED [9/9] ADD . /opt/inferno/                                                                               0.0s
 => exporting to image                                                                                             0.1s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:8028db923977edda688cc57a4c257ee42bdc003ca654e7da1907fbfa3a7649f5                       0.0s
 => => naming to docker.io/library/onc-certification-g10-test-kit-main_worker                                      0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
WARNING: Found orphan containers (onc-certification-g10-test-kit-main_terminology_builder_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting onc-certification-g10-test-kit-main_validator_service_1 ... done
Creating onc-certification-g10-test-kit-main_inferno_run         ... done
I, [2022-03-24T19:31:34.042421 #1]  INFO -- : (0.001931s) PRAGMA foreign_keys = 1
I, [2022-03-24T19:31:34.042578 #1]  INFO -- : (0.000042s) PRAGMA case_sensitive_like = 1
D, [2022-03-24T19:31:34.046877 #1] DEBUG -- : (0.000125s) SELECT sqlite_version()
D, [2022-03-24T19:31:34.048649 #1] DEBUG -- : (0.001520s) CREATE TABLE IF NOT EXISTS 'schema_info' ('version' integer DEFAULT (0) NOT NULL)
D, [2022-03-24T19:31:34.050603 #1] DEBUG -- : (0.001740s) SELECT * FROM 'schema_info' LIMIT 1
D, [2022-03-24T19:31:34.052456 #1] DEBUG -- : (0.001588s) SELECT 1 AS 'one' FROM 'schema_info' LIMIT 1
D, [2022-03-24T19:31:34.054208 #1] DEBUG -- : (0.001475s) SELECT count(*) AS 'count' FROM 'schema_info' LIMIT 1
D, [2022-03-24T19:31:34.056206 #1] DEBUG -- : (0.001733s) SELECT 'version' FROM 'schema_info' LIMIT 1

```

**Comment by Jammjammjamm** [comment]
That is what the output should look like if you've successfully setup the database already. It probably is worth running `docker-compose down --remove-orphans` to get rid of the orphan containers.

In the `data` folder, I would expect to see a file named `inferno_production.db` with a non-zero size. Do you see any zero-size files there?

Have you changed `config/database.yml` or either of the docker compose files at all? Also, what platform are you running this on?

**Comment by dkriebel** [comment]
Unfortunately removing the orphan containers has the same result. I ran your statement, re-ran setup.sh just to be safe and then tried to build the terminology again, but get the same error.

I do see a non-zero file as you described. Nope, I haven't touched any of the yml files.
![image](https://user-images.githubusercontent.com/27783502/160002334-7a657804-55b9-4ee1-b819-375671cb4f17.png)

This is running on:
Windows 10 Pro - Build 19042.1586
Docker 4.5.1
Docker is using WSL 2 Distro, integrated with Ubuntu 20.04.4

**Comment by Jammjammjamm** [comment]
Hmm, based on the size 0 `inferno_development.db`, it looks like the terminology build is running in development mode and trying to use the development database. For now, running this command should build the development database so that the terminology build can run:
```
docker-compose -f terminology_compose.yml run terminology_builder bundle exec inferno migrate
```

**Comment by Jammjammjamm** [comment]
I believe the real fix is to add this to the beginning of `Dockerfile.terminology`:
```
ENV APP_ENV=production
```
I'll be verifying that everything still works with this and opening a PR soon.

**Comment by dkriebel** [comment]
Building the development database seems to have done the trick - thank you!

We are actually experiencing another issue when actually running tests, where the "main_worker" immediately shuts off with the an "Error connecting to Redis" message, but I would imagine it's not related to this terminology issue, in which case I can create a new issue if we continue to have a problem with it.

**Comment by Jammjammjamm** [comment]
I see those error messages if the worker starts before redis, but it keeps retrying, and once redis is available, it connects and everything works.
