### ISSUE TITLE
Asymmetric Client refresh token tests - inconsistencies between 9.12.3.01 and 9.12.3.03

### ISSUE THREAD

**Issue by jwjahns** [onc-healthit/onc-certification-g10-test-kit#548]
Hello,

Test 9.12.3 (Token Refresh for asymmetric clients launch) appears to be mixing SMART STU2 and STU1 code.
Test 9.12.3.01 pulls from test `smart_token_refresh_stu2`:
https://github.com/onc-healthit/onc-certification-g10-test-kit/blob/64bbabe5b9e9335bfdaec1a8a8fa000efe2c6ab9/lib/onc_certification_g10_test_kit/base_token_refresh_stu2_group.rb#L33-L34

But test 9.12.3.03 pulls from test `smart_token_refresh`:
https://github.com/onc-healthit/onc-certification-g10-test-kit/blob/64bbabe5b9e9335bfdaec1a8a8fa000efe2c6ab9/lib/onc_certification_g10_test_kit/base_token_refresh_stu2_group.rb#L40-L42

The result is a different refresh token request between these two tests. You can see this using the reference server, e.g.:
https://inferno.healthit.gov/suites/g10_certification/gVKFKnQsmfl#g10_certification-Group06-g10_asymmetric_launch

In the above test run, Test 9.12.3.01 includes a `client_assertion` in the Request Body. Test 9.12.3.03 does not. I think this is due to the above code discrepancy.

**Comment by Jammjammjamm** [comment]
You are correct, thank you for reporting this. We will fix this ASAP.

**Comment by Jammjammjamm** [comment]
We released version 6.0.1 yesterday which should address this issue.
