### ISSUE TITLE
Syntax error when running run.sh locally (FI-1504)

### ISSUE THREAD

**Issue by sstanciu5** [onc-healthit/onc-certification-g10-test-kit#55]
Hi all.

I pulled in the last version of this repository and tried to run `run.sh` to startup the docker images.

On startup I'm getting the following errors:
```
inferno_1            | ! Unable to load application: SyntaxError: /opt/inferno/lib/onc_certification_g10_test_kit/bulk_data_authorization.rb:27: syntax error, unexpected symbol literal, expecting `do' or '{' or '('
inferno_1            |     input :bulk_client_id,
inferno_1            |           ^
inferno_1            | /opt/inferno/lib/onc_certification_g10_test_kit/bulk_data_authorization.rb:28: syntax error, unexpected ',', expecting `end'
inferno_1            | ...  title: 'Bulk Data Client ID',
inferno_1            | ...                              ^
inferno_1            | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
inferno_1            | /opt/inferno/lib/onc_certification_g10_test_kit/multi_patient_api.rb:1:in `require_relative': /opt/inferno/lib/onc_certification_g10_test_kit/bulk_data_authorization.rb:27: syntax error, unexpected symbol literal, expecting `do' or '{' or '(' (SyntaxError)
inferno_1            |     input :bulk_client_id,
inferno_1            |           ^
inferno_1            | /opt/inferno/lib/onc_certification_g10_test_kit/bulk_data_authorization.rb:28: syntax error, unexpected ',', expecting `end'
inferno_1            | ...  title: 'Bulk Data Client ID',
inferno_1            | ...                              ^
```

A little digging around leads me to believe the cause is this pr https://github.com/onc-healthit/onc-certification-g10-test-kit/pull/50 .

Changing the order so that `description` is called last and doesn't require a comma at the end seems to resolve this but I don't think it's a solution.

Any suggestions on this ?

**Comment by Jammjammjamm** [comment]
We just merged a fix for this: https://github.com/onc-healthit/onc-certification-g10-test-kit/pull/56

So if you pull the most recent update to `main`, it should work.

It is likely that you want to use our latest release, though: https://github.com/onc-healthit/onc-certification-g10-test-kit/releases/tag/v2.0.0

I am making a note to update our README to direct users to our official releases rather than just cloning the repo.

**Comment by sstanciu5** [comment]
Will go ahead and close this.
Thank you for the quick turnaround!

**Comment by Jammjammjamm** [comment]
I'm going to go ahead and keep this open until we have a fix merged and released.
