### ISSUE TITLE
Token Introspection Endpoint is Ignored

### ISSUE THREAD

**Issue by Justin-Ramm** [onc-healthit/onc-certification-g10-test-kit#550]
In test 9.11.2, Inferno unexpectedly requires and always uses the introspection endpoint from the .well-known configuration. The "Token Introspection Endpoint" value entered as part of the Run Tests config is always ignored (and if a value is present in .well-known, this user-entered value is overwritten during the test).

This is problematic if the introspection endpoint is not returned in `.well-known`, because there is no possible way to pass the test in that case.

**Comment by nkamat-gwyh** [comment]
We are seeing the same failure running with SMART App Launch 1.0.0. Is this something that is required for SMART App Launch STU2 that is also running when we use version 1.0.0

**Comment by yunwwang** [comment]
@nkamat-gwyh Yes. This test also applies to SMART v1 according to (g)(10) test procedure

![image](https://github.com/user-attachments/assets/ad397e00-4cab-4212-a18c-a432b768b4b8)

@Justin-Ramm To clarify, do you mean that token introspection test fails if your server does not send `introspection_endpoint` in `well-known`?

**Comment by Justin-Ramm** [comment]
@yunwwang That is correct. When the server does not send `introspection_endpoint`, the test always fails.

`introspection_endpoint` is marked only as _recommended_ in the [SMART app launch conformance](https://build.fhir.org/ig/HL7/smart-app-launch/conformance.html#metadata) document, so we had assumed the purpose of Inferno providing a place to enter the "Token Introspection Endpoint" value was so that servers which do not return an introspection endpoint in `/.well-known/smart-configuration` still have a method to pass the test.

**Comment by Jammjammjamm** [comment]
> @nkamat-gwyh Yes, according to (g)(10) test procedure
> 
> ![image](https://private-user-images.githubusercontent.com/8761175/360971789-ad397e00-4cab-4212-a18c-a432b768b4b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDcwNzUsIm5iZiI6MTcyNDg0Njc3NSwicGF0aCI6Ii84NzYxMTc1LzM2MDk3MTc4OS1hZDM5N2UwMC00Y2FiLTQyMTItYTE4Yy1hNDMyYjc2OGI0YjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMTIwNjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWZjNDQwYTBlZmMzZjczZGMzYjJkNGI5NDIwY2JiM2Y2Y2MxMWU5NjJlZDgzOWY4OGNjNWM3MjY4NDEwY2M5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D1xshtEGyvNLpgncYtACnATSP1FszuODCUtdm97l0jY)


Actually, we misinterpreted the test procedure here, and 170.215(c) can refer to either SMART v1 or SMART v2. So you are correct that these tests should not be required for SMART v1, and we will revert that change.

**Comment by Jammjammjamm** [comment]
@nkamat-gwyh I have created a new issue for the your report: #553.

**Comment by nkamat-gwyh** [comment]
Thanks we will track it there

**Comment by Jammjammjamm** [comment]
@Justin-Ramm Thank you for the report, we will fix this.
