### ISSUE TITLE
Granular Scopes Tests Fail When Server Returns Separated `.r` and `.s` Scopes

### ISSUE THREAD

**Issue by Justin-Ramm** [onc-healthit/onc-certification-g10-test-kit#551]
Related to #538, but in this case Inferno reports a failure.

Separated scopes are unexpectedly not recognized in tests `9.14.1.1.2.08` and `9.14.2.1.2.08`.

![image](https://github.com/user-attachments/assets/927665fb-c917-4700-9ffc-8f64dd7ae953)

_Textual output of image copied below:_

9.14.1.1.2.08  Required granular scopes were granted

The following granular scopes were not granted: `Condition.rs?category=http://terminology.hl7.org/CodeSystem/condition-category|encounter-diagnosis`, `Condition.rs?category=http://hl7.org/fhir/us/core/CodeSystem/condition-category|health-concern`, `Observation.rs?category=http://terminology.hl7.org/CodeSystem/observation-category|laboratory`, and `Observation.rs?category=http://terminology.hl7.org/CodeSystem/observation-category|social-history`

standalone_received_scopes

`patient/Condition.r?category=http://hl7.org/fhir/us/core/CodeSystem/condition-category|health-concern   patient/Condition.r?category=http://terminology.hl7.org/CodeSystem/condition-category|encounter-diagnosis   patient/Condition.s?category=http://hl7.org/fhir/us/core/CodeSystem/condition-category|health-concern   patient/Condition.s?category=http://terminology.hl7.org/CodeSystem/condition-category|encounter-diagnosis   patient/Observation.r?category=http://terminology.hl7.org/CodeSystem-observation-category.html|social-history   patient/Observation.r?category=http://terminology.hl7.org/CodeSystem/observation-category|laboratory   patient/Observation.s?category=http://terminology.hl7.org/CodeSystem-observation-category.html|social-history   patient/Observation.s?category=http://terminology.hl7.org/CodeSystem/observation-category|laboratory  fhirUser launch/patient openid`

**Comment by Jammjammjamm** [comment]
I thought this was handled, but apparently not. Thanks for the report, we will look into this.

**Comment by Justin-Ramm** [comment]
Note that this also appears to affect test `9.9.11` in the EHR Launch with Patient Scopes section.
