### ISSUE TITLE
Fine-grained scopes (9.14) tests fail if OperationOutcomes are present

### ISSUE THREAD

**Issue by jwjahns** [onc-healthit/onc-certification-g10-test-kit#552]
Hello,

The 9.14 tests that check whether data is filtered correctly appear to not handle OperationOutcomes.

From a private Inferno deployment (running g10 test kit v6.0.0):
![image](https://github.com/user-attachments/assets/1d6d0cf0-f626-4bb2-a058-0d0b867b7637)

This FHIR ID comes from an OperationOutcome:
![image](https://github.com/user-attachments/assets/6965aa72-d09a-4aed-94df-f8826ff1280c)

If I follow the code correctly, that's because the test calls `fetch_all_bundled_resources`, which returns _all_ resource types present in the Bundle:
https://github.com/inferno-framework/us-core-test-kit/blob/14dd3bf3035dc95d893b44d081ef1368e26549dd/lib/us_core_test_kit/granular_scope_search_test.rb#L31

However, `mismatched_resource_ids` only throws out resources that don't match a granular scope for the resource under test. So, OperationOutcomes (or any other resource beyond the one under test) will never be thrown out.
https://github.com/inferno-framework/us-core-test-kit/blob/14dd3bf3035dc95d893b44d081ef1368e26549dd/lib/us_core_test_kit/granular_scope_search_test.rb#L89C5-L97C8

(if I follow right, this is technically an issue in `us-core-test-kit` code, but I assume it's preferred to post these here)

**Comment by Jammjammjamm** [comment]
That does look like what is happening. Thank you for reporting this, we will fix it.
