### ISSUE TITLE
Scope issue in Standalone Patient App - Full Access

### ISSUE THREAD

**Issue by VighneshAlevoorP** [onc-healthit/onc-certification-g10-test-kit#556]
Why below highlighted scopes are NOT automatically getting requested in the suite? There are tests related to these resources but are not getting requested during Standalone Patient App - Full Access test.

**patient/ServiceRequest.rs patient/Coverage.rs patient/MedicationDispense.rs patient/RelatedPerson.rs**

<img width="684" alt="image" src="https://github.com/user-attachments/assets/e19f58da-7a64-42a3-a17c-0f0f07d50463">

**Comment by yunwwang** [comment]
Hello @VighneshAlevoorP 

When you don't use any Preset from the left side, the configuration is set to default for all US Core versions. 

A solution is that you can save your server's setting as a JSON file and reuse by upload or copy/paste. To save your own settings, click the "JSON" or "YAML" tab at the bottom
![image](https://github.com/user-attachments/assets/32fd566d-6b83-48dc-b54b-ca4cf8f1f73b)

Then click either "Download File" or the "Copy/Paste" button.

The next time you run test against your server, you can click "Upload File" button to update values.
