### ISSUE TITLE
deceasedDateTime issue

### ISSUE THREAD

**Issue by VighneshAlevoorP** [onc-healthit/onc-certification-g10-test-kit#575]
Single patient selected in standalone patient app test should it be deceased?

<img width="667" alt="image" src="https://github.com/user-attachments/assets/586c2a8b-4e6b-4558-acf9-984e2566137b">

I tried giving a additional deceased patient as shown below but Inferno is showing 0 search results.
<img width="200" alt="image" src="https://github.com/user-attachments/assets/85cc18b0-5edf-46aa-862b-893800123ded">
<img width="487" alt="image" src="https://github.com/user-attachments/assets/18ceb81e-2e68-4855-affd-4abed7c5e010">

If I make same inferno call in our postman I can see the deceased patient which I have added under additional patient IDs
<img width="639" alt="image" src="https://github.com/user-attachments/assets/e5d816c7-ca86-4a49-b7f0-5f641231a7f4">

**Comment by yunwwang** [comment]
@VighneshAlevoorP Thank you for reaching to Inferno. First question, did you grant Infenro testing client the authorization to read/search Patient with id: 1975xxx1810?

**Comment by yunwwang** [comment]
@VighneshAlevoorP Let's check this. If you select the Patient 1975xxx1810 at the Patient Selection, do you still get the same error on 10.2.09? (while you may experience different error)

**Comment by VighneshAlevoorP** [comment]
If I take 1975xxx1810 patient separately in a new run, then this tests passes. I am curious how in Inferno reference server I see 2 patients are selected. We are not authorizing id=85 right?. I have selected only id=355 in the Standalone Patient app authorization.

<img width="724" alt="image" src="https://github.com/user-attachments/assets/8e23ad7e-93d1-4477-ba82-3ab1cfad70d1">

**Comment by yunwwang** [comment]
Thanks for the verification. Inferno uses authorization token returned from server for read/seach access. When you run (g)(10) in sequence, the last token returned is from test group 3, EHR Practitioner App. In real world use cases, practitioner normally have access to more than one patients. In order to use multiple patients in Infenro testing, the token granded in EHR Practitioner App should allow Infenro to read/search these patients in testing.

**Comment by VighneshAlevoorP** [comment]
It worked for us now. Thanks for the help. Please close the ticket.
