### ISSUE TITLE
Disable SSL verification in Inferno Template

### ISSUE THREAD

**Issue by godavarthi-seshu** [onc-healthit/onc-certification-g10-test-kit#66]
does anyone please suggest me to disable / turn-off  Peer SSL verification certificate in Inferno template client?  

please provide details if there are any config files

**Comment by Jammjammjamm** [comment]
We do not currently provide a mechanism for disabling SSL verification.

**Comment by chris-at-work** [comment]
If you have a self-signed certificate chain in a corporate environment, save your cert chain somewhere.  I will call it `ca_cert.crt` here.  If you have a test server, that will also have a generated public certificate.  If you can browse to the server and view the certificate, this is one way to do it.

Sorry to not be exact here but there is only so much I can assume.  In any event, copy the self-signed SSL cert as `ca_cert.crt`.  Be sure you are only using the public cert.  If you have generated one, you don't want to include the `.key` file (for example).

Try adding the line `SSL_CERT_FILE=/full/path/to/ca_cert.crt` in `.env`.  This should let you get past SSL errors while not disabling SSL verification.

Another way to test the cert env is to do the same thing but set `CA_CERT_FILE` for `curl` if you have that command available.  If curl works, then it is likely that `SSL_CERT_FILE` for the template will work.

**Comment by godavarthi-seshu** [comment]
Thanks for the input. we will try above suggestion and get back to you if any questions

**Comment by godavarthi-seshu** [comment]
@chris-at-work , We have tried the solutions provided by you as below and facing same SSL issue from inferno(v2.1.1).
1) We have added corporate self-signed certificate in .env file which is under onc-certification-g10-test-kit-2.1.1 folder and restarted docker images. When we run standalone patient app tests from inferno, we are getting same SSL issue (screenshot attached below).
Note: Inferno is setup in one of our local dev linux server and we are running tests from dev windows machines in chrome/edge browsers.
![Inferno_SSL_Error](https://user-images.githubusercontent.com/102810717/168095402-7813ddab-b49c-4a59-9d16-1be9b74b673d.png)

our .env file looks like:
                    JS_HOST=""
                    INFERNO_HOST=http://localhost/
                    G10_VALIDATOR_URL=http://validator_service:XXXX
                    REDIS_URL=redis://redis:XXXX
                    export SSL_CERT_FILE=/opt/jboss/docker/ca_cert.crt
                    # Terminology build variables
                    UMLS_API_KEY=
                    CLEANUP=

2) We are able to access FHIR resources using curl command (with-in same linux server) like below:
                  curl --cacert ca_cert.crt -H "Authorization: Bearer <Access_Token>" <FHIR Service URL>

Could you please suggest any other solution?

**Comment by yunwwang** [comment]
Hello @godavarthi-seshu  

I will close this issue as no activities over the last few months. If you experience similar issue in the future, you can reopen this issue or create a new one. 

Thank you

**Comment by adunsulag** [comment]
@yunwwang this continues to be an issue as far as I have tested against the most recent release version 2.3.0.  I followed the same steps as @godavarthi-seshu although I saw he has an 'export' instruction in his .env file and I removed that as its not compatible with ruby .env files.  
```
JS_HOST=""
INFERNO_HOST=http://localhost
G10_VALIDATOR_URL=http://validator_service:4567
REDIS_URL=redis://redis:6379/0

# Full path to a custom JWKS json file, will use lib/onc_certification_g10_test_kit/bulk_data_jwks.json if left blank
# G10_BULK_DATA_JWKS=

# Flags for features under development
US_CORE_4_ENABLED=false
BULk_DATA_V2_ENABLED=false

# Terminology build variables
UMLS_API_KEY=
CLEANUP=
SSL_CERT_FILE=/opt/inferno/data/testcert.crt
```
Upon editing the .env file in my local folder I rebuild the images and verified the .env is populated in the container docker:
```
docker-compose build --no-cache inferno
```

I stored my certificate in the /opt/inferno/data/ directory and verified it is accessible via curl from within the docker
```
curl --cacert data/testcert.crt https://10.1.0.9:9300/apis/default/fhir/metadata
```

Our FHIR server mandates SSL access (to be ONC compliant) and so we'd really like to have a test environment that can work with self-signed certificates for our internal developers and infrastructure.

I searched in the inferno codebase and could not see anywhere the SSL_CERT_FILE constant was used.  Is there an underlying library that grabs the ruby .env variable that I can step through to try and figure out why this isn't populating?  If there was a segment of code (class file, directory, library) that someone could point out me in the right direction to investigate I'd be happy to look deeper into this.
