### ISSUE TITLE
Terminology Errors in Multi-Patient API Tests (FI-1527)

### ISSUE THREAD

**Issue by akkillewale** [onc-healthit/onc-certification-g10-test-kit#73]
With g10 version of Inferno test kit, we are seeing errors related to terminology which aren't reported as errors in v1.9 Program Edition. 

**Example 1:** Group Compartment Export Validation Test (Immunization: 5.13.14, BDGV-14 in v1.9)
Error: Immunization.subpotentReason[0].coding[0]: Unknown Code http://terminology.hl7.org/CodeSystem/immunization-subpotent-reason#**partialdose** in http://terminology.hl7.org/CodeSystem/immunization-subpotent-reason for 'http://terminology.hl7.org/CodeSystem/immunization-subpotent-reason#partialdose'
Response:
"subpotentReason": [
		{
			"coding": [
				{
					"system": "http://terminology.hl7.org/CodeSystem/immunization-subpotent-reason",
					"code": "partialdose",
					"display": "Partial Dose"
				}
			],
			"text": "Partial Dose"
		}
	],

**Example 2:** Group Compartment Export Validation Test (DocumentReference: 5.13.12, BDGV-12 in v1.9)
Error: DocumentReference.meta.tag[0]: Coding.system must be an absolute reference, not a local reference
Response:
"resourceType": "DocumentReference",
	"id": "12342040",
	"meta": {
		"lastUpdated": "2022-01-13T14:06:06.913-05:00",
		"source": "https://abc.open.xyz.com:4438/R4/fhir-ReleaseAll",
		"profile": [
			"http://hl7.org/fhir/us/core/StructureDefinition/us-core-documentreference"
		],
		"security": [
			{
				"system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
				"code": "NOPAT",
				"display": "no disclosure to patient, family or caregivers without attending provider's authorization"
			},
			{
				"system": "http://terminology.hl7.org/CodeSystem/v3-Confidentiality",
				"code": "N",
				"display": "normal"
			}
		],
		"tag": [
			{
				"system": "IsDocumentLocked",
				"code": "FALSE"
			},
			{
				"system": "PatCareDocGuid",
				"code": "1234"
			},
			{
				"system": "DocumentType",
				"code": "4"
			}
		]

We can resolve these but I wanted to find out if these terminology issues (some of which were treated as Warnings in v1.9) are now going to be reported as failures? I did not see this change mentioned in the release notes, may be I missed it.

**Comment by Jammjammjamm** [comment]
> Error: DocumentReference.meta.tag[0]: Coding.system must be an absolute reference, not a local reference

That looks like an error coming from the FHIR validator. We did update the version of the validator we're using recently. Do you see it when running 1.9 right now? 1.9 and 2.0 use the same validator, so I would expect to see that error in both.

It'll take a little more time to look into the other error.

**Comment by akkillewale** [comment]
The latest run as of this morning does not throw these as errors. Same test bed and patients used in both v1.9 and g10 version.
https://inferno.healthit.gov/inferno/6NcaTVdOih8/test_sets/test_procedure/

Regarding the other error #2, "partialdose'" is a valid code in HL7 Terminology R3.1.0 but its not in R4.0.1

**Comment by Jammjammjamm** [comment]
It depends on what the individual errors are. Those should be fixed.

**Comment by akkillewale** [comment]
thank you, any information on DocumentReference.meta.tag[0]?

**Comment by yunwwang** [comment]
That is an error in the resource. In your resource, the tag is
```
"tag": [
{
"system": "IsDocumentLocked",
"code": "FALSE"
},
```
As the error indicated, tag.system has to be an absolute url.
