### ISSUE TITLE
Inferno reference read issue

### ISSUE THREAD

**Issue by liquid36** [onc-healthit/onc-certification-g10-test-kit#76]
Hi! We are having a issue with the reference read test in all of the resource. 

![image](https://user-images.githubusercontent.com/3813270/162264526-be9bb7d7-adc8-4eaa-995c-1d192cdb5fbc.png)

![image](https://user-images.githubusercontent.com/3813270/162264594-126bc19b-ee8c-4f66-a681-05d3e8dc32c0.png)

Inferno does not provide us the HTTP Request  in order to be sure that  the endpoints are correct. Also it said that it is an 401 Unauthorized Error but cannot be possible. any idea what could the problem be? 

This is the CareTeam resource: 

```json
{
        "resourceType": "CareTeam",
        "id": "1",
        "text": {
            "status": "generated",
            "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Success!</div>"
        },
        "status": "active",
        "category": [
            {
                "coding": {
                    "system": "http://loinc.org",
                    "code": "LA27976-2",
                    "display": "Encounter-focused care team"
                }
            }
        ],
        "subject": {
            "reference": "1",
            "type": "Patient"
        },
        "participant": [
            {
                "role": {
                    "coding": {
                        "system": "http://snomed.info/sct",
                        "code": "17561000",
                        "display": "Cardiologist"
                    }
                },
                "member": {
                    "reference": "Practitioner/1",
                    "type": "Practitioner"
                }
            }
        ]
    }
```

Thank in advance

**Comment by yunwwang** [comment]
The logging issue is resolved in PR: https://github.com/inferno-framework/us-core-test-kit/pull/24. The fix will be incorporated in next g10-test-kit release.

This error means that Inferno is not authorized to access Practitioner/1 resource. Could you double check 
1) if Practitioner/read is in the SMART launch scope (test 1.2 and 3.2)
2) if Practitioner read test passed for the same id Practitioner/1 (test 4.29)

**Comment by liquid36** [comment]
yes, i double checked that. 

1. Practitioner/*.read  is in the scope.
2. Yes, I passed all the practitioner test: 

![image](https://user-images.githubusercontent.com/3813270/162274317-fc01927a-b162-4f32-826a-aac19b30d320.png)

It seem to be a general problem because it also fail with patient reference, for example on Provenance Resource. 

```json
{
        "resourceType": "Provenance",
        "id": "1",
        "target": [
            {
                "reference": "Patient/1",
                "type": "Patient"
            }
        ],
        "recorded": "1994-07-03T08:54:59+00:00",
        "patient": {
            "reference": "Patient/1",
            "type": "Patient"
        },
        "agent": [
            {
                "onBehalfOf": {
                    "reference": "Organization/1",
                    "type": "Organization"
                },
                "type": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
                            "code": "AUT"
                        }
                    ]
                },
                "who": {
                    "reference": "Practitioner/1",
                    "type": "Practitioner"
                }
            },
            {
                "type": {
                    "coding": [
                        {
                            "system": "http://hl7.org/fhir/us/core/CodeSystem/us-core-provenance-participant-type",
                            "code": "transmitter",
                            "display": "Transmitter"
                        }
                    ]
                },
                "who": {
                    "reference": "Organization/Payer1"
                }
            },
            {
                "type": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/provenance-participant-type",
                            "code": "author",
                            "display": "Author"
                        }
                    ]
                },
                "who": {
                    "reference": "Organization/Author1"
                }
            }
        ]
    }
```


I will wait until the next release to see how the endpoints look like. Do you know when it will be released?

**Comment by dwebe003** [comment]
I would like to add that I am experiencing the same result. I am getting both 500 and 401 errors. 
Scope input: launch/patient openid fhirUser offline_access patient/*.read practitioner/*.read
![Screen Shot 2022-04-08 at 11 20 45 AM](https://user-images.githubusercontent.com/6394944/162499474-8ba91b42-db2d-4d88-a4aa-212ce8141875.png)

**Comment by dwebe003** [comment]
Ah I believe it's an ID issue. I am supplying the wrong provider ID to "Practitioner/id". The way our tables are setup makes it difficult to provide the proper ID, so I am just considering changing each role's reference to be of the form "CareTeam/careteam_id"

**Comment by yunwwang** [comment]
Now the RC is out. Please check if the new RC gives more information about failed reference check. BTW, the new release also changes the testing logic for reference validation so you may experience more or less errors.

https://inferno-dev.healthit.gov/
