### ISSUE TITLE
DocumentReference Custodian Discrepancy

### ISSUE THREAD

**Issue by joerocca** [onc-healthit/onc-certification-g10-test-kit#81]
Hello,

The 4.10.09 test under DocumentReference Tests on the Single Patient API step of the Inferno tests shows that the custodian property is required, but if you look at the must support content in the [FHIR DocumentReference documentation](http://hl7.org/fhir/us/core/StructureDefinition-us-core-documentreference.html) under the "Snapshot Table (Must Support)" tab, you will notice that `custodian` is not shown. Is this a mistake in the Inferno tests or is `custodian` actually required?

Thank you!

**Comment by yunwwang** [comment]
Hello @joerocca Thank you for reaching to us. 

The link you provided is US Core v4.0.0

ONC (g)(10) test procedure requires US Core v3.1.1 which can be found here: http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-documentreference.html

In US Core v3.1.1, DocumentReference.custodian is marked as MustSupport.
