### ISSUE TITLE
Multi-Patient API Provenance Test 5.3.21 Failing - agent.onBehalfOf

### ISSUE THREAD

**Issue by akkillewale** [onc-healthit/onc-certification-g10-test-kit#82]
We are seeing this error with g(10) test kit "Could not find agent.onBehalfOf in the 23 provided resources". 
This test has passed with v1.9 version using same test data.

For the specific use case in DiagnosticReport where onBehalfOf is not present, this data was sent to EMR from a 3rd party lab. This lab system does not have a represented org id in the EMR, usually just a text value. Is it expected that in g(10) test kit we need to somehow represent the lab's managing organization?

Get URL: {fhirbaseurl}[/Provenance/DiagnosticReport-OR20392300680]

{
	"resourceType": "Provenance",
	"id": "DiagnosticReport-OR20402400680",
	"meta": {
		"lastUpdated": "2022-01-17T09:49:20.97-05:00",
		"source": "https://scmfhirconnect.open.allscripts.com:4438/R4/fhir-ReleaseAll",
		"profile": [
			"http://hl7.org/fhir/us/core/StructureDefinition/us-core-provenance"
		]
	},
	"language": "en-US",
	"target": [
		{
			"reference": "https://scmfhirconnect.open.allscripts.com:4438/R4/fhir-ReleaseAll/DiagnosticReport/OR20402400680",
			"type": "DiagnosticReport",
			"display": "Angiocardiogram Left Heart1 | Category: Cardiology | Created: 17-Jan-2022 09:49"
		}
	],
	"occurredDateTime": "2022-01-17T09:49:19-05:00",
	"recorded": "2022-01-17T09:49:20.97-05:00",
	"location": {
		"reference": "https://scmfhirconnect.open.allscripts.com:4438/R4/fhir-ReleaseAll/Location/6500610",
		"type": "Location",
		"display": "1 East-102-A"
	},
	"activity": {
		"coding": [
			{
				"system": "http://terminology.hl7.org/CodeSystem/v3-DataOperation",
				"code": "CREATE",
				"display": "create"
			}
		],
		"text": "create"
	},
	"agent": [
		{
			"type": {
				"coding": [
					{
						"system": "http://terminology.hl7.org/CodeSystem/provenance-participant-type",
						"code": "author",
						"display": "Author"
					}
				],
				"text": "Author"
			},
			**"who": {
				"type": "Organization",
				"display": "Vancouver Labs"
			}**
		},
		{
			"type": {
				"coding": [
					{
						"system": "http://hl7.org/fhir/us/core/CodeSystem/us-core-provenance-participant-type",
						"code": "transmitter",
						"display": "Transmitter"
					}
				],
				"text": "Transmitter"
			},
			"who": {
				"reference": "https://scmfhirconnect.open.allscripts.com:4438/R4/fhir-ReleaseAll/Organization/100610",
				"type": "Organization",
				"display": "Scm-Flamingo20.0"
			}
		}
	]
}

**Comment by yunwwang** [comment]
@akkillewale Thank for your reaching to us. Yes, agent.onBehalfOf is a MustSupport element. Sever implementation must demonstrate it is capable of populating that element. agent.onBehalfOf is FHIR Reference type. FHIR allows Reference to have display text only

**Comment by akkillewale** [comment]
Thanks, so we need to show at least 1 example of this data for this resource.
