### ISSUE TITLE
DiagnosticReport Note refer to Laboratory 

### ISSUE THREAD

**Issue by liquid36** [onc-healthit/onc-certification-g10-test-kit#84]
Hi! I think that I found an issue when validating `DianosticReport for Report and Note`, it's refer to `Laboratory Results`. 

![image](https://user-images.githubusercontent.com/3813270/162774055-fdb480aa-4375-4947-88f2-bb24f4b78a2a.png)

**Comment by Jammjammjamm** [comment]
Do any of the DiagnosticReports returned in the Note tests include the lab profile in `meta.profile`?

**Comment by Jammjammjamm** [comment]
The hl7 validator validates resources against profiles listed in `meta.profile` in addition to the profile we tell it to validate against.

**Comment by liquid36** [comment]
that's right! Sorry, that was my mistake.
