### ISSUE TITLE
Provenance validation in multipatient tests

### ISSUE THREAD

**Issue by nathanloyer** [onc-healthit/onc-certification-g10-test-kit#86]
For the Provenance portion of Bulk/Multi-Patient tests, there seem to be 2 sets of calls being made: AllergyIntolerance and CarePlan. All of the relevant scenarios are contained in the AllergyIntolerance responses, and all required elements are being sent. The CarePlan set contains a single response, which happens to be a Practitioner and thus includes the required agent.onBehalfOf element. The test fails because there is not also an example of agent.type.coding.code:transmitter in the CarePlan response, despite being contained in the relevant AllergyIntolerance responses. Should the test pass given the required scenarios/elements are contained within the full set of responses, or is it intended to assess the subsets distinctly?

[chat](https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Provenance.20Logic)

**Comment by yunwwang** [comment]
The problem is that Inferno runs must_support validation per output file instead of per resource type. We will fix that in next release. At the same time, the work around is merging Provenance of AllergyIntolerance and Provenance of CarePlan into one file which should give you a green check.

**Comment by nathanloyer** [comment]
testing this out today, thanks for the fast fix
