### ISSUE TITLE
Pre-Release Question

### ISSUE THREAD

**Issue by akkillewale** [onc-healthit/onc-certification-g10-test-kit#89]
This is more of a question than an issue. 2.1.RC1 (April update) is published at inferno-dev.healthit.gov, what is the timeframe for a pre-release to deploy to production? We have fixes in RC1 which we need for our attestation.

**Comment by yunwwang** [comment]
We are trying to finalize release v2.1 today

**Comment by akkillewale** [comment]
Thanks yunwwang

**Comment by yunwwang** [comment]
v2.1.0 is released
