### ISSUE TITLE
Single Patient API Test - Ruby Error without "Additional Patient Ids"

### ISSUE THREAD

**Issue by spclbp** [onc-healthit/onc-certification-g10-test-kit#93]
WIth the newly released ONC Certification (g)(10) Standardized API V.2.1.0, we've come upon a new error. First we perform the EHR Launch test to get our access token, then head over to the Single Patient API tests. We're getting the Ruby error below when we do not fill in the additional patient ids field:Error: 

undefined method `split' for nil:NilClass
/usr/local/bundle/gems/us_core_test_kit-0.2.1/lib/us_core_test_kit/search_test.rb:436:in `patient_id_list'

Work around:  Enter patient ids into the additional patient ids field -- even if it's the same id that's already present in the "Patient ID from SMART App Launch" field.

**Comment by arscan** [comment]
Thanks for the report @spclbp -- we're working on a fix and will likely provide a patch release ASAP.
