### ISSUE TITLE
MULTI PATIENT-API jwks url throws SSL hand-shake exception

### ISSUE THREAD

**Issue by dileeprt** [onc-healthit/onc-certification-g10-test-kit#96]
The below issue is only seen on ONC Certification (g)(10) Standardized API **V.2.1.1** and NOT seen on **V.2.1.0**

When nimbus jose is trying to load jwks url (https://inferno.healthit.gov/suites/custom/g10_certification/.well-known/jwks.json), the tool throws SSL hand-shake exception.
Below is the description of the exception:
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

Could you please let us know if FHIR side changes are required for this.

**Comment by yunwwang** [comment]
Inferno updates its SSL certificate last night. See (https://chat.fhir.org/#narrow/stream/179309-inferno/topic/SSL.20Certificate.20Expired)

Did you test this yesterday or this morning?

**Comment by yunwwang** [comment]
The SSL certification on reference server is fixed.

**Comment by naveen101112** [comment]
Hi @dileeprt,

I am not getting idea of how Multi-Patient API works. Can you please help me out on how the flow and what I need to build exactly to handle the Multi-Patient API requests.
