### ISSUE TITLE
Inferno Immunization test seemingly making a request to improperly formatted FHIR URL

### ISSUE THREAD

**Issue by VinnieMaida** [onc-healthit/onc-certification-g10-test-kit#97]
Hello,

In running the Inferno tests against a test FHIR API of mine, specifically the `4.12.01` Immunization tests within the `4 - Single Patient API` group of tests, the tests are failing because one of the tests is making a seemingly improperly formatted request against my test FHIR API.

The `FHIR Endpoint` input value I'm giving the test before running it is `https://<myFHIRApiBaseUrl>/api/r4`, and the `4.12.01` test makes a total of 22 HTTP requests against the FHIR URL that I provided using the provided `/r4` format, and 21 of those requests seem to make a request like `https://<myFHIRApiBaseUrl>/api/r4/Immunization?patient=<myPatientID>&_getpagesoffset=0&_count=10`, which work just fine, BUT there is one test that is making a request that's lacking the `r4` part of the FHIR URL that I gave, so it looks like this instead `https://<myFHIRApiBaseUrl>/api/Immunization?patient=<myPatientID>&_getpagesoffset=0&_count=10`, which you can see is missing the `r4` part of the request, which is not implemented in my API, and so is resulting in a 404 that's failing this test. 

Am I missing something here as to why this test is making a request that's missing the end of the FHIR URL that I gave as a test input? Thanks for any help that you can provide!

**Comment by yunwwang** [comment]
Hello @VinnieMaida Inferno uses the `Bundle.link.url` to retrieve the next page of result. Could you verify the `next` link in the Bundle resource before the failed request? The element looks like this:

![image](https://user-images.githubusercontent.com/8761175/163677401-e88590ed-3411-4648-a687-82a03b0022d5.png)

**Comment by VinnieMaida** [comment]
Thank you very much for the info! The tests using the `next` url makes a lot of sense! Given that info, I think I've pinned down the problem to being an issue with how my FHIR server constructs those `relation` url values, specifically when it's given a POST-based search (which is one of the searching tests that's being run), so I should be able to resolve things on my end, now! Thank you very much!
