### ISSUE TITLE
Invalid launch parameter tests exceed spec requirements

### ISSUE THREAD

**Issue by Jammjammjamm** [onc-healthit/onc-certification-g10-test-kit#98]
The _SMART Invalid Launch Parameter_ tests (6.4) require that a server fail to authorize a client which sends an invalid `launch` parameter. The SMART App Launch IG [states that clients send back the same `launch` parameter they received from the server,](http://hl7.org/fhir/smart-app-launch/1.0.0/#step-1-app-asks-for-authorization) but does not state any requirements for how the server handles an invalid or missing `launch` parameter.

See [discussion on zulip.](https://chat.fhir.org/#narrow/stream/179170-smart/topic/Server.20response.20when.20client.20sends.20bad.20launch.20parameter)

**Comment by alps8** [comment]
@yunwwang @arscan 
Hi,
  We are currently using [v2.2.1] and this test case is failing for us. Is there an ETA or version number where this constraint will be removed? Thanks.
